/* MYBODY 2.0 advanced workout logger: per-set tracking, RPE, history, PRs, rest timer, progressive overload. */
(function(){
  const KEY='decemberTracker.v1';
  const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
  const todayKey=()=>new Date().toLocaleDateString('en-CA');
  let restInterval=null,restEndsAt=0;

  function style(){if(q('#advancedWorkoutStyles'))return;const s=document.createElement('style');s.id='advancedWorkoutStyles';s.textContent=`
    .aw-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.aw-toolbar button{flex:1;min-width:120px}.aw-history{margin:12px 0;padding:15px}.aw-history h4{margin:0 0 8px}.aw-history-list{display:grid;gap:8px}.aw-history-row{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--line);font-size:12px}.aw-history-row:last-child{border-bottom:0}.aw-set-table{margin-top:13px;border-top:1px solid var(--line)}.aw-set-head,.aw-set-row{display:grid;grid-template-columns:38px 1fr 1fr 1fr 48px;gap:7px;align-items:center}.aw-set-head{padding:10px 0 6px;color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.06em}.aw-set-row{padding:8px 0;border-top:1px solid color-mix(in srgb,var(--line) 65%,transparent)}.aw-set-row input{padding:10px 6px;text-align:center;font-weight:750}.aw-set-num{font-weight:850;color:var(--muted);text-align:center}.aw-done{width:38px;height:38px;border-radius:50%;border:1px solid var(--line);background:var(--bg);color:var(--muted);font-weight:900}.aw-done.done{background:var(--accent2);border-color:var(--accent2);color:#07100d}.aw-add-set{margin-top:9px;width:100%;border:1px dashed var(--line);background:transparent;color:var(--accent);border-radius:11px;padding:10px;font-weight:800}.aw-extras{display:flex;gap:8px;flex-wrap:wrap;margin-top:9px}.aw-extras button{flex:1;border:1px solid var(--line);background:var(--bg);color:var(--text);border-radius:10px;padding:9px;font-size:11px;font-weight:750}.aw-tip{margin-top:10px;padding:10px;border-radius:11px;background:#8b7cff12;color:var(--accent);font-size:11px;line-height:1.35}.aw-pr{color:#ffd166;font-weight:850}.aw-rest{position:fixed;z-index:80;right:16px;bottom:92px;min-width:145px;padding:12px 14px;border-radius:18px;background:var(--text);color:var(--bg);box-shadow:0 16px 40px #0007;display:none}.aw-rest.show{display:block}.aw-rest strong{font-size:24px}.aw-rest small{display:block;opacity:.7;margin-top:2px}.aw-rest-actions{display:flex;gap:6px;margin-top:8px}.aw-rest button{border:0;border-radius:9px;padding:7px 9px;font-weight:800}.aw-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0}.aw-summary div{padding:11px;border-radius:12px;background:var(--bg);border:1px solid var(--line)}.aw-summary small{display:block;color:var(--muted);font-size:10px}.aw-summary b{display:block;margin-top:4px}.exercise>.exercise-inputs{display:none}.exercise>.exercise-actions{display:none}@media(max-width:520px){.aw-set-head,.aw-set-row{grid-template-columns:30px 1fr 1fr .8fr 42px}.aw-set-row input{font-size:13px}.aw-summary{grid-template-columns:1fr 1fr 1fr}}
  `;document.head.appendChild(s)}

  function stateSafe(){try{return typeof state!=='undefined'?state:JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
  function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));window.dispatchEvent(new Event('mybody-data-changed'))}catch{}}
  function dayLog(){const s=stateSafe(),k=todayKey();s.workoutLog=s.workoutLog||{};s.workoutLog[k]=s.workoutLog[k]||{};const d=typeof selectedDay==='number'?selectedDay:0;s.workoutLog[k][d]=s.workoutLog[k][d]||{};return s.workoutLog[k][d]}
  function previousExercise(index){const s=stateSafe(),d=typeof selectedDay==='number'?selectedDay:0;const dates=Object.keys(s.workoutLog||{}).filter(x=>x!==todayKey()).sort().reverse();for(const date of dates){const log=s.workoutLog[date]?.[d];if(log?.setDetails?.[index]?.length)return {date,sets:log.setDetails[index]};if(log?.exercises?.[index]){const x=log.exercises[index];return {date,sets:Array.from({length:Number(x.sets)||0},(_,i)=>({weight:Number(x.weight)||0,reps:Number(x.reps)||0,rpe:'',done:true}))}}}return null}
  function allHistoricalSets(index){const s=stateSafe(),d=typeof selectedDay==='number'?selectedDay:0,out=[];Object.entries(s.workoutLog||{}).forEach(([date,byDay])=>{if(date===todayKey())return;const log=byDay?.[d];if(log?.setDetails?.[index])log.setDetails[index].forEach(x=>out.push({...x,date}))});return out}
  function bestEpley(index){return allHistoricalSets(index).reduce((m,x)=>{const w=Number(x.weight)||0,r=Number(x.reps)||0;return Math.max(m,w*(1+r/30))},0)}
  function suggestion(index,targetReps){const prev=previousExercise(index);if(!prev?.sets?.length)return 'Start conservatively and leave 1–2 reps in reserve on early sets.';const completed=prev.sets.filter(x=>x.done!==false),good=completed.length&&completed.every(x=>(Number(x.reps)||0)>=Number(targetReps||0)&&(x.rpe===''||Number(x.rpe)<=9));const maxW=Math.max(...completed.map(x=>Number(x.weight)||0),0);return good&&maxW?`Progressive overload: try ${Math.round((maxW+Math.max(1,Math.min(2.5,maxW*.025)))*2)/2} kg if form stays solid.`:`Repeat last load and beat reps or RPE before increasing weight.`}

  function ensureRestWidget(){if(q('#awRest'))return;const box=document.createElement('div');box.id='awRest';box.className='aw-rest';box.innerHTML=`<strong id="awRestTime">01:30</strong><small>Rest timer</small><div class="aw-rest-actions"><button id="awMinus">−15s</button><button id="awPlus">+15s</button><button id="awStop">Stop</button></div>`;document.body.appendChild(box);q('#awMinus').onclick=()=>{restEndsAt-=15000;tickRest()};q('#awPlus').onclick=()=>{restEndsAt+=15000;tickRest()};q('#awStop').onclick=stopRest}
  function startRest(seconds=90){ensureRestWidget();restEndsAt=Date.now()+seconds*1000;q('#awRest').classList.add('show');clearInterval(restInterval);restInterval=setInterval(tickRest,250);tickRest()}
  function stopRest(){clearInterval(restInterval);restInterval=null;q('#awRest')?.classList.remove('show')}
  function tickRest(){const left=Math.max(0,Math.ceil((restEndsAt-Date.now())/1000)),m=Math.floor(left/60),s=left%60,el=q('#awRestTime');if(el)el.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(left<=0){stopRest();try{navigator.vibrate?.([150,100,150])}catch{}}}

  function setFromLegacy(card,index,targetSets,targetReps){const log=dayLog();if(log.setDetails?.[index]?.length)return log.setDetails[index];const weight=Number(card.querySelector('.ex-weight')?.value)||0,reps=Number(card.querySelector('.ex-reps')?.value)||targetReps;return Array.from({length:targetSets},()=>({weight,reps,rpe:'',done:false}))}
  function syncLegacy(index,sets){const log=dayLog();log.setDetails=log.setDetails||{};log.setDetails[index]=sets;log.exercises=log.exercises||[];const completed=sets.filter(x=>x.done);const base=completed.length?completed:sets;log.exercises[index]={sets:sets.length,reps:base.length?Math.round(base.reduce((a,x)=>a+(Number(x.reps)||0),0)/base.length):0,weight:base.length?Math.max(...base.map(x=>Number(x.weight)||0)):0};persist();if(typeof updateVolumeLabels==='function')try{updateVolumeLabels()}catch{}}

  function decorateExercise(card,index){if(card.dataset.advanced==='1')return;card.dataset.advanced='1';const p=stateSafe().workouts?.[typeof selectedDay==='number'?selectedDay:0]?.exercises?.[index]||['Exercise',3,10],targetSets=Number(p[1])||3,targetReps=Number(p[2])||10;let sets=setFromLegacy(card,index,targetSets,targetReps);const prev=previousExercise(index),best=bestEpley(index);
    const table=document.createElement('div');table.className='aw-set-table';table.innerHTML=`<div class="aw-set-head"><span>Set</span><span>Kg</span><span>Reps</span><span>RPE</span><span>Done</span></div><div class="aw-set-body"></div><button class="aw-add-set" type="button">＋ Add set</button><div class="aw-extras"><button type="button" class="aw-use-last">↶ Use last</button><button type="button" class="aw-rest-btn">⏱ Rest 90s</button><button type="button" class="aw-remove-last">− Remove set</button></div><div class="aw-tip">${suggestion(index,targetReps)}</div>`;
    card.appendChild(table);
    function render(){const body=table.querySelector('.aw-set-body');body.innerHTML=sets.map((x,i)=>`<div class="aw-set-row" data-set="${i}"><span class="aw-set-num">${i+1}</span><input class="aw-weight" inputmode="decimal" type="number" step="0.5" value="${x.weight||''}" placeholder="kg"><input class="aw-reps" inputmode="numeric" type="number" value="${x.reps||targetReps}" placeholder="reps"><input class="aw-rpe" inputmode="decimal" type="number" min="1" max="10" step="0.5" value="${x.rpe||''}" placeholder="RPE"><button type="button" class="aw-done ${x.done?'done':''}">${x.done?'✓':'○'}</button></div>`).join('');body.querySelectorAll('.aw-set-row').forEach(row=>{const i=Number(row.dataset.set);row.querySelectorAll('input').forEach(inp=>inp.addEventListener('input',()=>{sets[i]={...sets[i],weight:Number(row.querySelector('.aw-weight').value)||0,reps:Number(row.querySelector('.aw-reps').value)||0,rpe:row.querySelector('.aw-rpe').value===''?'':Number(row.querySelector('.aw-rpe').value)};syncLegacy(index,sets);updatePr()}));row.querySelector('.aw-done').onclick=()=>{sets[i]={...sets[i],weight:Number(row.querySelector('.aw-weight').value)||0,reps:Number(row.querySelector('.aw-reps').value)||0,rpe:row.querySelector('.aw-rpe').value===''?'':Number(row.querySelector('.aw-rpe').value),done:!sets[i].done};syncLegacy(index,sets);render();if(sets[i].done)startRest(90)}});updatePr()}
    function updatePr(){const current=sets.reduce((m,x)=>Math.max(m,(Number(x.weight)||0)*(1+(Number(x.reps)||0)/30)),0),v=card.querySelector('.volume');if(current>best&&current>0&&v){v.textContent='PR ✦';v.classList.add('aw-pr')}}
    table.querySelector('.aw-add-set').onclick=()=>{const last=sets[sets.length-1]||{weight:0,reps:targetReps,rpe:'',done:false};sets.push({...last,done:false});syncLegacy(index,sets);render()};
    table.querySelector('.aw-remove-last').onclick=()=>{if(sets.length<=1)return;sets.pop();syncLegacy(index,sets);render()};
    table.querySelector('.aw-rest-btn').onclick=()=>startRest(90);
    table.querySelector('.aw-use-last').onclick=e=>{if(!prev?.sets?.length){e.currentTarget.textContent='No history yet';return}sets=prev.sets.map(x=>({weight:Number(x.weight)||0,reps:Number(x.reps)||targetReps,rpe:x.rpe??'',done:false}));syncLegacy(index,sets);render();e.currentTarget.textContent='Loaded ✓'};
    const meta=card.querySelector('.exercise p');if(meta&&prev){const d=new Date(prev.date+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short'});meta.textContent+=` • Last ${d}`}
    render();
  }

  function workoutSummary(){const host=q('#workout .workout-summary');if(!host||q('#awSessionSummary'))return;const box=document.createElement('div');box.id='awSessionSummary';box.className='aw-summary';box.style.gridColumn='1/-1';box.innerHTML=`<div><small>Completed sets</small><b id="awCompleted">0</b></div><div><small>Total volume</small><b id="awVolume">0 kg</b></div><div><small>PRs today</small><b id="awPRs">0</b></div>`;host.appendChild(box)}
  function refreshSummary(){const log=dayLog(),sets=Object.values(log.setDetails||{}).flat(),done=sets.filter(x=>x.done),vol=done.reduce((a,x)=>a+(Number(x.weight)||0)*(Number(x.reps)||0),0),prs=qa('#exerciseList .aw-pr').length;if(q('#awCompleted'))q('#awCompleted').textContent=`${done.length}/${sets.length}`;if(q('#awVolume'))q('#awVolume').textContent=`${Math.round(vol).toLocaleString()} kg`;if(q('#awPRs'))q('#awPRs').textContent=prs}

  function historyCard(){const panel=q('#workout');if(!panel||q('#awHistory'))return;const box=document.createElement('section');box.id='awHistory';box.className='card aw-history';const s=stateSafe(),d=typeof selectedDay==='number'?selectedDay:0,dates=Object.keys(s.workoutLog||{}).sort().reverse().filter(x=>s.workoutLog[x]?.[d]).slice(0,5);box.innerHTML=`<h4>Workout history</h4><div class="aw-history-list">${dates.length?dates.map(date=>{const l=s.workoutLog[date][d],sets=Object.values(l.setDetails||{}).flat(),volume=sets.filter(x=>x.done).reduce((a,x)=>a+(Number(x.weight)||0)*(Number(x.reps)||0),0);return `<div class="aw-history-row"><span>${new Date(date+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short'})}</span><strong>${Number(l.minutes)||0} min • ${Math.round(volume).toLocaleString()} kg</strong></div>`}).join(''):'<div class="aw-history-row"><span>No completed sessions yet</span></div>'}</div>`;q('#saveWorkout')?.insertAdjacentElement('afterend',box)}

  function decorate(){const list=q('#exerciseList');if(!list)return;qa('#exerciseList .exercise').forEach((c,i)=>decorateExercise(c,i));workoutSummary();refreshSummary();historyCard()}
  function init(){style();ensureRestWidget();decorate();const obs=new MutationObserver(()=>setTimeout(decorate,0));const list=q('#exerciseList');if(list)obs.observe(list,{childList:true,subtree:false});q('[data-tab="workout"]')?.addEventListener('click',()=>setTimeout(()=>{q('#awHistory')?.remove();decorate()},40));document.addEventListener('input',()=>setTimeout(refreshSummary,60));document.addEventListener('click',()=>setTimeout(refreshSummary,60))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();