document.addEventListener('DOMContentLoaded',function(){
'use strict';
var KEY='decemberTracker.v1',restInt=null,restEnd=0;
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function dayIndex(){var b=document.querySelector('.day-btn.active');return b?Number(b.dataset.day||0):0}
function plan(){var s=load(),i=dayIndex();return s.workouts&&s.workouts[i]?s.workouts[i]:null}
function prevLog(){var s=load(),i=dayIndex(),dates=Object.keys(s.workoutLog||{}).filter(function(d){return d<today()&&s.workoutLog[d]&&s.workoutLog[d][i]}).sort().reverse();return dates.length?s.workoutLog[dates[0]][i]:null}
function addCss(){if(document.getElementById('advWorkoutCss'))return;var st=document.createElement('style');st.id='advWorkoutCss';st.textContent='.adv-session{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0}.adv-session div{padding:11px;border:1px solid var(--line);background:var(--bg);border-radius:12px}.adv-session small{display:block;color:var(--muted);font-size:10px}.adv-session b{display:block;margin-top:4px}.adv-set-head,.adv-set-row{display:grid;grid-template-columns:32px 1fr 1fr 1fr 42px;gap:7px;align-items:center}.adv-set-head{margin-top:12px;color:var(--muted);font-size:10px;font-weight:800}.adv-set-row{margin-top:7px}.adv-set-row input{text-align:center;padding:9px 5px}.adv-done{height:38px;border-radius:10px;border:1px solid var(--line);background:var(--bg);color:var(--muted)}.adv-done.done{background:#63e6be22;color:var(--accent2);border-color:#63e6be55}.adv-actions{display:flex;gap:7px;margin-top:10px;flex-wrap:wrap}.adv-actions button,.adv-actions a{flex:1;min-width:80px;text-align:center;text-decoration:none;border:1px solid var(--line);background:var(--bg);color:var(--text);border-radius:10px;padding:9px;font-size:11px;font-weight:700}.adv-tip{margin-top:9px;font-size:10px;color:var(--muted)}.adv-rest{position:fixed;right:14px;bottom:94px;z-index:90;background:var(--text);color:var(--bg);padding:12px 14px;border-radius:16px;box-shadow:0 12px 35px #0007;display:none}.adv-rest.show{display:block}.adv-rest strong{font-size:22px}.adv-rest button{margin-top:7px;border:0;border-radius:8px;padding:6px 8px;font-weight:800}.adv-pr{color:#ffd166;font-size:10px;font-weight:800;margin-left:6px}.exercise>.exercise-inputs{display:none}.adv-history{margin-top:12px;padding:14px}.adv-history-row{display:flex;justify-content:space-between;gap:8px;padding:9px 0;border-bottom:1px solid var(--line);font-size:11px}.adv-history-row:last-child{border-bottom:0}@media(max-width:520px){.adv-set-head,.adv-set-row{grid-template-columns:26px 1fr 1fr .85fr 38px}.adv-set-row input{font-size:13px}.adv-session{grid-template-columns:repeat(3,1fr)}}';document.head.appendChild(st)}
function restWidget(){if(document.getElementById('advRest'))return;var d=document.createElement('div');d.id='advRest';d.className='adv-rest';d.innerHTML='<strong id="advRestTime">01:30</strong><div><button id="advRestMinus">−15s</button> <button id="advRestPlus">+15s</button> <button id="advRestStop">Stop</button></div>';document.body.appendChild(d);document.getElementById('advRestMinus').onclick=function(){restEnd-=15000;tickRest()};document.getElementById('advRestPlus').onclick=function(){restEnd+=15000;tickRest()};document.getElementById('advRestStop').onclick=stopRest}
function startRest(sec){restWidget();restEnd=Date.now()+(sec||90)*1000;document.getElementById('advRest').classList.add('show');clearInterval(restInt);restInt=setInterval(tickRest,250);tickRest()}
function tickRest(){var left=Math.max(0,Math.ceil((restEnd-Date.now())/1000)),m=Math.floor(left/60),s=left%60,e=document.getElementById('advRestTime');if(e)e.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');if(left<=0)stopRest()}
function stopRest(){clearInterval(restInt);restInt=null;var e=document.getElementById('advRest');if(e)e.classList.remove('show')}
function ensureLog(){var s=load(),k=today(),i=dayIndex();s.workoutLog=s.workoutLog||{};s.workoutLog[k]=s.workoutLog[k]||{};s.workoutLog[k][i]=s.workoutLog[k][i]||{};return{s:s,log:s.workoutLog[k][i],i:i,k:k}}
function priorExercise(idx){var p=prevLog();if(!p)return null;if(p.advancedSets&&p.advancedSets[idx])return p.advancedSets[idx];var x=p.exercises&&p.exercises[idx];if(!x)return null;var out=[];for(var i=0;i<Number(x.sets||0);i++)out.push({weight:Number(x.weight||0),reps:Number(x.reps||0),rpe:'',done:true});return out}
function persist(card,idx){var pack=ensureLog(),rows=Array.from(card.querySelectorAll('.adv-set-row')),sets=rows.map(function(r){return{weight:Number(r.querySelector('.adv-weight').value||0),reps:Number(r.querySelector('.adv-reps').value||0),rpe:r.querySelector('.adv-rpe').value,done:r.querySelector('.adv-done').classList.contains('done')}});pack.log.advancedSets=pack.log.advancedSets||{};pack.log.advancedSets[idx]=sets;pack.log.exercises=pack.log.exercises||[];var completed=sets.filter(function(x){return x.done});var src=completed.length?completed:sets;pack.log.exercises[idx]={sets:sets.length,reps:src.length?Math.round(src.reduce(function(a,x){return a+x.reps},0)/src.length):0,weight:src.length?Math.max.apply(null,src.map(function(x){return x.weight})):0};save(pack.s);updateSummary()}
function renderRows(card,table,sets,idx,targetReps){var body=table.querySelector('.adv-set-body');body.innerHTML='';sets.forEach(function(x,i){var r=document.createElement('div');r.className='adv-set-row';r.innerHTML='<span>'+String(i+1)+'</span><input class="adv-weight" type="number" step="0.5" placeholder="kg" value="'+(x.weight||'')+'"><input class="adv-reps" type="number" placeholder="reps" value="'+(x.reps||targetReps)+'"><input class="adv-rpe" type="number" min="1" max="10" step="0.5" placeholder="RPE" value="'+(x.rpe||'')+'"><button class="adv-done '+(x.done?'done':'')+'">'+(x.done?'✓':'○')+'</button>';body.appendChild(r);r.querySelectorAll('input').forEach(function(inp){inp.onchange=function(){persist(card,idx)}});r.querySelector('.adv-done').onclick=function(){this.classList.toggle('done');this.textContent=this.classList.contains('done')?'✓':'○';persist(card,idx);if(this.classList.contains('done'))startRest(90)}})}
function upgrade(){var cards=Array.from(document.querySelectorAll('#exerciseList .exercise'));if(!cards.length)return;var p=plan(),prev=prevLog();cards.forEach(function(card,idx){if(card.dataset.adv==='1')return;card.dataset.adv='1';var base=p&&p.exercises&&p.exercises[idx]||['Exercise',3,10],targetSets=Number(base[1]||3),targetReps=Number(base[2]||10),pack=ensureLog(),stored=pack.log.advancedSets&&pack.log.advancedSets[idx],legacy=pack.log.exercises&&pack.log.exercises[idx],sets=stored&&stored.length?stored.slice():[];if(!sets.length){for(var i=0;i<targetSets;i++)sets.push({weight:Number(legacy&&legacy.weight||0),reps:Number(legacy&&legacy.reps||targetReps),rpe:'',done:false})}var table=document.createElement('div');table.innerHTML='<div class="adv-set-head"><span>Set</span><span>Kg</span><span>Reps</span><span>RPE</span><span>Done</span></div><div class="adv-set-body"></div><div class="adv-actions"><button class="adv-use-last">Use Last</button><button class="adv-add-set">＋ Set</button><button class="adv-remove-set">− Set</button><button class="adv-rest-btn">90s Rest</button><a target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query='+encodeURIComponent(base[0]+' exercise form')+'">Form Video</a></div><div class="adv-tip">'+(prev?'Previous session available for comparison.':'No previous session yet.')+'</div>';card.appendChild(table);renderRows(card,table,sets,idx,targetReps);table.querySelector('.adv-add-set').onclick=function(){sets.push({weight:0,reps:targetReps,rpe:'',done:false});renderRows(card,table,sets,idx,targetReps);persist(card,idx)};table.querySelector('.adv-remove-set').onclick=function(){if(sets.length>1){sets.pop();renderRows(card,table,sets,idx,targetReps);persist(card,idx)}};table.querySelector('.adv-rest-btn').onclick=function(){startRest(90)};table.querySelector('.adv-use-last').onclick=function(){var old=priorExercise(idx);if(!old||!old.length){this.textContent='No history';return}sets=old.map(function(x){return{weight:Number(x.weight||0),reps:Number(x.reps||targetReps),rpe:x.rpe||'',done:false}});renderRows(card,table,sets,idx,targetReps);persist(card,idx);this.textContent='Loaded ✓'};var title=card.querySelector('h4'),old=priorExercise(idx);if(title&&old&&old.length){var maxOld=Math.max.apply(null,old.map(function(x){return Number(x.weight||0)})),maxNow=Math.max.apply(null,sets.map(function(x){return Number(x.weight||0)}));if(maxNow>maxOld&&maxNow>0){var b=document.createElement('span');b.className='adv-pr';b.textContent='PR ↑';title.appendChild(b)}}});renderHistory();updateSummary()}
function sessionSummary(){var host=document.querySelector('#workout .workout-summary');if(!host||document.getElementById('advSession'))return;var box=document.createElement('div');box.id='advSession';box.className='adv-session';box.style.gridColumn='1/-1';box.innerHTML='<div><small>Completed sets</small><b id="advSets">0</b></div><div><small>Volume</small><b id="advVol">0 kg</b></div><div><small>PRs</small><b id="advPRs">0</b></div>';host.appendChild(box)}
function updateSummary(){sessionSummary();var done=0,total=0,vol=0;document.querySelectorAll('#exerciseList .adv-set-row').forEach(function(r){total++;var d=r.querySelector('.adv-done').classList.contains('done'),w=Number(r.querySelector('.adv-weight').value||0),reps=Number(r.querySelector('.adv-reps').value||0);if(d){done++;vol+=w*reps}});var a=document.getElementById('advSets'),v=document.getElementById('advVol'),p=document.getElementById('advPRs');if(a)a.textContent=done+'/'+total;if(v)v.textContent=Math.round(vol)+' kg';if(p)p.textContent=document.querySelectorAll('.adv-pr').length}
function renderHistory(){var old=document.getElementById('advHistory');if(old)old.remove();var panel=document.getElementById('workout');if(!panel)return;var s=load(),i=dayIndex(),dates=Object.keys(s.workoutLog||{}).filter(function(d){return s.workoutLog[d]&&s.workoutLog[d][i]}).sort().reverse().slice(0,5),box=document.createElement('section');box.id='advHistory';box.className='card adv-history';box.innerHTML='<h4 style="margin:0 0 8px">Workout history</h4>'+(dates.length?dates.map(function(d){var l=s.workoutLog[d][i],sets=Object.values(l.advancedSets||{}).flat(),vol=sets.filter(function(x){return x.done}).reduce(function(a,x){return a+Number(x.weight||0)*Number(x.reps||0)},0);return '<div class="adv-history-row"><span>'+d+'</span><strong>'+Math.round(vol)+' kg</strong></div>'}).join(''):'<div class="adv-history-row"><span>No completed sessions yet</span></div>');document.getElementById('saveWorkout')?.insertAdjacentElement('afterend',box)}
function refresh(){sessionSummary();upgrade();updateSummary()}
addCss();restWidget();refresh();document.querySelector('[data-tab="workout"]')?.addEventListener('click',function(){setTimeout(refresh,40)});document.getElementById('dayPicker')?.addEventListener('click',function(){setTimeout(function(){document.querySelectorAll('#exerciseList .exercise').forEach(function(c){delete c.dataset.adv});refresh()},60)});document.getElementById('saveWorkout')?.addEventListener('click',function(){setTimeout(function(){renderHistory();updateSummary()},50)});
});