const KEY='decemberTracker.v1';
const DEFAULTS={config:{age:40,height:175,sex:'male',startWeight:89,goalWeight:80,goalDate:'2026-12-15',calories:2100,protein:170,steps:8000,water:3.5},weights:[],waist:[],nutrition:{},activity:{},workoutLog:{},theme:'dark',customFoods:[],workouts:[
{name:'Chest + Triceps',focus:'Upper chest • chest • triceps',exercises:[['Barbell bench press',4,8],['Incline dumbbell press',3,10],['Machine chest press',3,12],['Cable fly',3,15],['Rope pushdown',3,12],['Overhead cable extension',3,12]]},
{name:'Back + Biceps',focus:'Lats • mid back • biceps',exercises:[['Lat pulldown',4,10],['Chest-supported row',4,10],['Seated cable row',3,12],['Single-arm lat pulldown',3,12],['Face pull',3,15],['EZ-bar curl',3,10],['Hammer curl',3,12]]},
{name:'Legs + Core',focus:'Quads • hamstrings • glutes • abs',exercises:[['Hack squat / squat',4,8],['Romanian deadlift',3,10],['Leg press',3,12],['Leg curl',3,12],['Leg extension',3,15],['Calf raise',4,15],['Cable crunch',3,15]]},
{name:'Shoulders + Upper Chest',focus:'Delts • upper chest • rear delts',exercises:[['Incline bench press',4,8],['Seated dumbbell shoulder press',3,10],['Lateral raise',4,15],['Reverse pec deck',4,15],['Low-to-high cable fly',3,15],['Face pull',3,15]]},
{name:'Back + Arms',focus:'V-taper • biceps • triceps',exercises:[['Pull-up / pulldown',4,10],['T-bar row',3,10],['Straight-arm pulldown',3,15],['Rear-delt fly',3,15],['Incline dumbbell curl',3,12],['Rope pushdown',3,12],['Overhead triceps extension',2,15]]}
]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const today=()=>new Date().toLocaleDateString('en-CA');
const round=(n,d=0)=>Math.round(n*10**d)/10**d;
const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,n));
function load(){try{const old=JSON.parse(localStorage.getItem(KEY)||'null')||{};return {...structuredClone(DEFAULTS),...old,config:{...DEFAULTS.config,...old.config},workouts:old.workouts?.length?old.workouts:structuredClone(DEFAULTS.workouts),customFoods:old.customFoods||[],activity:old.activity||{},nutrition:old.nutrition||{},workoutLog:old.workoutLog||{},weights:old.weights||[],waist:old.waist||[]};}catch{return structuredClone(DEFAULTS)}}
let state=load(),selectedDay=Math.min(4,Math.max(0,new Date().getDay()-1));
function save(render=true){localStorage.setItem(KEY,JSON.stringify(state));if(render)renderAll()}
function latestWeight(){return Number(state.weights[0]?.weight)||Number(state.config.startWeight)}
function bmr(weight=latestWeight()){const c=state.config;return 10*weight+6.25*c.height-5*c.age+(c.sex==='male'?5:-161)}
function baseBurn(){return bmr()*1.2}
function stepCalories(steps=0,weight=latestWeight()){return Number(steps||0)*weight*0.0005}
function exerciseCalories(minutes=0,met=5.5,weight=latestWeight()){return Number(minutes||0)*Number(met||0)*3.5*weight/200}
function getActivity(k=today()){return state.activity[k]||{steps:0,water:0,minutes:0,met:5.5,workoutDay:null}}
function allFoods(){return [...(window.FOOD_DB||[]),...state.customFoods]}
function findFood(name){const q=String(name||'').trim().toLowerCase();return allFoods().find(f=>f.name.toLowerCase()===q)||allFoods().find(f=>f.name.toLowerCase().includes(q)||f.aliases?.some(a=>a.toLowerCase().includes(q)))}
function mealData(k=today()){const n=state.nutrition[k]||{};return n.meals||{breakfast:[],lunch:[],dinner:[]}}
function nutritionTotals(k=today()){let calories=0,protein=0,carbs=0,fat=0;Object.values(mealData(k)).forEach(items=>(items||[]).forEach(x=>{calories+=Number(x.calories)||0;protein+=Number(x.protein)||0;carbs+=Number(x.carbs)||0;fat+=Number(x.fat)||0}));return{calories:round(calories),protein:round(protein,1),carbs:round(carbs,1),fat:round(fat,1)}}
function burnTotals(k=today()){const a=getActivity(k),base=baseBurn(),steps=stepCalories(a.steps),exercise=exerciseCalories(a.minutes,a.met);return{base,steps,exercise,total:base+steps+exercise}}
function progressPct(){const c=state.config,start=Number(c.startWeight),goal=Number(c.goalWeight),now=latestWeight();return clamp((start-now)/(start-goal)*100)}
function fillBar(id,value,target){const el=$(id);if(el)el.style.width=`${clamp(Number(value||0)/Math.max(1,Number(target||1))*100)}%`}
function renderAll(){renderDashboard();renderWorkout();renderFood();renderProgress();renderSettings();document.body.classList.toggle('light',state.theme==='light');$('#themeBtn').textContent=state.theme==='light'?'☾':'◐'}
function renderDashboard(){const c=state.config,n=nutritionTotals(),a=getActivity(),burn=burnTotals(),balance=burn.total-n.calories;const days=Math.max(0,Math.ceil((new Date(c.goalDate+'T00:00:00')-new Date())/86400000));$('#daysLeft').textContent=days;$('#todayLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'short'});$('#dashIntake').textContent=n.calories;$('#dashBurn').textContent=Math.round(burn.total);$('#dashBalance').textContent=(balance>=0?'-':'+')+Math.abs(Math.round(balance));$('#dashBalanceLabel').textContent=balance>=0?'kcal estimated deficit':'kcal estimated surplus';$('#dashBalance').className=balance>=0?'good':'warn';$('#dashProtein').textContent=`${n.protein}g`;$('#dashProteinTarget').textContent=`of ${c.protein}g target`;$('#baseBurn').textContent=`${Math.round(burn.base)} kcal`;$('#stepBurn').textContent=`${Math.round(burn.steps)} kcal`;$('#exerciseBurn').textContent=`${Math.round(burn.exercise)} kcal`;$('#totalBurn').textContent=`${Math.round(burn.total)} kcal`;const budgetPct=clamp(n.calories/c.calories*100);$('#balanceRing').style.setProperty('--p',budgetPct);$('#balanceRingText').textContent=`${Math.round(budgetPct)}%`;$('#budgetHeadline').textContent=`${n.calories} / ${c.calories} kcal`;$('#stepsInput').value=a.steps||'';$('#waterInput').value=a.water||'';$('#scoreCalories').textContent=`${n.calories} / ${c.calories}`;$('#scoreProtein').textContent=`${n.protein} / ${c.protein}g`;$('#scoreSteps').textContent=`${a.steps||0} / ${c.steps}`;$('#scoreWater').textContent=`${a.water||0} / ${c.water}L`;fillBar('#scoreCaloriesBar',n.calories,c.calories);fillBar('#scoreProteinBar',n.protein,c.protein);fillBar('#scoreStepsBar',a.steps,c.steps);fillBar('#scoreWaterBar',a.water,c.water);$('#todayStatus').textContent=n.calories||a.steps?'In progress':'Start logging';const wk=weekSummary();$('#weekIntake').textContent=wk.avgIntake;$('#weekBalance').textContent=(wk.avgBalance>=0?'-':'+')+Math.abs(wk.avgBalance);$('#weekWorkouts').textContent=wk.workouts}
function weekSummary(){let intake=0,balance=0,days=0,workouts=0;for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-i);const k=d.toLocaleDateString('en-CA'),n=nutritionTotals(k),a=getActivity(k),b=burnTotals(k);if(n.calories||a.steps||a.minutes){intake+=n.calories;balance+=b.total-n.calories;days++}if(a.minutes>0)workouts++}return{avgIntake:days?Math.round(intake/days):0,avgBalance:days?Math.round(balance/days):0,workouts}}
function saveDaily(){const w=Number($('#weightInput').value),wa=Number($('#waistInput').value),steps=Number($('#stepsInput').value)||0,water=Number($('#waterInput').value)||0,k=today();if(w>=30&&w<=250){const e=state.weights.find(x=>x.date===k);e?e.weight=w:state.weights.unshift({date:k,weight:w})}if(wa>=40&&wa<=200){const e=state.waist.find(x=>x.date===k);e?e.value=wa:state.waist.unshift({date:k,value:wa})}state.weights.sort((a,b)=>b.date.localeCompare(a.date));state.waist.sort((a,b)=>b.date.localeCompare(a.date));state.activity[k]={...getActivity(k),steps,water};$('#weightInput').value='';$('#waistInput').value='';save()}
function renderWorkout(){const p=state.workouts[selectedDay],k=today(),log=state.workoutLog[k]?.[selectedDay]||{};$('#dayPicker').innerHTML=state.workouts.map((x,i)=>`<button class="day-btn ${i===selectedDay?'active':''}" data-day="${i}"><b>D${i+1}</b><span>${x.name}</span></button>`).join('');$$('.day-btn').forEach(b=>b.addEventListener('click',()=>{selectedDay=Number(b.dataset.day);renderWorkout()}));$('#sessionName').textContent=p.name;$('#sessionFocus').textContent=p.focus;$('#workoutMinutes').value=log.minutes??60;$('#workoutIntensity').value=String(log.met??5.5);$('#sessionMinutes').textContent=log.minutes??60;$('#sessionBurn').textContent=`${Math.round(exerciseCalories(log.minutes??60,log.met??5.5))} kcal`;$('#exerciseList').innerHTML=p.exercises.map((e,i)=>{const x=log.exercises?.[i]||{};return `<article class="card exercise"><div class="exercise-top"><div><span class="exercise-num">${i+1}</span><div><h4>${e[0]}</h4><p>${e[1]} sets × ${e[2]} reps target</p></div></div><span class="volume" id="vol-${i}">0 kg</span></div><div class="exercise-inputs"><label>Sets<input class="ex-set" data-i="${i}" type="number" value="${x.sets??e[1]}"></label><label>Reps<input class="ex-reps" data-i="${i}" type="number" value="${x.reps??e[2]}"></label><label>Weight kg<input class="ex-weight" data-i="${i}" type="number" step="0.5" value="${x.weight??''}" placeholder="kg"></label></div></article>`}).join('');updateVolumeLabels();['workoutMinutes','workoutIntensity'].forEach(id=>$('#'+id).addEventListener('input',()=>{const m=Number($('#workoutMinutes').value)||0,met=Number($('#workoutIntensity').value)||5.5;$('#sessionMinutes').textContent=m;$('#sessionBurn').textContent=`${Math.round(exerciseCalories(m,met))} kcal`}));$$('.ex-set,.ex-reps,.ex-weight').forEach(x=>x.addEventListener('input',updateVolumeLabels))}
function updateVolumeLabels(){$$('.ex-weight').forEach(x=>{const i=x.dataset.i,s=Number($(`.ex-set[data-i="${i}"]`)?.value)||0,r=Number($(`.ex-reps[data-i="${i}"]`)?.value)||0,w=Number(x.value)||0;$('#vol-'+i).textContent=`${Math.round(s*r*w)} kg volume`})}
function saveWorkout(){const k=today(),p=state.workouts[selectedDay],minutes=Number($('#workoutMinutes').value)||0,met=Number($('#workoutIntensity').value)||5.5,exercises=p.exercises.map((e,i)=>({sets:Number($(`.ex-set[data-i="${i}"]`).value)||0,reps:Number($(`.ex-reps[data-i="${i}"]`).value)||0,weight:Number($(`.ex-weight[data-i="${i}"]`).value)||0}));state.workoutLog[k]??={};state.workoutLog[k][selectedDay]={minutes,met,exercises};state.activity[k]={...getActivity(k),minutes,met,workoutDay:selectedDay};save()}
function openWorkoutEditor(){const p=state.workouts[selectedDay];$('#workoutEditor').classList.remove('hidden');$('#editSessionName').value=p.name;$('#editSessionFocus').value=p.focus;renderExerciseEditor()}
function renderExerciseEditor(){const p=state.workouts[selectedDay];$('#editExerciseList').innerHTML=p.exercises.map((e,i)=>`<div class="edit-row" data-i="${i}"><input class="edit-name" value="${escapeHtml(e[0])}" aria-label="Exercise name"><input class="edit-sets" type="number" value="${e[1]}" aria-label="Sets"><input class="edit-reps" type="number" value="${e[2]}" aria-label="Reps"><button class="remove-edit" type="button">×</button></div>`).join('');$$('.remove-edit').forEach(b=>b.addEventListener('click',()=>{state.workouts[selectedDay].exercises.splice(Number(b.parentElement.dataset.i),1);renderExerciseEditor()}))}
function saveWorkoutPlan(){const p=state.workouts[selectedDay];p.name=$('#editSessionName').value.trim()||p.name;p.focus=$('#editSessionFocus').value.trim()||p.focus;p.exercises=$$('.edit-row').map(r=>[r.querySelector('.edit-name').value.trim()||'Exercise',Number(r.querySelector('.edit-sets').value)||3,Number(r.querySelector('.edit-reps').value)||10]);$('#workoutEditor').classList.add('hidden');save()}
function renderFood(){const n=nutritionTotals(),c=state.config;$('#foodCalories').textContent=n.calories;$('#foodProtein').textContent=`${n.protein}g`;$('#foodCarbs').textContent=`${n.carbs}g`;$('#foodFat').textContent=`${n.fat}g`;$('#foodCalTarget').textContent=`target ${c.calories}`;$('#foodProteinTarget').textContent=`target ${c.protein}g`;$('#foodSuggestions').innerHTML=allFoods().map(f=>`<option value="${escapeHtml(f.name)}"></option>`).join('');const labels={breakfast:['🌅','Breakfast'],lunch:['☀️','Lunch'],dinner:['🌙','Dinner']};const meals=mealData();$('#mealSections').innerHTML=Object.keys(labels).map(m=>`<section class="card meal-card" data-meal="${m}"><div class="meal-head"><div><span>${labels[m][0]}</span><div><h3>${labels[m][1]}</h3><small id="${m}Total">0 kcal</small></div></div><button class="secondary add-food" data-meal="${m}">+ Add food</button></div><div class="meal-items">${(meals[m]||[]).map((x,i)=>foodRow(m,x,i)).join('')||'<p class="empty">Nothing logged yet.</p>'}</div></section>`).join('');Object.keys(labels).forEach(m=>updateMealTotal(m));$$('.add-food').forEach(b=>b.addEventListener('click',()=>addFoodRow(b.dataset.meal)));$$('.remove-food').forEach(b=>b.addEventListener('click',()=>removeFood(b.dataset.meal,Number(b.dataset.i))));$$('.food-name,.food-grams').forEach(x=>x.addEventListener('change',()=>syncFoodRow(x)));renderCustomFoodList()}
function foodRow(meal,x,i){return `<div class="food-row" data-meal="${meal}" data-i="${i}"><input class="food-name" list="foodSuggestions" value="${escapeHtml(x.name)}" placeholder="Choose food"><input class="food-grams" type="number" value="${x.grams||''}" placeholder="g"><span class="food-macro">${Math.round(x.calories||0)} kcal<br><small>${round(x.protein||0,1)}g P</small></span><button class="remove-food" data-meal="${meal}" data-i="${i}" type="button">×</button></div>`}
function addFoodRow(meal){state.nutrition[today()]??={meals:{breakfast:[],lunch:[],dinner:[]}};state.nutrition[today()].meals??={breakfast:[],lunch:[],dinner:[]};state.nutrition[today()].meals[meal]??=[];state.nutrition[today()].meals[meal].push({name:'',grams:'',calories:0,protein:0,carbs:0,fat:0});save()}
function removeFood(meal,i){state.nutrition[today()].meals[meal].splice(i,1);save()}
function syncFoodRow(input){const row=input.closest('.food-row'),meal=row.dataset.meal,i=Number(row.dataset.i),name=row.querySelector('.food-name').value,food=findFood(name),grams=Number(row.querySelector('.food-grams').value)||Number(food?.defaultGrams)||100;if(!food)return;const calc=k=>round((Number(food[k])||0)*grams/100,1);state.nutrition[today()]??={meals:{breakfast:[],lunch:[],dinner:[]}};state.nutrition[today()].meals??={breakfast:[],lunch:[],dinner:[]};state.nutrition[today()].meals[meal]??=[];state.nutrition[today()].meals[meal][i]={name:food.name,grams,calories:calc('calories'),protein:calc('protein'),carbs:calc('carbs'),fat:calc('fat')};save()}
function updateMealTotal(meal){const t=(mealData()[meal]||[]).reduce((a,x)=>a+(Number(x.calories)||0),0),el=$('#'+meal+'Total');if(el)el.textContent=`${Math.round(t)} kcal`}
function saveCustomFood(){const name=$('#customFoodName').value.trim();if(!name)return;const item={name,aliases:[],defaultGrams:Number($('#customFoodServing').value)||100,calories:Number($('#customFoodCalories').value)||0,protein:Number($('#customFoodProtein').value)||0,carbs:Number($('#customFoodCarbs').value)||0,fat:Number($('#customFoodFat').value)||0};const i=state.customFoods.findIndex(x=>x.name.toLowerCase()===name.toLowerCase());i>=0?state.customFoods[i]=item:state.customFoods.push(item);['customFoodName','customFoodCalories','customFoodProtein','customFoodCarbs','customFoodFat'].forEach(id=>$('#'+id).value='');save()}
function renderCustomFoodList(){$('#customFoodList').innerHTML=state.customFoods.length?state.customFoods.map((f,i)=>`<div class="list-row"><span><b>${escapeHtml(f.name)}</b><small>${f.calories} kcal • ${f.protein}g P /100g</small></span><button class="text-btn del-custom" data-i="${i}">Delete</button></div>`).join(''):'<div class="list-row"><span>No custom foods yet</span></div>';$$('.del-custom').forEach(b=>b.addEventListener('click',()=>{state.customFoods.splice(Number(b.dataset.i),1);save()}))}
function renderProgress(){const c=state.config,w=latestWeight(),start=Number(c.startWeight),goal=Number(c.goalWeight),latestW=state.waist[0]?.value,firstW=state.waist[state.waist.length-1]?.value;$('#currentWeight').textContent=`${w.toFixed(1)} kg`;$('#goalWeight').textContent=`${goal.toFixed(1)} kg`;$('#weightChange').textContent=`${round(w-start,1)>0?'+':''}${round(w-start,1)} kg from start`;$('#weightRemaining').textContent=`${Math.max(0,round(w-goal,1))} kg to go`;$('#latestWaist').textContent=latestW?`${Number(latestW).toFixed(1)} cm`:'—';$('#waistChange').textContent=latestW&&firstW?`${round(latestW-firstW,1)} cm from baseline`:'No baseline yet';$('#progressPct').textContent=`${Math.round(progressPct())}%`;renderProgressList();drawChart()}
function renderProgressList(){const dates=[...new Set([...state.weights.map(x=>x.date),...state.waist.map(x=>x.date)])].sort().reverse().slice(0,14);$('#progressList').innerHTML=dates.length?dates.map(k=>{const w=state.weights.find(x=>x.date===k)?.weight,wa=state.waist.find(x=>x.date===k)?.value;return `<div class="list-row"><span>${new Date(k+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short'})}</span><strong>${w?Number(w).toFixed(1)+' kg':'—'} • ${wa?Number(wa).toFixed(1)+' cm':'—'}</strong></div>`}).join(''):'<div class="list-row"><span>No measurements yet</span></div>'}
function drawChart(){const c=$('#weightChart');if(!c)return;const ctx=c.getContext('2d'),w=c.clientWidth||320,h=220,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const data=[...state.weights].sort((a,b)=>a.date.localeCompare(b.date));if(!data.length){ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');ctx.font='14px system-ui';ctx.fillText('Log weight to see your trend.',18,35);return}const vals=data.map(x=>Number(x.weight)),min=Math.min(...vals,state.config.goalWeight)-1,max=Math.max(...vals,state.config.startWeight)+1,px=i=>30+i*(w-50)/Math.max(1,data.length-1),py=v=>h-25-(v-min)/(max-min)*(h-50),accent=getComputedStyle(document.body).getPropertyValue('--accent');ctx.strokeStyle=accent;ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>i?ctx.lineTo(px(i),py(v)):ctx.moveTo(px(i),py(v)));ctx.stroke();ctx.fillStyle=accent;vals.forEach((v,i)=>{ctx.beginPath();ctx.arc(px(i),py(v),4,0,Math.PI*2);ctx.fill()})}
function renderSettings(){const c=state.config;[['setAge','age'],['setHeight','height'],['setStartWeight','startWeight'],['setGoalWeight','goalWeight'],['setGoalDate','goalDate'],['setCalories','calories'],['setProtein','protein'],['setSteps','steps'],['setWater','water'],['setSex','sex']].forEach(([id,k])=>$('#'+id).value=c[k]);$('#bmrExplanation').textContent=`Estimated BMR ${Math.round(bmr())} kcal/day. Base daily burn uses BMR × 1.2, then adds estimated step calories and logged workout calories.`}
function saveSettings(){const map={age:'setAge',height:'setHeight',startWeight:'setStartWeight',goalWeight:'setGoalWeight',goalDate:'setGoalDate',calories:'setCalories',protein:'setProtein',steps:'setSteps',water:'setWater',sex:'setSex'};Object.entries(map).forEach(([k,id])=>{state.config[k]=['goalDate','sex'].includes(k)?$('#'+id).value:Number($('#'+id).value)});save()}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$$('.tab').forEach(t=>t.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab).classList.add('active');if(t.dataset.tab==='progress')drawChart()}));
$('#themeBtn').addEventListener('click',()=>{state.theme=state.theme==='light'?'dark':'light';save()});$('#saveDaily').addEventListener('click',saveDaily);$('#saveWorkout').addEventListener('click',saveWorkout);$('#editWorkoutBtn').addEventListener('click',openWorkoutEditor);$('#closeWorkoutEditor').addEventListener('click',()=>$('#workoutEditor').classList.add('hidden'));$('#addExercise').addEventListener('click',()=>{state.workouts[selectedDay].exercises.push(['New exercise',3,10]);renderExerciseEditor()});$('#saveWorkoutPlan').addEventListener('click',saveWorkoutPlan);$('#manageFoodsBtn').addEventListener('click',()=>$('#foodManager').classList.remove('hidden'));$('#closeFoodManager').addEventListener('click',()=>$('#foodManager').classList.add('hidden'));$('#saveCustomFood').addEventListener('click',saveCustomFood);$('#saveSettings').addEventListener('click',saveSettings);window.addEventListener('resize',drawChart);if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});renderAll();