const KEY='decemberTracker.v1';
const DEFAULTS={config:{age:40,height:175,sex:'male',startWeight:89,goalWeight:80,goalDate:'2026-12-15',calories:2100,protein:170,steps:8000,water:3.5},weights:[],waist:[],abdomen:[],pantWaist:[],nutrition:{},activity:{},workoutLog:{},theme:'dark',customFoods:[],workouts:[
{name:'Chest + Triceps',focus:'Upper chest • chest • triceps',exercises:[['Barbell bench press',4,8],['Incline dumbbell press',3,10],['Machine chest press',3,12],['Cable fly',3,15],['Rope pushdown',3,12],['Overhead cable extension',3,12]]},
{name:'Back + Biceps',focus:'Lats • mid back • biceps',exercises:[['Lat pulldown',4,10],['Chest-supported row',4,10],['Seated cable row',3,12],['Single-arm lat pulldown',3,12],['Face pull',3,15],['EZ-bar curl',3,10],['Hammer curl',3,12]]},
{name:'Legs + Core',focus:'Quads • hamstrings • glutes • abs',exercises:[['Hack squat / squat',4,8],['Romanian deadlift',3,10],['Leg press',3,12],['Leg curl',3,12],['Leg extension',3,15],['Calf raise',4,15],['Cable crunch',3,15]]},
{name:'Shoulders + Upper Chest',focus:'Delts • upper chest • rear delts',exercises:[['Incline bench press',4,8],['Seated dumbbell shoulder press',3,10],['Lateral raise',4,15],['Reverse pec deck',4,15],['Low-to-high cable fly',3,15],['Face pull',3,15]]},
{name:'Back + Arms',focus:'V-taper • biceps • triceps',exercises:[['Pull-up / pulldown',4,10],['T-bar row',3,10],['Straight-arm pulldown',3,15],['Rear-delt fly',3,15],['Incline dumbbell curl',3,12],['Rope pushdown',3,12],['Overhead triceps extension',2,15]]}
]};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const clone=x=>JSON.parse(JSON.stringify(x));
const today=()=>{const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const round=(n,d=0)=>Math.round((Number(n)||0)*10**d)/10**d;
const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,Number(n)||0));
const arr=v=>Array.isArray(v)?v:[];
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
function normalizeWorkouts(v){let w=arr(v).filter(x=>x&&typeof x==='object').map((x,i)=>({name:String(x.name||`Workout ${i+1}`),focus:String(x.focus||'Training'),exercises:arr(x.exercises).map(e=>Array.isArray(e)?[String(e[0]||'Exercise'),Number(e[1])||3,Number(e[2])||10]:[String(e?.name||'Exercise'),Number(e?.sets)||3,Number(e?.reps)||10])}));if(!w.length)w=clone(DEFAULTS.workouts);while(w.length<5)w.push(clone(DEFAULTS.workouts[w.length%DEFAULTS.workouts.length]));return w;}
function load(){let old={};try{old=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(e){old={}}const s={...clone(DEFAULTS),...obj(old)};s.config={...DEFAULTS.config,...obj(old.config)};s.weights=arr(old.weights);s.waist=arr(old.waist);s.abdomen=arr(old.abdomen);s.pantWaist=arr(old.pantWaist);s.customFoods=arr(old.customFoods);s.nutrition=obj(old.nutrition);s.activity=obj(old.activity);s.workoutLog=obj(old.workoutLog);s.workouts=normalizeWorkouts(old.workouts);s.theme=old.theme==='light'?'light':'dark';return s;}
let state=load(), selectedDay=Math.min(4,Math.max(0,new Date().getDay()-1));
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function save(render=true){persist();if(render)renderAll()}
function latestWeight(){return Number(arr(state.weights)[0]?.weight)||Number(state.config.startWeight)||89}
function bmr(weight=latestWeight()){const c=state.config;return 10*weight+6.25*(Number(c.height)||175)-5*(Number(c.age)||40)+(c.sex==='female'?-161:5)}
function baseBurn(){return bmr()*1.2}
function stepCalories(steps=0,weight=latestWeight()){return (Number(steps)||0)*weight*0.0005}
function exerciseCalories(minutes=0,met=5.5,weight=latestWeight()){return (Number(minutes)||0)*(Number(met)||5.5)*3.5*weight/200}
function getActivity(k=today()){return {...{steps:0,water:0,minutes:0,met:5.5,workoutDay:null},...obj(state.activity[k])}}
function allFoods(){return [...arr(window.FOOD_DB),...arr(state.customFoods)]}
function findFood(name){const q=String(name||'').trim().toLowerCase();if(!q)return null;return allFoods().find(f=>String(f.name||'').toLowerCase()===q)||allFoods().find(f=>String(f.name||'').toLowerCase().includes(q)||arr(f.aliases).some(a=>String(a).toLowerCase().includes(q)))}
function mealData(k=today()){const meals=obj(obj(state.nutrition[k]).meals);return {breakfast:arr(meals.breakfast),lunch:arr(meals.lunch),eveningSnacks:arr(meals.eveningSnacks),dinner:arr(meals.dinner)}}
function nutritionTotals(k=today()){let calories=0,protein=0,carbs=0,fat=0;Object.values(mealData(k)).forEach(items=>items.forEach(x=>{calories+=Number(x?.calories)||0;protein+=Number(x?.protein)||0;carbs+=Number(x?.carbs)||0;fat+=Number(x?.fat)||0}));return{calories:round(calories),protein:round(protein,1),carbs:round(carbs,1),fat:round(fat,1)}}
function burnTotals(k=today()){const a=getActivity(k),base=baseBurn(),steps=stepCalories(a.steps),exercise=exerciseCalories(a.minutes,a.met);return{base,steps,exercise,total:base+steps+exercise}}
function progressPct(){const c=state.config,start=Number(c.startWeight)||89,goal=Number(c.goalWeight)||80,now=latestWeight(),den=start-goal;return den?clamp((start-now)/den*100):0}
function setText(sel,val){const e=$(sel);if(e)e.textContent=val}
function setVal(sel,val){const e=$(sel);if(e)e.value=val}
function fillBar(sel,value,target){const e=$(sel);if(e)e.style.width=`${clamp((Number(value)||0)/Math.max(1,Number(target)||1)*100)}%`}
function renderAll(){try{renderDashboard()}catch(e){console.warn('dashboard',e)}try{renderWorkout()}catch(e){console.warn('workout',e)}try{renderFood()}catch(e){console.warn('food',e)}try{renderProgress()}catch(e){console.warn('progress',e)}try{renderSettings()}catch(e){console.warn('settings',e)}document.body.classList.toggle('light',state.theme==='light');setText('#themeBtn',state.theme==='light'?'☾':'◐')}
function renderDashboard(){const c=state.config,n=nutritionTotals(),a=getActivity(),burn=burnTotals(),balance=burn.total-n.calories;setText('#todayLabel',new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'short'}));setText('#dashIntake',n.calories);setText('#dashBurn',Math.round(burn.total));setText('#dashBalance',(balance>=0?'-':'+')+Math.abs(Math.round(balance)));setText('#dashBalanceLabel',balance>=0?'kcal estimated deficit':'kcal estimated surplus');const db=$('#dashBalance');if(db)db.className=balance>=0?'good':'warn';setText('#dashProtein',`${n.protein}g`);setText('#dashProteinTarget',`of ${c.protein}g target`);setText('#baseBurn',`${Math.round(burn.base)} kcal`);setText('#stepBurn',`${Math.round(burn.steps)} kcal`);setText('#exerciseBurn',`${Math.round(burn.exercise)} kcal`);setText('#totalBurn',`${Math.round(burn.total)} kcal`);const pct=clamp(n.calories/Math.max(1,Number(c.calories)||1)*100),ring=$('#balanceRing');if(ring)ring.style.setProperty('--p',pct);setText('#balanceRingText',`${Math.round(pct)}%`);setText('#budgetHeadline',`${n.calories} / ${c.calories} kcal`);setVal('#stepsInput',a.steps||'');setVal('#waterInput',a.water||'');setText('#scoreCalories',`${n.calories} / ${c.calories}`);setText('#scoreProtein',`${n.protein} / ${c.protein}g`);setText('#scoreSteps',`${a.steps||0} / ${c.steps}`);setText('#scoreWater',`${a.water||0} / ${c.water}L`);fillBar('#scoreCaloriesBar',n.calories,c.calories);fillBar('#scoreProteinBar',n.protein,c.protein);fillBar('#scoreStepsBar',a.steps,c.steps);fillBar('#scoreWaterBar',a.water,c.water);setText('#todayStatus',n.calories||a.steps?'In progress':'Start logging');const wk=weekSummary();setText('#weekIntake',wk.avgIntake);setText('#weekBalance',(wk.avgBalance>=0?'-':'+')+Math.abs(wk.avgBalance));setText('#weekWorkouts',wk.workouts)}
function weekSummary(){let intake=0,balance=0,days=0,workouts=0;for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-i);const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,n=nutritionTotals(k),a=getActivity(k),b=burnTotals(k);if(n.calories||a.steps||a.minutes){intake+=n.calories;balance+=b.total-n.calories;days++}if(a.minutes>0)workouts++}return{avgIntake:days?Math.round(intake/days):0,avgBalance:days?Math.round(balance/days):0,workouts}}
function saveDaily(){const w=Number($('#weightInput')?.value),wa=Number($('#waistInput')?.value),steps=Number($('#stepsInput')?.value)||0,water=Number($('#waterInput')?.value)||0,k=today();if(w>=30&&w<=250){const i=state.weights.findIndex(x=>x.date===k);i>=0?state.weights[i].weight=w:state.weights.unshift({date:k,weight:w})}if(wa>=40&&wa<=200){const i=state.waist.findIndex(x=>x.date===k);i>=0?state.waist[i].value=wa:state.waist.unshift({date:k,value:wa})}state.weights.sort((a,b)=>String(b.date).localeCompare(String(a.date)));state.waist.sort((a,b)=>String(b.date).localeCompare(String(a.date)));state.activity[k]={...getActivity(k),steps,water};setVal('#weightInput','');setVal('#waistInput','');save()}
function renderWorkout(){const p=state.workouts[selectedDay]||state.workouts[0],k=today(),log=obj(obj(state.workoutLog[k])[selectedDay]);const picker=$('#dayPicker');if(picker){picker.innerHTML=state.workouts.slice(0,5).map((x,i)=>`<button class="day-btn ${i===selectedDay?'active':''}" data-day="${i}"><b>D${i+1}</b><span>${escapeHtml(x.name)}</span></button>`).join('');$$('.day-btn').forEach(b=>b.onclick=()=>{selectedDay=Number(b.dataset.day)||0;renderWorkout()})}setText('#sessionName',p.name);setText('#sessionFocus',p.focus);setVal('#workoutMinutes',log.minutes??60);setVal('#workoutIntensity',String(log.met??5.5));setText('#sessionMinutes',log.minutes??60);setText('#sessionBurn',`${Math.round(exerciseCalories(log.minutes??60,log.met??5.5))} kcal`);const list=$('#exerciseList');if(list){list.innerHTML=arr(p.exercises).map((e,i)=>{const x=arr(log.exercises)[i]||{};return `<article class="card exercise"><div class="exercise-top"><div><span class="exercise-num">${i+1}</span><div><h4>${escapeHtml(e[0])}</h4><p>${e[1]} sets × ${e[2]} reps target</p></div></div><span class="volume" id="vol-${i}">0 kg</span></div><div class="exercise-inputs"><label>Sets<input class="ex-set" data-i="${i}" type="number" value="${Number(x.sets??e[1])}"></label><label>Reps<input class="ex-reps" data-i="${i}" type="number" value="${Number(x.reps??e[2])}"></label><label>Weight kg<input class="ex-weight" data-i="${i}" type="number" step="0.5" value="${Number(x.weight)||''}" placeholder="kg"></label></div></article>`}).join('');$$('.ex-set,.ex-reps,.ex-weight').forEach(x=>x.oninput=updateVolumeLabels);updateVolumeLabels()}const m=$('#workoutMinutes'),met=$('#workoutIntensity');const upd=()=>{setText('#sessionMinutes',Number(m?.value)||0);setText('#sessionBurn',`${Math.round(exerciseCalories(Number(m?.value)||0,Number(met?.value)||5.5))} kcal`)};if(m)m.oninput=upd;if(met)met.oninput=upd}
function updateVolumeLabels(){$$('.ex-weight').forEach(x=>{const i=x.dataset.i,s=Number($(`.ex-set[data-i="${i}"]`)?.value)||0,r=Number($(`.ex-reps[data-i="${i}"]`)?.value)||0,w=Number(x.value)||0;setText(`#vol-${i}`,`${Math.round(s*r*w)} kg volume`)})}
function saveWorkout(){const k=today(),p=state.workouts[selectedDay]||state.workouts[0],minutes=Number($('#workoutMinutes')?.value)||0,met=Number($('#workoutIntensity')?.value)||5.5,exercises=arr(p.exercises).map((e,i)=>({sets:Number($(`.ex-set[data-i="${i}"]`)?.value)||0,reps:Number($(`.ex-reps[data-i="${i}"]`)?.value)||0,weight:Number($(`.ex-weight[data-i="${i}"]`)?.value)||0}));state.workoutLog[k]=obj(state.workoutLog[k]);state.workoutLog[k][selectedDay]={minutes,met,exercises};state.activity[k]={...getActivity(k),minutes,met,workoutDay:selectedDay};save()}
function openWorkoutEditor(){const p=state.workouts[selectedDay]||state.workouts[0],box=$('#workoutEditor');if(box)box.classList.remove('hidden');setVal('#editSessionName',p.name);setVal('#editSessionFocus',p.focus);renderExerciseEditor()}
function renderExerciseEditor(){const p=state.workouts[selectedDay]||state.workouts[0],box=$('#editExerciseList');if(!box)return;box.innerHTML=arr(p.exercises).map((e,i)=>`<div class="edit-row" data-i="${i}"><input class="edit-name" value="${escapeHtml(e[0])}"><input class="edit-sets" type="number" value="${e[1]}"><input class="edit-reps" type="number" value="${e[2]}"><button class="remove-edit" type="button">×</button></div>`).join('');$$('.remove-edit').forEach(b=>b.onclick=()=>{p.exercises.splice(Number(b.parentElement.dataset.i),1);renderExerciseEditor()})}
function saveWorkoutPlan(){const p=state.workouts[selectedDay]||state.workouts[0];p.name=$('#editSessionName')?.value.trim()||p.name;p.focus=$('#editSessionFocus')?.value.trim()||p.focus;p.exercises=$$('.edit-row').map(r=>[r.querySelector('.edit-name')?.value.trim()||'Exercise',Number(r.querySelector('.edit-sets')?.value)||3,Number(r.querySelector('.edit-reps')?.value)||10]);$('#workoutEditor')?.classList.add('hidden');save()}
function renderFood(){const n=nutritionTotals(),c=state.config;setText('#foodCalories',n.calories);setText('#foodProtein',`${n.protein}g`);setText('#foodCarbs',`${n.carbs}g`);setText('#foodFat',`${n.fat}g`);setText('#foodCalTarget',`target ${c.calories}`);setText('#foodProteinTarget',`target ${c.protein}g`);const dl=$('#foodSuggestions');if(dl)dl.innerHTML=allFoods().map(f=>`<option value="${escapeHtml(f.name)}"></option>`).join('');const labels={breakfast:['🌅','Breakfast'],lunch:['☀️','Lunch'],eveningSnacks:['🍎','Evening Snacks'],dinner:['🌙','Dinner']},meals=mealData(),box=$('#mealSections');if(box)box.innerHTML=Object.keys(labels).map(m=>`<section class="card meal-card" data-meal="${m}"><div class="meal-head"><div><span>${labels[m][0]}</span><div><h3>${labels[m][1]}</h3><small id="${m}Total">0 kcal</small></div></div><button class="secondary add-food" data-meal="${m}">+ Add food</button></div><div class="meal-items">${meals[m].map((x,i)=>foodRow(m,x,i)).join('')||'<p class="empty">Nothing logged yet.</p>'}</div></section>`).join('');Object.keys(labels).forEach(updateMealTotal);$$('.add-food').forEach(b=>b.onclick=()=>addFoodRow(b.dataset.meal));$$('.remove-food').forEach(b=>b.onclick=()=>removeFood(b.dataset.meal,Number(b.dataset.i)));$$('.food-name,.food-grams').forEach(x=>x.onchange=()=>syncFoodRow(x));renderCustomFoodList()}
function foodRow(meal,x,i){return `<div class="food-row" data-meal="${meal}" data-i="${i}"><input class="food-name" list="foodSuggestions" value="${escapeHtml(x?.name||'')}" placeholder="Choose food"><input class="food-grams" type="number" value="${Number(x?.grams)||''}" placeholder="g"><span class="food-macro">${Math.round(Number(x?.calories)||0)} kcal<br><small>${round(x?.protein||0,1)}g P</small></span><button class="remove-food" data-meal="${meal}" data-i="${i}" type="button">×</button></div>`}
function ensureMeals(){const k=today();state.nutrition[k]=obj(state.nutrition[k]);state.nutrition[k].meals=obj(state.nutrition[k].meals);['breakfast','lunch','eveningSnacks','dinner'].forEach(m=>state.nutrition[k].meals[m]=arr(state.nutrition[k].meals[m]));return state.nutrition[k].meals}
function addFoodRow(meal){const meals=ensureMeals();meals[meal]=arr(meals[meal]);meals[meal].push({name:'',grams:'',calories:0,protein:0,carbs:0,fat:0});save()}
function removeFood(meal,i){const meals=ensureMeals();meals[meal].splice(i,1);save()}
function syncFoodRow(input){const row=input.closest('.food-row');if(!row)return;const meal=row.dataset.meal,i=Number(row.dataset.i),food=findFood(row.querySelector('.food-name')?.value),grams=Number(row.querySelector('.food-grams')?.value)||Number(food?.defaultGrams)||100;if(!food)return;const calc=k=>round((Number(food[k])||0)*grams/100,1),meals=ensureMeals();meals[meal][i]={name:food.name,grams,calories:calc('calories'),protein:calc('protein'),carbs:calc('carbs'),fat:calc('fat')};save()}
function updateMealTotal(meal){const total=arr(mealData()[meal]).reduce((a,x)=>a+(Number(x?.calories)||0),0);setText(`#${meal}Total`,`${Math.round(total)} kcal`)}
function saveCustomFood(){const name=$('#customFoodName')?.value.trim();if(!name)return;const item={name,aliases:[],defaultGrams:Number($('#customFoodServing')?.value)||100,calories:Number($('#customFoodCalories')?.value)||0,protein:Number($('#customFoodProtein')?.value)||0,carbs:Number($('#customFoodCarbs')?.value)||0,fat:Number($('#customFoodFat')?.value)||0},i=state.customFoods.findIndex(x=>String(x.name).toLowerCase()===name.toLowerCase());i>=0?state.customFoods[i]=item:state.customFoods.push(item);['#customFoodName','#customFoodCalories','#customFoodProtein','#customFoodCarbs','#customFoodFat'].forEach(s=>setVal(s,''));save()}
function renderCustomFoodList(){const box=$('#customFoodList');if(!box)return;box.innerHTML=state.customFoods.length?state.customFoods.map((f,i)=>`<div class="list-row"><span><b>${escapeHtml(f.name)}</b><small>${f.calories} kcal • ${f.protein}g P /100g</small></span><button class="text-btn del-custom" data-i="${i}">Delete</button></div>`).join(''):'<div class="list-row"><span>No custom foods yet</span></div>';$$('.del-custom').forEach(b=>b.onclick=()=>{state.customFoods.splice(Number(b.dataset.i),1);save()})}
function renderProgress(){const c=state.config,w=latestWeight(),start=Number(c.startWeight)||89,goal=Number(c.goalWeight)||80,latestW=state.waist[0]?.value,firstW=state.waist[state.waist.length-1]?.value;setText('#currentWeight',`${w.toFixed(1)} kg`);setText('#goalWeight',`${goal.toFixed(1)} kg`);setText('#weightChange',`${round(w-start,1)>0?'+':''}${round(w-start,1)} kg from start`);setText('#weightRemaining',`${Math.max(0,round(w-goal,1))} kg to go`);setText('#latestWaist',latestW?`${Number(latestW).toFixed(1)} cm`:'—');setText('#waistChange',latestW&&firstW?`${round(latestW-firstW,1)} cm from baseline`:'No baseline yet');setText('#progressPct',`${Math.round(progressPct())}%`);renderProgressList();drawChart()}
function renderProgressList(){const dates=[...new Set([...state.weights.map(x=>x.date),...state.waist.map(x=>x.date)])].filter(Boolean).sort().reverse().slice(0,14),box=$('#progressList');if(!box)return;box.innerHTML=dates.length?dates.map(k=>{const w=state.weights.find(x=>x.date===k)?.weight,wa=state.waist.find(x=>x.date===k)?.value;return `<div class="list-row"><span>${escapeHtml(k)}</span><strong>${w?Number(w).toFixed(1)+' kg':'—'} • ${wa?Number(wa).toFixed(1)+' cm':'—'}</strong></div>`}).join(''):'<div class="list-row"><span>No measurements yet</span></div>'}
function drawChart(){const c=$('#weightChart');if(!c||!c.getContext)return;const ctx=c.getContext('2d'),w=c.clientWidth||320,h=220,dpr=window.devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const data=state.weights.filter(x=>Number(x.weight)).slice().sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(!data.length){ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');ctx.font='14px system-ui';ctx.fillText('Log weight to see your trend.',18,35);return}const vals=data.map(x=>Number(x.weight)),min=Math.min(...vals,Number(state.config.goalWeight)||80)-1,max=Math.max(...vals,Number(state.config.startWeight)||89)+1,px=i=>30+i*(w-50)/Math.max(1,data.length-1),py=v=>h-25-(v-min)/Math.max(1,max-min)*(h-50),accent=getComputedStyle(document.body).getPropertyValue('--accent');ctx.strokeStyle=accent;ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>i?ctx.lineTo(px(i),py(v)):ctx.moveTo(px(i),py(v)));ctx.stroke();ctx.fillStyle=accent;vals.forEach((v,i)=>{ctx.beginPath();ctx.arc(px(i),py(v),4,0,Math.PI*2);ctx.fill()})}
function renderSettings(){const c=state.config;[['#setAge','age'],['#setHeight','height'],['#setStartWeight','startWeight'],['#setGoalWeight','goalWeight'],['#setGoalDate','goalDate'],['#setCalories','calories'],['#setProtein','protein'],['#setSteps','steps'],['#setWater','water'],['#setSex','sex']].forEach(([id,k])=>setVal(id,c[k]));setText('#bmrExplanation',`Estimated BMR ${Math.round(bmr())} kcal/day. Base daily burn uses BMR × 1.2, then adds estimated step calories and logged workout calories.`)}
function saveSettings(){const map={age:'#setAge',height:'#setHeight',startWeight:'#setStartWeight',goalWeight:'#setGoalWeight',goalDate:'#setGoalDate',calories:'#setCalories',protein:'#setProtein',steps:'#setSteps',water:'#setWater',sex:'#setSex'};Object.entries(map).forEach(([k,id])=>{const e=$(id);if(e)state.config[k]=['goalDate','sex'].includes(k)?e.value:Number(e.value)});save()}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function wire(){$$('.tab[data-tab]').forEach(t=>{t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');const p=$('#'+t.dataset.tab);if(p)p.classList.add('active');if(t.dataset.tab==='progress')setTimeout(drawChart,20);window.scrollTo(0,0)}});const on=(s,fn)=>{const e=$(s);if(e)e.onclick=fn};on('#themeBtn',()=>{state.theme=state.theme==='light'?'dark':'light';save()});on('#saveDaily',saveDaily);on('#saveWorkout',saveWorkout);on('#editWorkoutBtn',openWorkoutEditor);on('#closeWorkoutEditor',()=>$('#workoutEditor')?.classList.add('hidden'));on('#addExercise',()=>{const p=state.workouts[selectedDay]||state.workouts[0];p.exercises.push(['New exercise',3,10]);renderExerciseEditor()});on('#saveWorkoutPlan',saveWorkoutPlan);on('#manageFoodsBtn',()=>$('#foodManager')?.classList.remove('hidden'));on('#closeFoodManager',()=>$('#foodManager')?.classList.add('hidden'));on('#saveCustomFood',saveCustomFood);on('#saveSettings',saveSettings);window.onresize=drawChart}
wire();renderAll();persist();
