document.addEventListener('DOMContentLoaded',function(){
'use strict';
var KEY='decemberTracker.v1';
function q(s,r){return (r||document).querySelector(s)}function qa(s,r){return Array.from((r||document).querySelectorAll(s))}
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function dayIndex(){var b=q('.day-btn.active');return b?Number(b.dataset.day||0):0}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function show(el,on){if(el)el.classList.toggle('hidden',!on)}

/* WORKOUT PLAN EDITOR */
var editBtn=q('#editWorkoutBtn'),editor=q('#workoutEditor'),closeEdit=q('#closeWorkoutEditor'),list=q('#editExerciseList'),addBtn=q('#addExercise'),saveBtn=q('#saveWorkoutPlan');
function exerciseRow(e,i){return '<div class="card" style="padding:12px;margin-top:8px" data-edit-row="'+i+'"><div class="form-grid two"><label>Exercise<input class="ep-name" value="'+esc(e[0])+'"></label><label>Target weight<input class="ep-weight" value="'+esc(e[3]??'')+'" placeholder="e.g. 20, bodyweight, none"></label><label>Sets<input class="ep-sets" type="number" min="1" value="'+Number(e[1]||3)+'"></label><label>Target reps<input class="ep-reps" type="number" min="1" value="'+Number(e[2]||10)+'"></label></div><button type="button" class="secondary ep-remove" style="margin-top:8px">Remove exercise</button></div>'}
function openEditor(){var s=load(),i=dayIndex(),p=s.workouts&&s.workouts[i];if(!p)return;show(editor,true);q('#editSessionName').value=p.name||'';q('#editSessionFocus').value=p.focus||'';list.innerHTML=(p.exercises||[]).map(exerciseRow).join('');bindRows();editor.scrollIntoView({behavior:'smooth',block:'start'})}
function bindRows(){qa('.ep-remove',list).forEach(function(b){b.onclick=function(){b.closest('[data-edit-row]').remove()}})}
if(editBtn)editBtn.onclick=openEditor;if(closeEdit)closeEdit.onclick=function(){show(editor,false)};
if(addBtn)addBtn.onclick=function(){var d=document.createElement('div');d.innerHTML=exerciseRow(['New exercise',3,10,''],Date.now());list.appendChild(d.firstElementChild);bindRows()};
if(saveBtn)saveBtn.onclick=function(){var s=load(),i=dayIndex();s.workouts=s.workouts||[];var old=s.workouts[i]||{name:'Workout',focus:'',exercises:[]};var ex=qa('[data-edit-row]',list).map(function(row){var w=row.querySelector('.ep-weight').value.trim();var parsed=w===''?'':(!isNaN(Number(w))?Number(w):w.toLowerCase());return[row.querySelector('.ep-name').value.trim()||'Exercise',Number(row.querySelector('.ep-sets').value||3),Number(row.querySelector('.ep-reps').value||10),parsed]}).filter(function(x){return x[0]});s.workouts[i]={name:q('#editSessionName').value.trim()||old.name,focus:q('#editSessionFocus').value.trim(),exercises:ex};save(s);show(editor,false);location.reload()};

/* FOOD DATABASE MANAGER */
var manage=q('#manageFoodsBtn'),fm=q('#foodManager'),closeFood=q('#closeFoodManager'),saveFood=q('#saveCustomFood'),customList=q('#customFoodList');var editing=-1;
function clearFoodForm(){editing=-1;['#customFoodName','#customFoodCalories','#customFoodProtein','#customFoodCarbs','#customFoodFat'].forEach(function(id){q(id).value=''});q('#customFoodServing').value=100;if(saveFood)saveFood.textContent='Save food'}
function renderCustom(){var s=load(),arr=Array.isArray(s.customFoods)?s.customFoods:[];var built=window.FOOD_DB||[];customList.innerHTML='<div style="margin-top:16px"><b>My custom foods</b></div>'+(arr.length?arr.map(function(f,i){return '<div class="card" style="padding:11px;margin-top:8px;display:flex;justify-content:space-between;gap:10px;align-items:center"><div><b>'+esc(f.name)+'</b><small style="display:block;color:var(--muted)">'+Number(f.calories||0)+' kcal • '+Number(f.protein||0)+'g protein /100g</small></div><div><button class="secondary cf-edit" data-i="'+i+'">Edit</button> <button class="secondary cf-del" data-i="'+i+'">Delete</button></div></div>'}).join(''):'<p class="muted-copy">No custom foods yet.</p>')+'<div style="margin-top:18px"><b>Built-in foods ('+built.length+')</b><p class="muted-copy">Built-in foods are available for meal search. Add a custom food above if you need different nutrition values.</p></div>';
qa('.cf-edit',customList).forEach(function(b){b.onclick=function(){var f=arr[Number(b.dataset.i)];editing=Number(b.dataset.i);q('#customFoodName').value=f.name||'';q('#customFoodServing').value=f.defaultGrams||100;q('#customFoodCalories').value=f.calories||0;q('#customFoodProtein').value=f.protein||0;q('#customFoodCarbs').value=f.carbs||0;q('#customFoodFat').value=f.fat||0;saveFood.textContent='Update food';fm.scrollIntoView({behavior:'smooth'})}});qa('.cf-del',customList).forEach(function(b){b.onclick=function(){var s2=load();s2.customFoods=Array.isArray(s2.customFoods)?s2.customFoods:[];s2.customFoods.splice(Number(b.dataset.i),1);save(s2);renderCustom()}})}
if(manage)manage.onclick=function(){show(fm,true);renderCustom();fm.scrollIntoView({behavior:'smooth',block:'start'})};if(closeFood)closeFood.onclick=function(){show(fm,false);clearFoodForm()};
if(saveFood)saveFood.onclick=function(){var name=q('#customFoodName').value.trim();if(!name){q('#customFoodName').focus();return}var s=load();s.customFoods=Array.isArray(s.customFoods)?s.customFoods:[];var f={name:name,aliases:[],defaultGrams:Number(q('#customFoodServing').value||100),calories:Number(q('#customFoodCalories').value||0),protein:Number(q('#customFoodProtein').value||0),carbs:Number(q('#customFoodCarbs').value||0),fat:Number(q('#customFoodFat').value||0)};if(editing>=0&&s.customFoods[editing])s.customFoods[editing]=f;else s.customFoods.push(f);save(s);clearFoodForm();renderCustom()};
});