(function(){
'use strict';
const Store=window.MyBodyStore;if(!Store)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const clone=Store.clone,foods=Array.isArray(window.FOOD_DB)?window.FOOD_DB:[];
const mealKeys=['breakfast','lunch','eveningSnacks','dinner'];
const labels={breakfast:'Breakfast',lunch:'Lunch',eveningSnacks:'Snacks',dinner:'Dinner'};
let state=Store.read(),wired=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,f=0)=>{const x=Number(v);return Number.isFinite(x)?x:f};
function currentMeal(){const h=new Date().getHours();return h<11?'breakfast':h<16?'lunch':h<19?'eveningSnacks':'dinner'}
function toast(m){const el=$('#appToast');if(!el)return;el.textContent=m;el.dataset.type='success';el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function write(next,msg){const r=Store.write(next);state=r.state;if(msg)toast(msg);setTimeout(render,80);return r.ok}
function ensureMeals(next,date=Store.localDate()){next.nutrition=next.nutrition||{};next.nutrition[date]=next.nutrition[date]||{};next.nutrition[date].meals=next.nutrition[date].meals||{};mealKeys.forEach(k=>{if(!Array.isArray(next.nutrition[date].meals[k]))next.nutrition[date].meals[k]=[]});return next.nutrition[date].meals}
function prefs(){return state.profile?.experience?.food||{favorites:[],portions:{}}}
function savePrefs(mutator){const next=clone(Store.read());next.profile=next.profile||{};next.profile.experience=next.profile.experience||{};next.profile.experience.food=next.profile.experience.food||{favorites:[],portions:{}};mutator(next.profile.experience.food);write(next)}
function latestFoodByName(name){const target=String(name||'').trim().toLowerCase();for(const d of Object.keys(state.nutrition||{}).sort().reverse()){for(const k of mealKeys){const arr=state.nutrition?.[d]?.meals?.[k]||[];for(let i=arr.length-1;i>=0;i--){if(String(arr[i]?.name||'').trim().toLowerCase()===target)return clone(arr[i])}}}return null}
function favoriteItems(){const p=prefs();return (p.favorites||[]).map(name=>latestFoodByName(name)||foodFromDb(name)).filter(Boolean).slice(0,12)}
function foodFromDb(name){const q=String(name||'').toLowerCase();const f=foods.find(x=>String(x.name).toLowerCase()===q||(x.aliases||[]).some(a=>String(a).toLowerCase()===q));if(!f)return null;return fromPer100(f,f.defaultGrams||100)}
function fromPer100(food,grams){const ratio=grams/100;return{name:food.name,amount:grams,grams,unit:'g',calories:n(food.calories)*ratio,protein:n(food.protein)*ratio,carbs:n(food.carbs)*ratio,fat:n(food.fat)*ratio,savedAt:new Date().toISOString()}}
function addFood(item,meal=currentMeal()){const next=clone(Store.read()),meals=ensureMeals(next);meals[meal].push({...clone(item),savedAt:new Date().toISOString()});write(next,`${item.name} added to ${labels[meal]}`)}
function repeatMeal(key){const dates=Object.keys(state.nutrition||{}).filter(d=>d<Store.localDate()).sort().reverse();for(const d of dates){const arr=state.nutrition?.[d]?.meals?.[key];if(arr?.length){const next=clone(Store.read()),meals=ensureMeals(next);meals[key].push(...arr.map(clone));write(next,`${labels[key]} repeated`);return}}toast(`No previous ${labels[key].toLowerCase()} found`)}
function modal(title,html){let m=$('#experienceFoodModal');if(!m){m=document.createElement('div');m.id='experienceFoodModal';m.className='xp-modal hidden';document.body.appendChild(m)}m.innerHTML=`<div class="xp-modal-panel food-fast-modal"><header><div><h2>${esc(title)}</h2></div><button type="button" class="xp-close">×</button></header><div class="food-fast-body">${html}</div></div>`;m.classList.remove('hidden');document.body.classList.add('modal-open');$('.xp-close',m).onclick=()=>closeModal(m);m.onclick=e=>{if(e.target===m)closeModal(m)};return m}
function closeModal(m=$('#experienceFoodModal')){m?.classList.add('hidden');if(!document.querySelector('.xp-modal:not(.hidden),.p5-modal:not(.hidden),.p4-modal:not(.hidden),.p3-modal:not(.hidden),.coach-modal:not(.hidden),.sheet-backdrop:not(.hidden)'))document.body.classList.remove('modal-open')}
function openFavorites(){state=Store.read();const items=favoriteItems(),m=modal('Favorite foods',items.length?`<div class="food-fast-list">${items.map((f,i)=>`<button type="button" data-fast-fav="${i}"><strong>${esc(f.name)}</strong><span>${Math.round(n(f.calories))} kcal · ${Math.round(n(f.protein))}g protein</span></button>`).join('')}</div>`:'<p class="empty">Save foods normally, then tap the star beside a logged item to build favorites.</p>');$$('[data-fast-fav]',m).forEach(b=>b.onclick=()=>{addFood(items[n(b.dataset.fastFav)]);closeModal(m)})}
function addFavoriteFromRow(row){const name=$('.food-name',row)?.value?.trim();if(!name)return;savePrefs(p=>{p.favorites=Array.isArray(p.favorites)?p.favorites:[];const key=name.toLowerCase();const exists=p.favorites.findIndex(x=>String(x).toLowerCase()===key);if(exists>=0){p.favorites.splice(exists,1);toast('Removed from favorites')}else{p.favorites.unshift(name);p.favorites=p.favorites.slice(0,30);toast('Added to favorites')}})}
function decorateRows(){const favs=(prefs().favorites||[]).map(x=>String(x).toLowerCase());$$('#mealSections .food-row').forEach(row=>{if($('.food-favorite',row))return;const name=$('.food-name',row)?.value||'';const b=document.createElement('button');b.type='button';b.className='food-favorite';b.setAttribute('aria-label','Favorite food');b.textContent=favs.includes(name.toLowerCase())?'★':'☆';b.onclick=()=>{addFavoriteFromRow(row);setTimeout(render,100)};row.appendChild(b)})}
function rememberPortions(){state=Store.read();const next=clone(state);next.profile=next.profile||{};next.profile.experience=next.profile.experience||{};next.profile.experience.food=next.profile.experience.food||{favorites:[],portions:{}};const portions=next.profile.experience.food.portions||{};$$('#mealSections .food-row').forEach(row=>{const name=$('.food-name',row)?.value?.trim();if(!name)return;const amount=n($('.food-amount',row)?.value),unit=$('.food-unit',row)?.value||'g';if(amount>0)portions[name.toLowerCase()]={amount,unit}});next.profile.experience.food.portions=portions;Store.write(next)}
function applyRememberedPortion(row){const name=$('.food-name',row)?.value?.trim().toLowerCase();if(!name)return;const p=prefs().portions?.[name];if(!p)return;const amount=$('.food-amount',row),unit=$('.food-unit',row);if(amount&&(!amount.value||n(amount.value)<=0))amount.value=p.amount;if(unit&&p.unit)unit.value=p.unit}
function wordsNumber(v){const m={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,half:.5};return m[String(v||'').toLowerCase()]||n(v,1)}
function parseVoice(text){const lower=' '+String(text||'').toLowerCase().replace(/[,.;]+/g,' ')+' ';const matches=[];const candidates=[];foods.forEach(food=>{[food.name,...(food.aliases||[])].forEach(alias=>{const a=String(alias).toLowerCase();const idx=lower.indexOf(' '+a+' ');if(idx>=0)candidates.push({food,alias:a,idx})})});candidates.sort((a,b)=>a.idx-b.idx||b.alias.length-a.alias.length);const used=new Set();for(const c of candidates){if(used.has(c.food.name))continue;used.add(c.food.name);const before=lower.slice(Math.max(0,c.idx-24),c.idx).trim().split(/\s+/).pop();const qty=wordsNumber(before);let grams=n(c.food.defaultGrams,100)*Math.max(.25,qty);const nearby=lower.slice(Math.max(0,c.idx-30),c.idx+c.alias.length+25);const gm=nearby.match(/(\d+(?:\.\d+)?)\s*(g|gram|grams|ml)/);if(gm)grams=n(gm[1],grams);matches.push(fromPer100(c.food,grams))}return matches}
function previewVoice(text,items){const m=modal('Voice meal preview',`<p class="food-voice-heard">“${esc(text)}”</p>${items.length?`<div class="food-voice-list">${items.map((x,i)=>`<label><input type="checkbox" checked data-voice-item="${i}"><span><strong>${esc(x.name)}</strong><small>${Math.round(n(x.grams))} g · ${Math.round(n(x.calories))} kcal · ${Math.round(n(x.protein))}g protein</small></span></label>`).join('')}</div><label class="food-meal-select">Add to<select id="voiceMeal">${mealKeys.map(k=>`<option value="${k}" ${k===currentMeal()?'selected':''}>${labels[k]}</option>`).join('')}</select></label><button type="button" class="primary full" id="voiceAddFood">Add selected foods</button>`:'<p class="empty">I could not match foods confidently. Try names from the food database, for example “3 rotis, 150 grams chicken curry and one bowl dal”.</p>'}`);$('#voiceAddFood',m)?.addEventListener('click',()=>{const meal=$('#voiceMeal',m)?.value||currentMeal(),selected=$$('[data-voice-item]:checked',m).map(x=>items[n(x.dataset.voiceItem)]);if(!selected.length)return;const next=clone(Store.read()),meals=ensureMeals(next);meals[meal].push(...selected.map(x=>({...clone(x),savedAt:new Date().toISOString()})));write(next,`${selected.length} foods added`);closeModal(m)})}
function voiceLog(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){const text=prompt('Describe your meal, for example: 3 rotis, 150 grams chicken curry and dal');if(text)previewVoice(text,parseVoice(text));return}const r=new Recognition();r.lang='en-IN';r.interimResults=false;r.maxAlternatives=1;toast('Listening…');r.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript||'';previewVoice(text,parseVoice(text))};r.onerror=()=>toast('Voice logging was not available. Try again or use normal food search.');r.start()}
function ensureToolbar(){const host=$('#food'),anchor=$('#mealSections');if(!host||!anchor)return;let bar=$('#experienceFoodTools');if(!bar){bar=document.createElement('section');bar.id='experienceFoodTools';bar.className='food-fast-tools';anchor.before(bar)}bar.innerHTML='<button type="button" data-fast="favorites">★ Favorites</button><button type="button" data-fast="repeat">Repeat meal</button><button type="button" data-fast="voice">🎙 Voice log</button>';bar.onclick=e=>{const a=e.target.closest('[data-fast]')?.dataset.fast;if(a==='favorites')openFavorites();if(a==='repeat'){const key=prompt('Repeat which meal? breakfast, lunch, snacks or dinner',labels[currentMeal()]);if(!key)return;const k=String(key).toLowerCase().startsWith('break')?'breakfast':String(key).toLowerCase().startsWith('lunch')?'lunch':String(key).toLowerCase().startsWith('snack')?'eveningSnacks':'dinner';repeatMeal(k)}if(a==='voice')voiceLog()}}
function render(){state=Store.read();ensureToolbar();decorateRows()}
function wire(){if(wired)return;wired=true;window.addEventListener('mybody:state',()=>setTimeout(render,100));document.addEventListener('click',e=>{if(e.target.closest('[data-action="save-food"]'))setTimeout(()=>{rememberPortions();render()},180)},true);document.addEventListener('change',e=>{const row=e.target.closest('.food-row');if(row&&e.target.classList.contains('food-name'))applyRememberedPortion(row)},true);const o=new MutationObserver(()=>requestAnimationFrame(render));o.observe(document.body,{childList:true,subtree:true})}
function init(){render();wire()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
window.MyBodyFastFood={voiceLog,repeatMeal,openFavorites};
})();