(function(){
'use strict';
const Store=window.MyBodyStore;if(!Store)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
let state=Store.read(),wired=false;
function dayNumber(){const created=state.profile?.createdAt||state.profile?.coach?.plan?.createdAt;let start=created?new Date(created):null;if(!start||Number.isNaN(+start)){const dates=[...(state.weights||[]).map(x=>x.date),...Object.keys(state.nutrition||{}),...Object.keys(state.workoutLog||{})].filter(Boolean).sort();start=dates.length?new Date(dates[0]+'T12:00:00'):new Date()}const diff=Math.floor((Date.now()-start.getTime())/86400000)+1;return Math.max(1,diff)}
function step(day){if(day<=1)return{title:'Start simple',body:'Build your plan, log today’s food and complete or schedule your workout. You do not need to fill every screen.',label:'Open coach',action:'coach'};if(day<=3)return{title:'Learn your training effort',body:'After working sets choose Easy, Good, Hard or Max. MYBODY uses that with your reps to guide progression.',label:'Open workout',action:'workout'};if(day<=5)return{title:'Make food logging faster',body:'Use Favorites, Repeat meal and Voice log. Consistency matters more than perfect food entries.',label:'Open food',action:'food'};if(day<=6)return{title:'Add one body check',body:'Log weight or waist so MYBODY can separate daily noise from real transformation trends.',label:'Open progress',action:'progress'};return{title:'Your first weekly review is ready',body:'Check hunger, energy and training performance. MYBODY will tell you whether to keep or adjust the plan.',label:'Weekly review',action:'review'}}
function dismissed(day){return localStorage.getItem(`mybody.firstweek.dismiss.${day}`)==='1'}
function ensure(){const host=$('#today'),brief=$('#experienceBrief');if(!host||!brief)return;const day=dayNumber();let card=$('#experienceFirstWeek');if(day>7||dismissed(day)){card?.remove();return}if(!card){card=document.createElement('section');card.id='experienceFirstWeek';card.className='experience-firstweek';brief.insertAdjacentElement('afterend',card)}const s=step(day);card.innerHTML=`<div><span>DAY ${day} OF 7</span><strong>${s.title}</strong><p>${s.body}</p></div><div><button class="secondary" type="button" data-first-action>${s.label}</button><button class="text-btn" type="button" data-first-dismiss>Dismiss</button></div>`;card.querySelector('[data-first-action]').onclick=()=>act(s.action);card.querySelector('[data-first-dismiss]').onclick=()=>{localStorage.setItem(`mybody.firstweek.dismiss.${day}`,'1');card.remove()}}
function act(action){if(action==='review'){const hidden=$('#mybodyCoachCard [data-coach-action="review"]');hidden?.click();return}if(action==='coach'){const hidden=$('#mybodyCoachCard [data-coach-action="plan"],#mybodyCoachCard [data-coach-action="build"]');hidden?.click();return}const tab=$(`[data-tab="${action}"],[data-nav="${action}"],#${action}-tab`);tab?.click()}
function unifyAccountLanguage(){$$('.cloud-auth-overlay').forEach(o=>{const h=o.querySelector('h2');if(h)h.textContent='MYBODY account';o.querySelectorAll('p').forEach(p=>{p.textContent=p.textContent.replace('Your tracker is synced to MYBODY 2.0 cloud.','Your MYBODY account is backed up and synced.').replace('Cloud sync is not connected for this profile.','Backup & sync is not connected yet. Your device copy still works offline.').replace('Cloud account created.','MYBODY account backup created.').replace('Connect cloud','Enable backup & sync')});const go=o.querySelector('.cloud-go');if(go&&/Connect cloud/i.test(go.textContent))go.textContent='Enable backup & sync'})}
function render(){state=Store.read();ensure();unifyAccountLanguage()}
function wire(){if(wired)return;wired=true;window.addEventListener('mybody:state',()=>setTimeout(render,100));const o=new MutationObserver(()=>requestAnimationFrame(render));o.observe(document.body,{childList:true,subtree:true})}
function init(){render();wire()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();