(function(){
'use strict';
const Store=window.MyBodyStore;if(!Store)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
let state=Store.read(),wired=false,timer=null,renderQueued=false;
const REST_KEY='mybody.experience.restEnd.v1';
const n=(v,f=0)=>{const x=Number(v);return Number.isFinite(x)?x:f};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function selectedDay(){return n($('.day-btn.active')?.dataset.day,$('.wr-day-select')?.value||0)}
function exerciseIndex(name){return state.workouts?.[selectedDay()]?.exercises?.findIndex(x=>String(x[0]).toLowerCase()===String(name||'').toLowerCase())??-1}
function previous(day,index){const dates=Object.keys(state.workoutLog||{}).filter(d=>d<Store.localDate()).sort().reverse();for(const d of dates){const ex=state.workoutLog?.[d]?.[day]?.exercises?.[index];if(ex)return{date:d,ex}}return null}
function workingSets(ex){return (ex?.setsDetail||[]).filter(s=>n(s.actualWeight)>0&&n(s.actualReps)>0)}
function increment(load,name){if(/machine|cable|pulldown|row|extension|curl/i.test(name))return load<20?1:2.5;if(/dumbbell|db/i.test(name))return load<20?1:2;return 2.5}
function recommendation(name,plannedReps,prev){if(!prev)return{last:'No previous set',target:'Choose a controlled starting load',note:'Leave 2–3 good reps in reserve on your first logged session.',load:0};const sets=workingSets(prev.ex);if(!sets.length)return{last:'Previous session logged',target:'Repeat the last planned load',note:'Complete the target reps cleanly before increasing.',load:n(prev.ex?.weight)};const best=sets.slice().sort((a,b)=>n(b.actualWeight)-n(a.actualWeight)||n(b.actualReps)-n(a.actualReps))[0],load=n(best.actualWeight),reps=n(best.actualReps);const hit=sets.every(s=>s.done!==false&&n(s.actualReps)>=n(s.targetReps,plannedReps)),efforts=sets.map(s=>s.effort).filter(Boolean),maxCount=efforts.filter(x=>x==='max').length,hardCount=efforts.filter(x=>x==='hard').length;let next=load,note='Repeat this load and make the reps cleaner.';if(hit&&!maxCount&&hardCount<=Math.floor(sets.length/3)){next=load+increment(load,name);note='Targets were completed with control. A small increase is reasonable.'}else if(!hit&&sets.filter(s=>n(s.actualReps)<n(s.targetReps,plannedReps)-2).length>=Math.ceil(sets.length/2)){next=Math.max(0,load-increment(load,name));note='Several reps were missed. A small reduction can improve quality.'}else if(maxCount)note='You reached your limit. Keep the same load until it feels more controlled.';return{last:`${load} kg × ${reps}`,target:`${Math.round(next*10)/10} kg × ${plannedReps}`,note,load:next}}
function isBarbell(name){return /barbell|bench press|back squat|front squat|deadlift|ohp|overhead press/i.test(name||'')&&!/dumbbell|db|machine|cable|smith/i.test(name||'')}
function platePlan(total,bar=20){const per=Math.max(0,(total-bar)/2),plates=[25,20,15,10,5,2.5,1.25],out=[];let rem=per;plates.forEach(p=>{const count=Math.floor((rem+1e-6)/p);if(count){out.push([p,count]);rem-=p*count}});return{per,plates:out,remainder:Math.max(0,rem)}}
function close(m){m.classList.add('hidden');if(!document.querySelector('.xp-modal:not(.hidden),.sheet-backdrop:not(.hidden),.coach-modal:not(.hidden)'))document.body.classList.remove('modal-open')}
function openPlate(target){let m=$('#experiencePlateModal');if(!m){m=document.createElement('div');m.id='experiencePlateModal';m.className='xp-modal hidden';document.body.appendChild(m)}m.innerHTML=`<div class="xp-modal-panel workout-plate-modal"><header><div><h2>Plate calculator</h2><p>Calculate plates per side for a standard barbell.</p></div><button class="xp-close" type="button">×</button></header><div class="plate-form"><label>Total weight (kg)<input id="plateTotal" type="number" step="0.5" value="${target||60}"></label><label>Bar weight (kg)<select id="plateBar"><option>20</option><option>15</option><option>10</option></select></label></div><div id="plateResult"></div></div>`;m.classList.remove('hidden');document.body.classList.add('modal-open');const draw=()=>{const p=platePlan(n($('#plateTotal',m).value),n($('#plateBar',m).value,20));$('#plateResult',m).innerHTML=p.per<=0?'<p class="empty">Total weight must be heavier than the bar.</p>':`<div class="plate-result"><span>Each side</span><strong>${p.plates.length?p.plates.map(([w,c])=>`${c} × ${w} kg`).join(' + '):'No plates'}</strong>${p.remainder>.05?`<small>Approximation is ${p.remainder.toFixed(2)} kg short per side with available plates.</small>`:''}</div>`};m.querySelector('.xp-close').onclick=()=>close(m);m.onclick=e=>{if(e.target===m)close(m)};$$('input,select',m).forEach(x=>x.oninput=draw);draw()}
function renderTarget(){state=Store.read();const sheet=$('#exerciseDetailSheet');if(!sheet||sheet.classList.contains('hidden'))return;const name=$('#exerciseDetailTitle')?.textContent||'',day=selectedDay(),idx=exerciseIndex(name);if(idx<0)return;const exercise=state.workouts?.[day]?.exercises?.[idx],reps=n(exercise?.[2],10),prev=previous(day,idx),rec=recommendation(name,reps,prev);let card=$('#experienceNextTarget',sheet);if(!card){card=document.createElement('section');card.id='experienceNextTarget';card.className='experience-next-target';const anchor=$('#phase2WorkoutGuide',sheet)||$('.exercise-set-table',sheet);anchor?.insertAdjacentElement('beforebegin',card)}const key=[name,rec.last,rec.target,rec.note,rec.load].join('|');if(card.dataset.renderKey===key)return;card.dataset.renderKey=key;card.innerHTML=`<div><span>Previous</span><strong>${esc(rec.last)}</strong></div><div class="next"><span>Today target</span><strong>${esc(rec.target)}</strong></div><p>${esc(rec.note)}</p>${isBarbell(name)&&rec.load?'<button type="button" class="text-btn" data-plate>Plate calculator</button>':''}`;card.querySelector('[data-plate]')?.addEventListener('click',()=>openPlate(rec.load))}
function restSeconds(name){return /bench|press|squat|deadlift|row|pulldown|pull-up|dip|leg press|hack squat|ohp/i.test(name||'')?150:/calf|lunge|split squat/i.test(name||'')?105:75}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function renderPersistentRest(){const end=n(localStorage.getItem(REST_KEY));if(end<=Date.now()){localStorage.removeItem(REST_KEY);$('#experienceRestPersist')?.remove();stopTimer();return}const native=$('#phase2RestTimer');if(native&&!native.classList.contains('hidden')){$('#experienceRestPersist')?.remove();stopTimer();return}let bar=$('#experienceRestPersist');if(!bar){bar=document.createElement('div');bar.id='experienceRestPersist';bar.className='experience-rest';bar.innerHTML='<div><small>REST</small><strong>0:00</strong><span>Timer restored</span></div><button type="button">Skip</button>';document.body.appendChild(bar);bar.querySelector('button').onclick=()=>{localStorage.removeItem(REST_KEY);bar.remove();stopTimer()}}const left=Math.max(0,Math.ceil((end-Date.now())/1000)),text=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;if(bar.querySelector('strong').textContent!==text)bar.querySelector('strong').textContent=text;if(!timer)timer=setInterval(renderPersistentRest,1000)}
function storeRestFromDone(e){const btn=e.target.closest('button');if(!btn||!$('#exerciseDetailSheet')?.contains(btn))return;const txt=(btn.textContent||'').trim().toLowerCase();if(!/done|save set|complete/.test(txt))return;const name=$('#exerciseDetailTitle')?.textContent||'';localStorage.setItem(REST_KEY,String(Date.now()+restSeconds(name)*1000));setTimeout(renderPersistentRest,80)}
function render(){renderQueued=false;renderTarget();renderPersistentRest()}
function scheduleRender(ms=0){if(ms){setTimeout(()=>scheduleRender(),ms);return}if(renderQueued)return;renderQueued=true;requestAnimationFrame(render)}
function wire(){if(wired)return;wired=true;window.addEventListener('mybody:state',()=>scheduleRender(100));document.addEventListener('click',e=>{storeRestFromDone(e);if(e.target.closest('#workout-tab,[data-nav="workout"],[data-tab="workout"],[data-action="save-exercise-detail"],.exercise,[data-exercise-detail],#saveWorkout,.sheet-close')){scheduleRender(120);scheduleRender(320)}},true);document.addEventListener('change',e=>{if(e.target.matches('.wr-day-select,#workoutDaySelect'))scheduleRender(100)},true);window.addEventListener('pageshow',()=>scheduleRender(100))}
function init(){render();wire();setTimeout(()=>scheduleRender(),300)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
window.MyBodyWorkoutExperience={recommendation,platePlan};
})();