/* Offline food database. Values are approximate per 100 g edible portion.
   Indian staples are aligned with ICMR-NIN IFCT 2017 where comparable.
   Prepared dishes use standardized home-recipe estimates; oil and recipes vary. */
window.FOOD_DB = [
// Eggs, meat and fish
{name:'Egg, whole',aliases:['egg','eggs','boiled egg','anda'],calories:143,protein:12.6,carbs:0.7,fat:9.5,defaultGrams:50},
{name:'Egg white',aliases:['egg whites','white egg'],calories:52,protein:10.9,carbs:0.7,fat:0.2,defaultGrams:33},
{name:'Omelette',aliases:['egg omelette','omelet','anda omelette'],calories:154,protein:10.8,carbs:1.9,fat:11.5,defaultGrams:100},
{name:'Egg curry',aliases:['anda curry','egg masala'],calories:155,protein:9,carbs:5.5,fat:10.5,defaultGrams:150},
{name:'Chicken breast, cooked',aliases:['chicken breast','grilled chicken','plain chicken'],calories:165,protein:31,carbs:0,fat:3.6,defaultGrams:150},
{name:'Chicken curry',aliases:['chicken gravy','chicken masala'],calories:190,protein:18,carbs:6,fat:10,defaultGrams:150},
{name:'Butter chicken',aliases:['murgh makhani','chicken makhani'],calories:210,protein:14,carbs:8,fat:13.5,defaultGrams:180},
{name:'Chicken tikka',aliases:['grilled chicken tikka','murgh tikka'],calories:148,protein:19,carbs:4,fat:6,defaultGrams:150},
{name:'Tandoori chicken',aliases:['tandoori murgh'],calories:177,protein:24,carbs:3.6,fat:7.5,defaultGrams:180},
{name:'Mutton curry',aliases:['mutton gravy','mutton masala','goat curry'],calories:250,protein:25,carbs:5,fat:15,defaultGrams:150},
{name:'Fish, cooked',aliases:['fish','grilled fish','plain fish'],calories:180,protein:26,carbs:0,fat:8,defaultGrams:150},
{name:'Fish curry',aliases:['machli curry','fish gravy'],calories:170,protein:14,carbs:4,fat:10.5,defaultGrams:150},
{name:'Fish fry',aliases:['fried fish','machli fry'],calories:220,protein:20,carbs:8,fat:12,defaultGrams:150},

// Dal, pulses and legumes
{name:'Dal, plain cooked',aliases:['dal','daal','plain lentils'],calories:116,protein:9,carbs:20,fat:0.4,defaultGrams:150},
{name:'Dal tadka',aliases:['tadka dal','dal fry'],calories:128,protein:6,carbs:16.5,fat:4.5,defaultGrams:150},
{name:'Toor dal, cooked',aliases:['arhar dal','tuvar dal','pigeon pea dal'],calories:121,protein:6.8,carbs:19.7,fat:1.8,defaultGrams:150},
{name:'Moong dal, cooked',aliases:['mung dal','green gram dal'],calories:105,protein:7,carbs:18,fat:0.4,defaultGrams:150},
{name:'Masoor dal, cooked',aliases:['red lentil dal','masur dal'],calories:116,protein:9,carbs:20,fat:0.4,defaultGrams:150},
{name:'Chana dal, cooked',aliases:['bengal gram dal','split chickpea dal'],calories:164,protein:9,carbs:27,fat:2.5,defaultGrams:150},
{name:'Rajma masala',aliases:['rajma','kidney bean curry'],calories:127,protein:6,carbs:20,fat:3,defaultGrams:180},
{name:'Chole masala',aliases:['chole','chana masala','chickpea curry'],calories:164,protein:8,carbs:22,fat:5.5,defaultGrams:180},
{name:'Sambar',aliases:['sambhar','lentil vegetable stew'],calories:66,protein:3,carbs:10,fat:1.8,defaultGrams:180},
{name:'Rasam',aliases:['tomato rasam','pepper rasam'],calories:36,protein:1.2,carbs:6,fat:0.8,defaultGrams:180},
{name:'Kadhi',aliases:['kadhi pakora','yogurt curry'],calories:92,protein:3.5,carbs:9,fat:4.5,defaultGrams:180},
{name:'Moong sprouts',aliases:['sprouts','sprouted moong','mung sprouts'],calories:30,protein:3,carbs:5.9,fat:0.2,defaultGrams:100},

// Roti, bread and flour dishes
{name:'Chapati / roti',aliases:['chapati','roti','wheat roti'],calories:297,protein:10,carbs:55,fat:6,defaultGrams:40},
{name:'Phulka',aliases:['phulka roti','oil free roti'],calories:263,protein:9,carbs:52,fat:2.5,defaultGrams:35},
{name:'Paratha, plain',aliases:['plain paratha','parantha'],calories:326,protein:7,carbs:45,fat:14,defaultGrams:70},
{name:'Aloo paratha',aliases:['potato paratha','aloo parantha'],calories:230,protein:6,carbs:35,fat:7.5,defaultGrams:100},
{name:'Methi paratha',aliases:['fenugreek paratha'],calories:263,protein:7,carbs:39,fat:9,defaultGrams:80},
{name:'Puri',aliases:['poori','fried indian bread'],calories:296,protein:7,carbs:40,fat:12,defaultGrams:30},
{name:'Bhatura',aliases:['bhature','fried leavened bread'],calories:327,protein:8,carbs:48,fat:12,defaultGrams:90},
{name:'Naan, plain',aliases:['naan','plain naan'],calories:291,protein:9,carbs:50,fat:5,defaultGrams:90},
{name:'Butter naan',aliases:['naan butter'],calories:330,protein:9,carbs:48,fat:11,defaultGrams:100},
{name:'Kulcha',aliases:['plain kulcha'],calories:275,protein:8,carbs:51,fat:4.5,defaultGrams:90},
{name:'Pav / bread roll',aliases:['pav','ladi pav','bread roll'],calories:270,protein:9,carbs:52,fat:3.5,defaultGrams:50},

// Rice and grain dishes
{name:'White rice, cooked',aliases:['rice','white rice','cooked rice','chawal'],calories:130,protein:2.7,carbs:28,fat:0.3,defaultGrams:150},
{name:'Brown rice, cooked',aliases:['brown rice'],calories:123,protein:2.7,carbs:25.6,fat:1,defaultGrams:150},
{name:'Jeera rice',aliases:['cumin rice'],calories:157,protein:3,carbs:29,fat:3.2,defaultGrams:180},
{name:'Vegetable pulao',aliases:['veg pulao','vegetable pilaf'],calories:160,protein:3.5,carbs:27,fat:4.5,defaultGrams:200},
{name:'Moong dal khichdi',aliases:['khichdi','khichri','dal rice'],calories:111,protein:4,carbs:20,fat:1.8,defaultGrams:200},
{name:'Chicken biryani',aliases:['biryani','chicken biriyani'],calories:190,protein:9,carbs:28,fat:5.5,defaultGrams:250},
{name:'Mutton biryani',aliases:['mutton biriyani','goat biryani'],calories:220,protein:10,carbs:27,fat:8.5,defaultGrams:250},
{name:'Vegetable biryani',aliases:['veg biryani','vegetable biriyani'],calories:170,protein:4,carbs:29,fat:4.5,defaultGrams:250},
{name:'Curd rice',aliases:['yogurt rice','dahi rice'],calories:138,protein:3.5,carbs:22,fat:4,defaultGrams:200},
{name:'Lemon rice',aliases:['nimbu rice','chitranna'],calories:175,protein:3.5,carbs:29,fat:5,defaultGrams:200},
{name:'Tamarind rice',aliases:['puliyogare','puliyodarai'],calories:190,protein:4,carbs:33,fat:5,defaultGrams:200},
{name:'Coconut rice',aliases:['thengai sadam'],calories:210,protein:4,carbs:33,fat:7,defaultGrams:200},

// Breakfast and light meals
{name:'Idli',aliases:['idly','steamed rice cake'],calories:146,protein:4.5,carbs:29,fat:1,defaultGrams:50},
{name:'Dosa, plain',aliases:['plain dosa','dose'],calories:184,protein:4.5,carbs:28,fat:6,defaultGrams:100},
{name:'Masala dosa',aliases:['potato dosa'],calories:200,protein:4.5,carbs:30,fat:7,defaultGrams:180},
{name:'Rava dosa',aliases:['sooji dosa','semolina dosa'],calories:210,protein:5,carbs:31,fat:7.5,defaultGrams:120},
{name:'Uttapam',aliases:['uthappam','vegetable uttapam'],calories:170,protein:5,carbs:28,fat:4.5,defaultGrams:150},
{name:'Poha, vegetables',aliases:['poha','kanda poha','flattened rice'],calories:130,protein:3,carbs:24,fat:3,defaultGrams:180},
{name:'Upma',aliases:['rava upma','sooji upma'],calories:125,protein:3.3,carbs:22,fat:3,defaultGrams:180},
{name:'Dalia, cooked',aliases:['broken wheat porridge','wheat dalia'],calories:83,protein:3.1,carbs:18.6,fat:0.2,defaultGrams:180},
{name:'Sabudana khichdi',aliases:['sago khichdi'],calories:180,protein:3,carbs:30,fat:6,defaultGrams:180},
{name:'Besan chilla',aliases:['besan cheela','gram flour pancake'],calories:190,protein:10,carbs:27,fat:6,defaultGrams:100},
{name:'Moong dal chilla',aliases:['moong cheela','mung pancake'],calories:170,protein:10,carbs:27,fat:3,defaultGrams:100},
{name:'Appam',aliases:['palappam','rice appam'],calories:170,protein:3.5,carbs:34,fat:2.2,defaultGrams:100},
{name:'Puttu',aliases:['rice puttu'],calories:190,protein:4,carbs:40,fat:1.4,defaultGrams:150},
{name:'Medu vada',aliases:['vada','medhu vadai','urad vada'],calories:290,protein:8,carbs:34,fat:13,defaultGrams:70},
{name:'Pav bhaji',aliases:['bhaji pav'],calories:150,protein:4,carbs:22,fat:5.5,defaultGrams:250},
{name:'Misal pav',aliases:['misal'],calories:160,protein:7,carbs:25,fat:4.5,defaultGrams:250},

// Paneer and vegetable dishes
{name:'Paneer',aliases:['cottage cheese','paneer cheese'],calories:265,protein:18.3,carbs:1.2,fat:20.8,defaultGrams:100},
{name:'Palak paneer',aliases:['saag paneer','spinach paneer'],calories:150,protein:8,carbs:6,fat:11,defaultGrams:180},
{name:'Matar paneer',aliases:['mutter paneer','peas paneer'],calories:170,protein:8,carbs:10,fat:12,defaultGrams:180},
{name:'Paneer butter masala',aliases:['paneer makhani','butter paneer'],calories:210,protein:8,carbs:8,fat:16,defaultGrams:180},
{name:'Shahi paneer',aliases:['royal paneer curry'],calories:220,protein:8,carbs:9,fat:17,defaultGrams:180},
{name:'Kadai paneer',aliases:['karahi paneer'],calories:180,protein:9,carbs:9,fat:13,defaultGrams:180},
{name:'Aloo sabzi',aliases:['potato curry','aloo curry'],calories:120,protein:2.5,carbs:18,fat:4.5,defaultGrams:150},
{name:'Aloo gobi',aliases:['potato cauliflower'],calories:100,protein:3,carbs:15,fat:3.5,defaultGrams:150},
{name:'Bhindi masala',aliases:['bhindi','okra masala','ladyfinger sabzi'],calories:95,protein:2.5,carbs:12,fat:4.5,defaultGrams:150},
{name:'Baingan bharta',aliases:['baingan','eggplant bharta','brinjal bharta'],calories:105,protein:2,carbs:11,fat:6,defaultGrams:150},
{name:'Mixed vegetable curry',aliases:['mixed veg','mixed vegetables','vegetable curry'],calories:90,protein:3,carbs:12,fat:4,defaultGrams:150},
{name:'Lauki sabzi',aliases:['bottle gourd curry','dudhi sabzi'],calories:55,protein:1.5,carbs:8,fat:2,defaultGrams:150},
{name:'Cabbage sabzi',aliases:['patta gobi','cabbage curry'],calories:65,protein:2.2,carbs:9,fat:2.5,defaultGrams:150},
{name:'Gobi matar',aliases:['cauliflower peas curry'],calories:90,protein:4,carbs:14,fat:2.5,defaultGrams:150},
{name:'Palak sabzi',aliases:['spinach sabzi','palak bhaji'],calories:75,protein:3.5,carbs:8,fat:3.5,defaultGrams:150},
{name:'Mushroom masala',aliases:['mushroom curry'],calories:105,protein:4,carbs:8,fat:6.5,defaultGrams:150},
{name:'Karela sabzi',aliases:['karela','bitter gourd curry'],calories:85,protein:2.5,carbs:11,fat:4,defaultGrams:150},
{name:'Potato, cooked',aliases:['potato','boiled potato','aloo'],calories:87,protein:1.9,carbs:20.1,fat:0.1,defaultGrams:150},

// Dairy, protein supplements, nuts and seeds
{name:'Curd / dahi',aliases:['curd','yogurt','dahi'],calories:61,protein:3.5,carbs:4.7,fat:3.3,defaultGrams:150},
{name:'Greek yogurt, low fat',aliases:['greek yogurt'],calories:73,protein:9.9,carbs:3.9,fat:1.9,defaultGrams:150},
{name:'Milk, whole',aliases:['milk','full cream milk'],calories:61,protein:3.2,carbs:4.8,fat:3.3,defaultGrams:250},
{name:'Milk, toned',aliases:['toned milk','low fat milk'],calories:58,protein:3.1,carbs:4.7,fat:3,defaultGrams:250},
{name:'Buttermilk / chaas',aliases:['buttermilk','chaas','chhach'],calories:40,protein:3.3,carbs:4.8,fat:0.9,defaultGrams:250},
{name:'Lassi, salted',aliases:['salt lassi','namkeen lassi'],calories:55,protein:3,carbs:5,fat:2.5,defaultGrams:250},
{name:'Lassi, sweet',aliases:['sweet lassi'],calories:100,protein:3,carbs:15,fat:3,defaultGrams:250},
{name:'Whey protein',aliases:['whey','protein powder'],calories:400,protein:80,carbs:8,fat:6,defaultGrams:30},
{name:'Oats, dry',aliases:['oats','rolled oats'],calories:389,protein:16.9,carbs:66.3,fat:6.9,defaultGrams:50},
{name:'Almonds',aliases:['almond','badam','badaam'],calories:579,protein:21.2,carbs:21.6,fat:49.9,defaultGrams:20},
{name:'Cashews',aliases:['cashew','kaju'],calories:553,protein:18.2,carbs:30.2,fat:43.9,defaultGrams:20},
{name:'Peanuts, roasted',aliases:['peanut','groundnut','moongfali'],calories:587,protein:24,carbs:21,fat:50,defaultGrams:25},
{name:'Roasted chana',aliases:['bhuna chana','roasted gram'],calories:370,protein:22,carbs:58,fat:6,defaultGrams:30},
{name:'Makhana, dry roasted',aliases:['makhana','fox nuts','lotus seeds'],calories:347,protein:9.7,carbs:76.9,fat:0.1,defaultGrams:25},
{name:'Ghee',aliases:['ghee','cow ghee','clarified butter'],calories:900,protein:0,carbs:0,fat:100,defaultGrams:5},

// Street food and snacks
{name:'Samosa',aliases:['aloo samosa','vegetable samosa'],calories:262,protein:5,carbs:32,fat:13,defaultGrams:80},
{name:'Kachori',aliases:['dal kachori'],calories:330,protein:7,carbs:39,fat:16,defaultGrams:70},
{name:'Onion pakora',aliases:['pakora','pakoda','onion bhaji'],calories:280,protein:7,carbs:31,fat:14,defaultGrams:100},
{name:'Dhokla',aliases:['khaman','khaman dhokla'],calories:160,protein:7,carbs:25,fat:4,defaultGrams:100},
{name:'Khandvi',aliases:['patuli','dahivadi'],calories:180,protein:7,carbs:20,fat:8,defaultGrams:100},
{name:'Vada pav',aliases:['wada pav','batata vada pav'],calories:250,protein:7,carbs:38,fat:8,defaultGrams:150},
{name:'Bhel puri',aliases:['bhelpuri','bhel'],calories:180,protein:5,carbs:32,fat:4,defaultGrams:150},
{name:'Pani puri',aliases:['golgappa','puchka'],calories:190,protein:5,carbs:33,fat:4,defaultGrams:120},
{name:'Sev puri',aliases:['sev batata puri'],calories:250,protein:6,carbs:35,fat:10,defaultGrams:150},
{name:'Aloo tikki',aliases:['potato tikki','aloo patties'],calories:210,protein:4,carbs:31,fat:8,defaultGrams:100},
{name:'Papad, roasted',aliases:['papad','papadum'],calories:330,protein:20,carbs:60,fat:2,defaultGrams:15},
{name:'Namkeen mixture',aliases:['namkeen','farsan','mixture'],calories:500,protein:12,carbs:50,fat:28,defaultGrams:30},

// Sweets and desserts
{name:'Gulab jamun',aliases:['gulabjamun'],calories:340,protein:5,carbs:53,fat:12,defaultGrams:50},
{name:'Jalebi',aliases:['jilebi'],calories:400,protein:3,carbs:70,fat:12,defaultGrams:50},
{name:'Rasgulla',aliases:['rasgola','rosogolla'],calories:186,protein:4,carbs:37,fat:2,defaultGrams:50},
{name:'Rice kheer',aliases:['kheer','payasam','rice pudding'],calories:134,protein:3.5,carbs:22,fat:3.5,defaultGrams:150},
{name:'Suji halwa',aliases:['sooji halwa','sheera'],calories:285,protein:4,carbs:45,fat:10,defaultGrams:100},
{name:'Gajar halwa',aliases:['carrot halwa','gajrela'],calories:220,protein:4,carbs:30,fat:10,defaultGrams:100},
{name:'Besan laddu',aliases:['besan ladoo','gram flour laddu'],calories:470,protein:11,carbs:54,fat:24,defaultGrams:35},
{name:'Milk barfi',aliases:['barfi','burfi','milk fudge'],calories:400,protein:9,carbs:55,fat:16,defaultGrams:40},

// Fruit and drinks
{name:'Banana',aliases:['banana','kela'],calories:89,protein:1.1,carbs:22.8,fat:0.3,defaultGrams:100},
{name:'Apple',aliases:['apple','seb'],calories:52,protein:0.3,carbs:13.8,fat:0.2,defaultGrams:150},
{name:'Mango',aliases:['mango','aam'],calories:60,protein:0.8,carbs:15,fat:0.4,defaultGrams:150},
{name:'Papaya',aliases:['papaya','papita'],calories:43,protein:0.5,carbs:10.8,fat:0.3,defaultGrams:150},
{name:'Guava',aliases:['guava','amrood'],calories:68,protein:2.6,carbs:14.3,fat:1,defaultGrams:150},
{name:'Orange',aliases:['orange','santra'],calories:47,protein:0.9,carbs:11.8,fat:0.1,defaultGrams:150},
{name:'Pomegranate',aliases:['pomegranate','anar'],calories:83,protein:1.7,carbs:18.7,fat:1.2,defaultGrams:150},
{name:'Watermelon',aliases:['watermelon','tarbooz'],calories:30,protein:0.6,carbs:7.6,fat:0.2,defaultGrams:200},
{name:'Grapes',aliases:['grapes','angoor'],calories:69,protein:0.7,carbs:18.1,fat:0.2,defaultGrams:150},
{name:'Avocado',aliases:['avocado'],calories:160,protein:2,carbs:8.5,fat:14.7,defaultGrams:100},
{name:'Coconut, fresh',aliases:['fresh coconut','nariyal'],calories:354,protein:3.3,carbs:15.2,fat:33.5,defaultGrams:50},
{name:'Tea with milk and sugar',aliases:['tea','chai','milk tea'],calories:45,protein:1,carbs:7,fat:1.5,defaultGrams:150},
{name:'Coffee with milk and sugar',aliases:['coffee','milk coffee'],calories:50,protein:1.2,carbs:7.5,fat:1.7,defaultGrams:150},
{name:'Coconut water',aliases:['nariyal pani','tender coconut water'],calories:19,protein:0.7,carbs:3.7,fat:0.2,defaultGrams:250},
{name:'Sugarcane juice',aliases:['ganne ka ras','sugar cane juice'],calories:74,protein:0,carbs:18.5,fat:0,defaultGrams:250}
];
