/* MYBODY 2.0 local/offline background music player. User-imported audio only. */
(function(){
'use strict';
const DB_NAME='mybody.music.v1',STORE_NAME='tracks',DB_VERSION=1;
const PREF_KEY='mybody.music.preferences.v1';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const audio=document.createElement('audio');audio.id='mybodyMusicAudio';audio.preload='metadata';audio.playsInline=true;document.body.appendChild(audio);
let dbPromise=null,tracks=[],currentId='',currentUrl='',shuffle=false,repeat='off',filter='';

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(message,type='success'){const el=$('#appToast');if(!el)return;el.textContent=message;el.dataset.type=type;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function fmt(sec){sec=Math.max(0,Number(sec)||0);const m=Math.floor(sec/60),s=Math.floor(sec%60);return `${m}:${String(s).padStart(2,'0')}`}
function size(bytes){bytes=Number(bytes)||0;if(bytes<1024)return `${bytes} B`;if(bytes<1048576)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1048576).toFixed(1)} MB`}
function prefs(){try{return JSON.parse(localStorage.getItem(PREF_KEY)||'{}')||{}}catch(_){return {}}}
function savePrefs(){try{localStorage.setItem(PREF_KEY,JSON.stringify({currentId,shuffle,repeat,volume:audio.volume}))}catch(_){}}
function openDb(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE_NAME)){const store=db.createObjectStore(STORE_NAME,{keyPath:'id'});store.createIndex('addedAt','addedAt')}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return dbPromise}
async function tx(mode,run){const db=await openDb();return new Promise((resolve,reject)=>{const t=db.transaction(STORE_NAME,mode),s=t.objectStore(STORE_NAME);let result;try{result=run(s)}catch(e){reject(e);return}t.oncomplete=()=>resolve(result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error)})}
async function allTracks(){const db=await openDb();return new Promise((resolve,reject)=>{const t=db.transaction(STORE_NAME,'readonly'),s=t.objectStore(STORE_NAME),req=s.getAll();req.onsuccess=()=>resolve((req.result||[]).sort((a,b)=>Number(b.addedAt)-Number(a.addedAt)));req.onerror=()=>reject(req.error)})}
async function getTrack(id){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE_NAME,'readonly').objectStore(STORE_NAME).get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}
function makeId(file){return `${Date.now()}-${Math.random().toString(36).slice(2)}-${String(file.name||'audio').toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,36)}`}
function supported(file){return /^audio\//.test(file.type||'')||/\.(mp3|m4a|aac|wav|ogg|oga)$/i.test(file.name||'')}
async function importFiles(fileList){const files=Array.from(fileList||[]).filter(supported);if(!files.length){toast('Choose MP3, M4A, AAC, WAV or OGG audio files.','error');return}
  let added=0;for(const file of files){const id=makeId(file),title=String(file.name||'Track').replace(/\.[^.]+$/,'');const item={id,title,fileName:file.name,type:file.type||'audio/mpeg',size:file.size||0,addedAt:Date.now()+added,blob:file};await tx('readwrite',s=>s.put(item));added++}
  await refreshTracks();toast(`${added} track${added===1?'':'s'} added for offline playback`);}
async function deleteTrack(id){const wasCurrent=id===currentId;await tx('readwrite',s=>s.delete(id));if(wasCurrent){audio.pause();clearSource();currentId=''}await refreshTracks();savePrefs();toast('Track removed')}
function clearSource(){if(currentUrl){URL.revokeObjectURL(currentUrl);currentUrl=''}audio.removeAttribute('src');audio.load();document.documentElement.classList.remove('mb-music-active');$('#mbMusicMini')?.classList.add('hidden')}
async function playTrack(id,shouldPlay=true){const track=await getTrack(id);if(!track)return;currentId=id;if(currentUrl)URL.revokeObjectURL(currentUrl);currentUrl=URL.createObjectURL(track.blob);audio.src=currentUrl;audio.load();updateMetadata(track);render();savePrefs();if(shouldPlay){try{await audio.play()}catch(_){toast('Tap Play to start audio on this device.','error')}}}
function currentIndex(){return tracks.findIndex(t=>t.id===currentId)}
function nextId(direction=1){if(!tracks.length)return'';if(shuffle&&tracks.length>1){const options=tracks.filter(t=>t.id!==currentId);return options[Math.floor(Math.random()*options.length)]?.id||tracks[0].id}let i=currentIndex();if(i<0)i=0;else i=(i+direction+tracks.length)%tracks.length;return tracks[i]?.id||''}
async function next(){const id=nextId(1);if(id)await playTrack(id,true)}
async function prev(){if(audio.currentTime>4){audio.currentTime=0;return}const id=nextId(-1);if(id)await playTrack(id,true)}
function togglePlay(){if(!currentId){if(tracks[0])playTrack(tracks[0].id,true);else openLibrary();return}if(audio.paused)audio.play().catch(()=>toast('Tap Play again to start audio.','error'));else audio.pause()}
function cycleRepeat(){repeat=repeat==='off'?'all':repeat==='all'?'one':'off';audio.loop=repeat==='one';savePrefs();render()}
function toggleShuffle(){shuffle=!shuffle;savePrefs();render()}
function updateMetadata(track){if(!('mediaSession'in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:track.title||track.fileName||'MYBODY Music',artist:'MYBODY Device Music',album:'Offline Library'});navigator.mediaSession.playbackState=audio.paused?'paused':'playing'}catch(_){}}
function setupMediaSession(){if(!('mediaSession'in navigator))return;const set=(name,fn)=>{try{navigator.mediaSession.setActionHandler(name,fn)}catch(_){}};set('play',()=>audio.play());set('pause',()=>audio.pause());set('nexttrack',next);set('previoustrack',prev);set('seekbackward',d=>audio.currentTime=Math.max(0,audio.currentTime-(d.seekOffset||10)));set('seekforward',d=>audio.currentTime=Math.min(audio.duration||Infinity,audio.currentTime+(d.seekOffset||10)));set('seekto',d=>{if(Number.isFinite(d.seekTime))audio.currentTime=d.seekTime})}
function syncPosition(){const duration=Number.isFinite(audio.duration)?audio.duration:0,current=audio.currentTime||0;$$('[data-music-seek]').forEach(i=>{i.max=duration||1;i.value=Math.min(current,duration||1)});$$('[data-music-current]').forEach(x=>x.textContent=fmt(current));$$('[data-music-duration]').forEach(x=>x.textContent=fmt(duration));if('mediaSession'in navigator&&duration>0){try{navigator.mediaSession.setPositionState({duration,playbackRate:audio.playbackRate,position:Math.min(current,duration)})}catch(_){}}}
function playerLabel(){const t=tracks.find(x=>x.id===currentId);return t?.title||'Choose music'}
function injectUi(){if($('#mbMusicLauncher'))return;document.body.insertAdjacentHTML('beforeend',`
<button id="mbMusicLauncher" class="mb-music-launcher" type="button" aria-label="Open MYBODY Music"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 18V5l10-2v13M9 9l10-2M6.5 21C4.6 21 3 20 3 18.5S4.6 16 6.5 16 10 17 10 18.5 8.4 21 6.5 21Zm10-2c-1.9 0-3.5-1-3.5-2.5s1.6-2.5 3.5-2.5 3.5 1 3.5 2.5-1.6 2.5-3.5 2.5Z"/></svg><span>Music</span></button>
<div id="mbMusicMini" class="mb-music-mini hidden" aria-label="MYBODY music player"><button class="mb-music-mini-main" type="button" data-open-music><span class="mb-music-cover">♪</span><span class="mb-music-copy"><strong data-music-title>Choose music</strong><span data-music-status>Offline device library</span></span></button><div class="mb-music-mini-controls"><button type="button" data-music-prev aria-label="Previous">‹</button><button class="mb-music-toggle" type="button" data-music-play aria-label="Play">▶</button><button type="button" data-music-next aria-label="Next">›</button></div><input class="mb-music-mini-progress" data-music-seek type="range" min="0" max="1" value="0" step="0.1" aria-label="Music progress"></div>
<div id="mbMusicModal" class="mb-music-modal hidden"><section class="mb-music-panel" role="dialog" aria-modal="true" aria-labelledby="mbMusicTitle"><header class="mb-music-head"><div><h2 id="mbMusicTitle">MYBODY Music</h2><p>Import your own audio and keep it available offline on this device.</p></div><button class="mb-music-close" type="button" data-close-music aria-label="Close">×</button></header><div class="mb-music-now"><span class="mb-music-cover">♪</span><div><strong data-music-title>Choose music</strong><span data-music-status>No track selected</span><div class="mb-music-time"><span data-music-current>0:00</span><input data-music-seek type="range" min="0" max="1" value="0" step="0.1" aria-label="Seek"><span data-music-duration>0:00</span></div></div></div><div class="mb-music-main-controls"><button type="button" data-music-shuffle>Shuffle</button><button type="button" data-music-prev>Previous</button><button type="button" data-music-play>Play</button><button type="button" data-music-next>Next</button><button type="button" data-music-repeat>Repeat</button></div><div class="mb-music-toolbar"><input id="mbMusicSearch" type="search" placeholder="Search imported music" autocomplete="off"><label class="mb-music-import">Import music<input id="mbMusicImport" type="file" accept="audio/mpeg,audio/mp4,audio/x-m4a,audio/aac,audio/wav,audio/ogg,.mp3,.m4a,.aac,.wav,.ogg" multiple></label></div><p id="mbMusicStorage" class="mb-music-storage"></p><div id="mbMusicList" class="mb-music-list"></div><p class="mb-music-note">Imported files stay in this app's local device storage for offline playback. Background and lock-screen controls depend on browser/OS support. MYBODY does not download or convert YouTube audio.</p></section></div>`)}
function openLibrary(){const m=$('#mbMusicModal');if(!m)return;m.classList.remove('hidden');document.body.classList.add('modal-open');renderList();updateStorage();}
function closeLibrary(){const m=$('#mbMusicModal');if(m)m.classList.add('hidden');if(!document.querySelector('.sheet-backdrop:not(.hidden),.media-lightbox:not(.hidden),.xp-modal:not(.hidden),.coach-modal:not(.hidden),.mb-diet-modal:not(.hidden)'))document.body.classList.remove('modal-open')}
function renderList(){const list=$('#mbMusicList');if(!list)return;const q=filter.trim().toLowerCase(),visible=tracks.filter(t=>!q||`${t.title} ${t.fileName}`.toLowerCase().includes(q));if(!visible.length){list.innerHTML=`<div class="mb-music-empty">${tracks.length?'No matching tracks.':'No music imported yet.<br>Tap <b>Import music</b> and choose MP3/M4A/audio files from this device.'}</div>`;return}list.innerHTML=visible.map(t=>`<article class="mb-track ${t.id===currentId?'playing':''}" data-track-id="${esc(t.id)}"><button class="mb-track-play" type="button" data-play-track="${esc(t.id)}" aria-label="Play ${esc(t.title)}">${t.id===currentId&&!audio.paused?'❚❚':'▶'}</button><div class="mb-track-copy"><strong>${esc(t.title)}</strong><span>${esc(t.fileName)} · ${size(t.size)}</span></div><button class="mb-track-delete" type="button" data-delete-track="${esc(t.id)}" aria-label="Delete ${esc(t.title)}">×</button></article>`).join('')}
function render(){const title=playerLabel(),playing=currentId&&!audio.paused;$$('[data-music-title]').forEach(x=>x.textContent=title);$$('[data-music-status]').forEach(x=>x.textContent=currentId?(playing?'Playing from device':'Paused · offline device library'):'No track selected');$$('[data-music-play]').forEach(x=>{x.textContent=playing?'❚❚':'▶';x.setAttribute('aria-label',playing?'Pause':'Play')});const sh=$('[data-music-shuffle]');if(sh)sh.classList.toggle('active',shuffle);const rp=$('[data-music-repeat]');if(rp){rp.classList.toggle('active',repeat!=='off');rp.textContent=repeat==='one'?'Repeat 1':repeat==='all'?'Repeat all':'Repeat'}if(currentId){$('#mbMusicMini')?.classList.remove('hidden');document.documentElement.classList.add('mb-music-active')}else{$('#mbMusicMini')?.classList.add('hidden');document.documentElement.classList.remove('mb-music-active')}renderList();syncPosition();const t=tracks.find(x=>x.id===currentId);if(t)updateMetadata(t)}
async function refreshTracks(){tracks=await allTracks();render();await updateStorage()}
async function updateStorage(){const el=$('#mbMusicStorage');if(!el)return;const bytes=tracks.reduce((a,t)=>a+(Number(t.size)||0),0);let extra='';try{const e=await navigator.storage?.estimate?.();if(e?.quota)extra=` · App storage ${size(e.usage||0)} of ${size(e.quota)}`}catch(_){ }el.textContent=`${tracks.length} track${tracks.length===1?'':'s'} · ${size(bytes)} music${extra}`}
function events(){document.addEventListener('click',e=>{if(e.target.closest('#mbMusicLauncher,[data-open-music]'))openLibrary();if(e.target.closest('[data-close-music]'))closeLibrary();if(e.target.closest('[data-music-play]'))togglePlay();if(e.target.closest('[data-music-next]'))next();if(e.target.closest('[data-music-prev]'))prev();if(e.target.closest('[data-music-shuffle]'))toggleShuffle();if(e.target.closest('[data-music-repeat]'))cycleRepeat();const p=e.target.closest('[data-play-track]');if(p){if(p.dataset.playTrack===currentId)togglePlay();else playTrack(p.dataset.playTrack,true)}const d=e.target.closest('[data-delete-track]');if(d)deleteTrack(d.dataset.deleteTrack)},true);document.addEventListener('input',e=>{if(e.target.matches('[data-music-seek]'))audio.currentTime=Math.min(Number(e.target.value)||0,Number.isFinite(audio.duration)?audio.duration:0);if(e.target.id==='mbMusicSearch'){filter=e.target.value;renderList()}},true);document.addEventListener('change',e=>{if(e.target.id==='mbMusicImport'){importFiles(e.target.files).finally(()=>{e.target.value=''})}},true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#mbMusicModal')?.classList.contains('hidden'))closeLibrary()});audio.addEventListener('play',()=>{if('mediaSession'in navigator)try{navigator.mediaSession.playbackState='playing'}catch(_){ }render()});audio.addEventListener('pause',()=>{if('mediaSession'in navigator)try{navigator.mediaSession.playbackState='paused'}catch(_){ }render()});audio.addEventListener('timeupdate',syncPosition);audio.addEventListener('loadedmetadata',syncPosition);audio.addEventListener('ended',async()=>{if(repeat==='one'){audio.currentTime=0;audio.play().catch(()=>{})}else if(repeat==='all'||currentIndex()<tracks.length-1)await next();else{audio.pause();render()}});window.addEventListener('beforeunload',savePrefs)}
async function init(){injectUi();setupMediaSession();events();const p=prefs();shuffle=Boolean(p.shuffle);repeat=['off','all','one'].includes(p.repeat)?p.repeat:'off';audio.loop=repeat==='one';if(Number.isFinite(Number(p.volume)))audio.volume=Math.max(0,Math.min(1,Number(p.volume)));await refreshTracks();if(p.currentId&&tracks.some(t=>t.id===p.currentId)){await playTrack(p.currentId,false);audio.pause();render()}}
if(!('indexedDB'in window)){return}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
window.MyBodyMusic=Object.freeze({open:openLibrary,playTrack,refresh:refreshTracks});
})();
