(function(){
'use strict';
const Store=window.MyBodyStore;
if(!Store)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const clone=Store.clone;
const today=()=>Store.localDate();
let state=Store.read();
const mealKeys=['breakfast','lunch','eveningSnacks','dinner'];
const mealNames={breakfast:'Breakfast',lunch:'Lunch',eveningSnacks:'Snacks',dinner:'Dinner'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function write(next,msg){const r=Store.write(next);state=r.state;if(msg)toast(msg);setTimeout(renderAll,60);return r.ok}
function toast(m){const el=$('#appToast');if(!el)return;el.textContent=m;el.dataset.type='success';el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function dateBack(offset){const d=new Date();d.setDate(d.getDate()-offset);return Store.localDate(d)}
function dayNutrition(date){const meals=state.nutrition?.[date]?.meals||{};let c=0,p=0;mealKeys.forEach(k=>(meals[k]||[]).forEach(f=>{c+=n(f.calories);p+=n(f.protein)}));return{calories:c,protein:p}}
function average(arr){return arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:0}
function weightSeries(){return (state.weights||[]).filter(x=>n(x.weight)>0&&x.date).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
function weightTrend(){const w=weightSeries();if(w.length<4)return null;const recent=w.slice(0,Math.min(7,w.length)),prev=w.slice(recent.length,recent.length+7);if(!prev.length)return null;const r=average(recent.map(x=>n(x.weight))),p=average(prev.map(x=>n(x.weight)));return{recent:r,previous:p,change:r-p,pct:p?((r-p)/p*100):0}}
function adherence(){const rows=[];for(let i=0;i<14;i++){const d=dateBack(i),x=dayNutrition(d);if(x.calories>0)rows.push(x)}const calTarget=n(state.config?.calories),proteinTarget=n(state.config?.protein);return{days:rows.length,calories:average(rows.map(x=>x.calories)),protein:average(rows.map(x=>x.protein)),calorieAdherence:rows.length&&calTarget?average(rows.map(x=>Math.max(0,1-Math.abs(x.calories-calTarget)/calTarget))):0,proteinAdherence:rows.length&&proteinTarget?average(rows.map(x=>Math.min(1,x.protein/proteinTarget))):0}}
function effortLoad(){let total=0,hard=0;const dates=Object.keys(state.workoutLog||{}).sort().reverse().slice(0,10);for(const d of dates){for(const log of Object.values(state.workoutLog[d]||{})){for(const ex of log.exercises||[]){for(const s of ex.setsDetail||[]){if(!s.done)continue;total++;if(s.effort==='hard'||s.effort==='max')hard++}}}}return{total,ratio:total?hard/total:0}}
function readinessLoad(){const r=state.profile?.coach?.readiness||{};const vals=Object.keys(r).sort().reverse().slice(0,4).map(k=>n(r[k]?.score)).filter(Boolean);return{values:vals,average:average(vals)}}
function phase(){return state.profile?.phase3||{}}
function cardioWeek(){let minutes=0;for(let i=0;i<7;i++)minutes+=n(phase().cardio?.[dateBack(i)]);return minutes}
function recommendation(){
 const a=adherence(),w=weightTrend(),load=effortLoad(),ready=readinessLoad(),goal=state.profile?.coach?.plan?.profile?.goal||'general';
 if((ready.values.length>=2&&ready.average<58)||(load.total>=10&&load.ratio>.55))return{type:'recovery',title:'Recovery is the priority',body:'Recent training effort or readiness is running high. Keep loads conservative and consider a lighter week before pushing progression.',action:'deload'};
 if(a.days<5||!w)return{type:'learning',title:'MYBODY is learning your pattern',body:'Keep logging food, body weight and workouts. After enough consistent data, MYBODY can suggest small target adjustments instead of guessing.'};
 if(a.proteinAdherence<.82)return{type:'protein',title:'Protein consistency first',body:`Your recent average is ${Math.round(a.protein)} g/day versus a ${Math.round(n(state.config.protein))} g target. Improve this before changing calories.`};
 if(goal==='fat_loss'){
   if(w.pct<-1)return{type:'calories',title:'Your loss rate looks fast',body:`Recent trend is about ${Math.abs(w.pct).toFixed(1)}% down. A small +100 kcal adjustment may support training and recovery.`,delta:100};
   if(w.pct>-.2&&a.calorieAdherence>.72)return{type:'calories',title:'Progress is slower than planned',body:'Your logging consistency looks reasonable. A small 100 kcal reduction is enough for the next test period, not a large cut.',delta:-100};
 }
 if(goal==='muscle_gain'&&w.pct<.05&&a.calorieAdherence>.72)return{type:'calories',title:'Scale trend is flat',body:'A small +100 kcal increase is a reasonable next step if strength and recovery are stable.',delta:100};
 return{type:'steady',title:'Stay the course',body:'Your recent trend and adherence do not justify a target change. Keep the current plan and review again after another week.'};
}
function ensureAdaptive(){const todayPanel=$('#today');if(!todayPanel||$('#phase3Adaptive'))return;const coach=$('#mybodyCoachCard');const card=document.createElement('section');card.id='phase3Adaptive';card.className='card p3-adaptive';(coach||todayPanel.querySelector('.section-head'))?.insertAdjacentElement('afterend',card)}
function renderAdaptive(){ensureAdaptive();const card=$('#phase3Adaptive');if(!card)return;const rec=recommendation(),a=adherence(),w=weightTrend(),cardio=cardioWeek(),min=!!phase().minimumDays?.[today()],deload=!!phase().deloadActive;card.innerHTML=`<div class="p3-head"><div><span>Adaptive coach</span><h3>${esc(rec.title)}</h3></div><b>${a.days>=5?'LIVE':'LEARNING'}</b></div><p>${esc(rec.body)}</p><div class="p3-mini-grid"><div><small>14-day intake</small><strong>${a.days?Math.round(a.calories):'—'}</strong><span>kcal avg</span></div><div><small>Weight trend</small><strong>${w?(w.change>0?'+':'')+w.change.toFixed(2):'—'}</strong><span>kg</span></div><div><small>Cardio</small><strong>${Math.round(cardio)}</strong><span>/ 150 min</span></div></div><div class="p3-actions">${rec.delta?`<button class="primary" data-p3="apply-cal" data-delta="${rec.delta}">${rec.delta>0?'+100':'−100'} kcal</button>`:''}${rec.action==='deload'?`<button class="secondary" data-p3="deload">${deload?'End deload':'Start lighter week'}</button>`:''}<button class="secondary" data-p3="minimum">${min?'Exit minimum day':'Busy day mode'}</button><button class="text-btn" data-p3="cardio">+ Cardio</button></div>${min?'<div class="p3-mode"><strong>Minimum Day active</strong><span>Keep protein on target • 6,000 steps floor • 20–30 min training or brisk walk</span></div>':''}${deload?'<div class="p3-mode recovery"><strong>Lighter week active</strong><span>Reduce working sets around 30–40%, avoid failure, keep technique crisp.</span></div>':''}`;
 $$('#phase3Adaptive [data-p3]').forEach(b=>b.onclick=()=>handleAction(b));
}
function handleAction(btn){const action=btn.dataset.p3,next=clone(Store.read());next.profile=next.profile||{};next.profile.phase3=next.profile.phase3||{};if(action==='apply-cal'){const delta=n(btn.dataset.delta);next.config.calories=Math.max(1200,Math.round(n(next.config.calories)+delta));next.profile.phase3.lastAdaptiveChange={date:today(),delta,calories:next.config.calories};write(next,`Calorie target updated to ${next.config.calories}`);return}if(action==='minimum'){next.profile.phase3.minimumDays=next.profile.phase3.minimumDays||{};if(next.profile.phase3.minimumDays[today()])delete next.profile.phase3.minimumDays[today()];else next.profile.phase3.minimumDays[today()]=true;write(next,'Minimum Day updated');return}if(action==='deload'){next.profile.phase3.deloadActive=!next.profile.phase3.deloadActive;next.profile.phase3.deloadStarted=next.profile.phase3.deloadActive?today():null;write(next,next.profile.phase3.deloadActive?'Lighter week started':'Lighter week ended');return}if(action==='cardio')openCardio()}
function openCardio(){let m=$('#phase3CardioModal');if(!m){m=document.createElement('div');m.id='phase3CardioModal';m.className='p3-modal hidden';document.body.appendChild(m)}m.innerHTML='<div class="p3-modal-panel"><header><div><h2>Log cardio</h2><p>Count purposeful aerobic activity. Keep this separate from strength training.</p></div><button type="button" class="p3-close">×</button></header><div class="p3-cardio-options"><button data-min="15">15 min</button><button data-min="30">30 min</button><button data-min="45">45 min</button><button data-min="60">60 min</button></div><label>Custom minutes<input id="p3CardioCustom" type="number" min="1" max="300" inputmode="numeric" placeholder="e.g. 25"></label><button id="p3SaveCardio" class="primary full" type="button">Save cardio</button></div>';m.classList.remove('hidden');document.body.classList.add('modal-open');$('.p3-close',m).onclick=()=>closeModal(m);let selected=0;$$('[data-min]',m).forEach(b=>b.onclick=()=>{selected=n(b.dataset.min);$$('[data-min]',m).forEach(x=>x.classList.toggle('active',x===b))});$('#p3SaveCardio',m).onclick=()=>{const mins=n($('#p3CardioCustom',m).value,selected);if(!mins)return;const next=clone(Store.read());next.profile=next.profile||{};next.profile.phase3=next.profile.phase3||{};next.profile.phase3.cardio=next.profile.phase3.cardio||{};next.profile.phase3.cardio[today()]=n(next.profile.phase3.cardio[today()])+mins;write(next,`${mins} min cardio logged`);closeModal(m)}}
function closeModal(m){m.classList.add('hidden');if(!document.querySelector('.p3-modal:not(.hidden),.coach-modal:not(.hidden),.sheet-backdrop:not(.hidden)'))document.body.classList.remove('modal-open')}
function mealProtein(){const meals=state.nutrition?.[today()]?.meals||{};return mealKeys.map(k=>({key:k,label:mealNames[k],protein:(meals[k]||[]).reduce((s,f)=>s+n(f.protein),0)}))}
function ensureProteinDistribution(){const food=$('#food'),nutrition=$('#food .nutrition-grid');if(!food||!nutrition)return;let card=$('#p3ProteinDistribution');if(!card){card=document.createElement('section');card.id='p3ProteinDistribution';card.className='card p3-protein';nutrition.insertAdjacentElement('afterend',card)}}
function renderProteinDistribution(){ensureProteinDistribution();const card=$('#p3ProteinDistribution');if(!card)return;const target=n(state.config?.protein),meals=mealProtein(),daily=meals.reduce((s,x)=>s+x.protein,0),perMeal=Math.max(20,Math.min(45,target/4));card.innerHTML=`<div class="p3-protein-head"><div><span>Protein distribution</span><strong>${Math.round(daily)} / ${Math.round(target)} g</strong></div><small>Aim for protein across the day</small></div><div class="p3-protein-rows">${meals.map(x=>{const pct=Math.min(100,x.protein/perMeal*100),ok=x.protein>=perMeal*.8;return `<div><span>${x.label}</span><i><b style="width:${pct}%"></b></i><strong class="${ok?'ok':''}">${Math.round(x.protein)}g</strong></div>`}).join('')}</div>`}
function applyMinimumDayVisual(){const min=!!phase().minimumDays?.[today()];const node=$('#today');if(node)node.classList.toggle('p3-minimum-day',min);if(min){const score=$('#scoreSteps');if(score){const actual=String(score.textContent).split('/')[0].trim();score.textContent=`${actual} / 6000`}}}
function renderAll(){state=Store.read();renderAdaptive();renderProteinDistribution();applyMinimumDayVisual()}
function wire(){window.addEventListener('mybody:state',()=>setTimeout(renderAll,80));document.addEventListener('click',e=>{if(e.target.closest('[data-nav],.tab,[data-action="save-food"],#saveDaily,#saveWorkout'))setTimeout(renderAll,120)},true);document.addEventListener('input',e=>{if(e.target.closest('#food,#today'))setTimeout(renderAll,140)},true)}
document.addEventListener('DOMContentLoaded',()=>{renderAll();wire();setTimeout(renderAll,240)});if(document.readyState!=='loading'){renderAll();wire();setTimeout(renderAll,240)}
})();