(function(){
'use strict';
const Store=window.MyBodyStore;
if(!Store)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const clone=Store.clone;
let state=Store.read();
const mealKeys=['breakfast','lunch','eveningSnacks','dinner'];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function avg(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}
function today(date=new Date()){return Store.localDate(date)}
function dateBack(days){const d=new Date();d.setDate(d.getDate()-days);return today(d)}
function mondayKey(date=new Date()){const d=new Date(date);const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return today(d)}
function toast(m){const el=$('#appToast');if(!el)return;el.textContent=m;el.dataset.type='success';el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
function write(next,msg){const r=Store.write(next);state=r.state;if(msg)toast(msg);setTimeout(renderAll,70);return r.ok}
function nutrition(date){const meals=state.nutrition?.[date]?.meals||{};let calories=0,protein=0;mealKeys.forEach(k=>(meals[k]||[]).forEach(f=>{calories+=n(f.calories);protein+=n(f.protein)}));return{calories,protein}}
function activity(date){const x=state.activity?.[date]||{};return{steps:n(x.steps),water:n(x.water)}}
function latestWeights(){return (state.weights||[]).filter(x=>x.date&&n(x.weight)>0).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
function weightTrend(){const w=latestWeights();if(w.length<4)return null;const a=w.slice(0,Math.min(7,w.length));const b=w.slice(a.length,a.length+7);if(!b.length)return null;const current=avg(a.map(x=>n(x.weight))),previous=avg(b.map(x=>n(x.weight))),change=current-previous;return{current,previous,change,pct:previous?change/previous*100:0,points:w.length}}
function waistTrend(){const rows=(state.abdomen||[]).filter(x=>x.date&&(n(x.value)>0||n(x.inches)>0)).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)));if(!rows.length)return null;const val=x=>n(x.value)||(n(x.inches)*2.54);const recent=rows.slice(0,Math.min(3,rows.length));const prev=rows.slice(recent.length,recent.length+3);return{current:avg(recent.map(val)),change:prev.length?avg(recent.map(val))-avg(prev.map(val)):null}}
function readiness(){const r=state.profile?.coach?.readiness||{},vals=Object.keys(r).sort().reverse().slice(0,7).map(k=>n(r[k]?.score)).filter(Boolean);return vals.length?avg(vals):0}
function weeklyStats(){let cal=[],protein=[],steps=[],workouts=0;for(let i=0;i<7;i++){const d=dateBack(i),nu=nutrition(d),ac=activity(d);if(nu.calories>0){cal.push(nu.calories);protein.push(nu.protein)}if(ac.steps>0)steps.push(ac.steps);if(state.workoutLog?.[d]&&Object.keys(state.workoutLog[d]).length)workouts++}const c=n(state.config?.calories),p=n(state.config?.protein),s=n(state.config?.steps);return{calories:avg(cal),protein:avg(protein),steps:avg(steps),workouts,loggedDays:cal.length,calorieAdherence:cal.length&&c?avg(cal.map(x=>Math.max(0,1-Math.abs(x-c)/c))):0,proteinAdherence:protein.length&&p?avg(protein.map(x=>Math.min(1,x/p))):0,stepAdherence:steps.length&&s?Math.min(1,avg(steps)/s):0,readiness:readiness(),weight:weightTrend(),waist:waistTrend()}}
function currentCheckin(){return state.profile?.phase4?.checkins?.[mondayKey()]||null}
function decision(stats,subjective=currentCheckin()){const goal=state.profile?.coach?.plan?.profile?.goal||'general',hunger=n(subjective?.hunger,3),energy=n(subjective?.energy,3),performance=subjective?.performance||'same';if((stats.readiness&&stats.readiness<58)||(energy<=2&&performance==='worse'))return{type:'recovery',title:'Recovery week',body:'Recovery signals are low. Keep technique work, reduce hard sets and avoid training to failure for several days.',action:'recovery'};if(stats.loggedDays<4||!stats.weight)return{type:'learn',title:'Keep collecting data',body:'Log food, body weight and workouts consistently so MYBODY can make a reliable weekly decision.'};if(stats.proteinAdherence<.8)return{type:'protein',title:'Fix protein consistency',body:'Protein consistency is the main limiter this week. Keep calories unchanged and improve protein distribution first.'};if(stats.stepAdherence<.72&&goal==='fat_loss')return{type:'activity',title:'Increase daily movement',body:'Activity is below your target. Add a small step increase before reducing food further.',action:'steps',delta:500};if(goal==='fat_loss'){
 if(stats.weight.pct<-1&&hunger>=4)return{type:'calories',title:'Slow the loss slightly',body:'Weight is falling quickly and hunger is elevated. A small calorie increase is the safer next test.',action:'calories',delta:100};
 if(stats.weight.pct>-.18&&stats.calorieAdherence>.72&&hunger<=4)return{type:'calories',title:'Small calorie adjustment',body:'Your weight trend is moving slowly despite reasonable adherence. Reduce calories slightly and reassess next week.',action:'calories',delta:-100};
}
if(goal==='muscle_gain'&&stats.weight.pct<.05&&stats.calorieAdherence>.72)return{type:'calories',title:'Support muscle gain',body:'Scale trend is flat. A small calorie increase is reasonable if training performance and recovery are stable.',action:'calories',delta:100};
return{type:'steady',title:'Keep the plan',body:'Your current trend does not justify changing targets. Keep the same plan for another week.'}}
function ensureWeeklyCard(){const progress=$('#progress');if(!progress)return null;let card=$('#p4WeeklyCard');if(!card){card=document.createElement('section');card.id='p4WeeklyCard';card.className='card p4-weekly';const stats=$('#progress .stats-grid');(stats||progress.querySelector('.section-head'))?.insertAdjacentElement('afterend',card)}return card}
function renderWeekly(){const card=ensureWeeklyCard();if(!card)return;const s=weeklyStats(),check=currentCheckin(),d=decision(s,check);card.innerHTML=`<div class="p4-head"><div><span>Weekly check-in</span><h3>${esc(d.title)}</h3></div><button type="button" class="secondary" data-p4="checkin">${check?'Update':'Check in'}</button></div><p>${esc(d.body)}</p><div class="p4-week-grid"><div><small>Calories</small><strong>${s.loggedDays?Math.round(s.calories):'—'}</strong><span>${Math.round(s.calorieAdherence*100)}% adherence</span></div><div><small>Protein</small><strong>${s.loggedDays?Math.round(s.protein)+'g':'—'}</strong><span>${Math.round(s.proteinAdherence*100)}% target</span></div><div><small>Steps</small><strong>${s.steps?Math.round(s.steps).toLocaleString():'—'}</strong><span>${Math.round(s.stepAdherence*100)}% target</span></div><div><small>Readiness</small><strong>${s.readiness?Math.round(s.readiness):'—'}</strong><span>/100 average</span></div></div>${d.action?`<button class="p4-decision" type="button" data-p4="accept" data-action="${d.action}" data-delta="${d.delta||0}">Apply recommendation</button>`:''}`;wireButtons(card)}
function openCheckin(){let m=$('#p4CheckinModal');if(!m){m=document.createElement('div');m.id='p4CheckinModal';m.className='p4-modal hidden';document.body.appendChild(m)}const c=currentCheckin()||{};m.innerHTML=`<div class="p4-modal-panel"><header><div><h2>Weekly check-in</h2><p>Three quick questions help MYBODY interpret your numbers.</p></div><button class="p4-close" type="button">×</button></header><div class="p4-question"><span>Hunger</span><div>${[1,2,3,4,5].map(x=>`<button type="button" data-q="hunger" data-v="${x}" class="${n(c.hunger)===x?'active':''}">${x}</button>`).join('')}</div><small>1 low · 5 very high</small></div><div class="p4-question"><span>Energy</span><div>${[1,2,3,4,5].map(x=>`<button type="button" data-q="energy" data-v="${x}" class="${n(c.energy)===x?'active':''}">${x}</button>`).join('')}</div><small>1 low · 5 excellent</small></div><div class="p4-question"><span>Training performance</span><div class="p4-performance"><button type="button" data-q="performance" data-v="improving" class="${c.performance==='improving'?'active':''}">Improving</button><button type="button" data-q="performance" data-v="same" class="${!c.performance||c.performance==='same'?'active':''}">Same</button><button type="button" data-q="performance" data-v="worse" class="${c.performance==='worse'?'active':''}">Worse</button></div></div><button class="primary full" type="button" data-p4="save-checkin">Save weekly check-in</button></div>`;m.classList.remove('hidden');document.body.classList.add('modal-open');$('.p4-close',m).onclick=()=>closeModal(m);m.onclick=e=>{if(e.target===m)closeModal(m)};$$('[data-q]',m).forEach(b=>b.onclick=()=>{const q=b.dataset.q;$$(`[data-q="${q}"]`,m).forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('[data-p4="save-checkin"]',m).onclick=()=>{const hunger=n($('[data-q="hunger"].active',m)?.dataset.v,3),energy=n($('[data-q="energy"].active',m)?.dataset.v,3),performance=$('[data-q="performance"].active',m)?.dataset.v||'same';const next=clone(Store.read());next.profile=next.profile||{};next.profile.phase4=next.profile.phase4||{};next.profile.phase4.checkins=next.profile.phase4.checkins||{};next.profile.phase4.checkins[mondayKey()]={date:today(),hunger,energy,performance};write(next,'Weekly check-in saved');closeModal(m)}}
function closeModal(m){m.classList.add('hidden');if(!document.querySelector('.p4-modal:not(.hidden),.p3-modal:not(.hidden),.coach-modal:not(.hidden),.sheet-backdrop:not(.hidden)'))document.body.classList.remove('modal-open')}
function acceptDecision(btn){const s=weeklyStats(),d=decision(s,currentCheckin()),next=clone(Store.read());next.profile=next.profile||{};next.profile.phase4=next.profile.phase4||{};if(d.action==='calories'){next.config.calories=Math.max(1200,Math.round(n(next.config.calories)+n(d.delta)));next.profile.phase4.lastDecision={date:today(),type:'calories',delta:n(d.delta)}}else if(d.action==='steps'){next.config.steps=Math.min(30000,Math.round(n(next.config.steps)+n(d.delta,500)));next.profile.phase4.lastDecision={date:today(),type:'steps',delta:n(d.delta,500)}}else if(d.action==='recovery'){next.profile.phase3=next.profile.phase3||{};next.profile.phase3.deloadActive=true;next.profile.phase3.deloadStarted=today();next.profile.phase4.lastDecision={date:today(),type:'recovery'}}write(next,'Weekly recommendation applied')}
function setRecords(){const rec=new Map();const dates=Object.keys(state.workoutLog||{}).sort();for(const date of dates){for(const [dayKey,log] of Object.entries(state.workoutLog?.[date]||{})){const day=n(dayKey),plan=state.workouts?.[day];(log.exercises||[]).forEach((ex,i)=>{const name=plan?.exercises?.[i]?.[0]||`Exercise ${i+1}`;const sets=(ex.setsDetail||[]).filter(s=>n(s.actualWeight)>0&&n(s.actualReps)>0);sets.forEach(s=>{const weight=n(s.actualWeight),reps=n(s.actualReps),e1rm=reps<=15?weight*(1+reps/30):weight;const r=rec.get(name)||{name,first:e1rm,best:0,bestWeight:0,bestReps:0,last:e1rm,date};if(e1rm>r.best){r.best=e1rm;r.bestWeight=weight;r.bestReps=reps;r.date=date}r.last=e1rm;rec.set(name,r)})})}}return Array.from(rec.values()).map(r=>({...r,change:r.first?((r.best-r.first)/r.first*100):0})).sort((a,b)=>b.best-a.best)}
function ensureStrength(){const progress=$('#progress');if(!progress)return null;let card=$('#p4Strength');if(!card){card=document.createElement('section');card.id='p4Strength';card.className='card p4-strength';const chart=$('#progress .chart-card');(chart||$('#p4WeeklyCard')||progress.querySelector('.stats-grid'))?.insertAdjacentElement('afterend',card)}return card}
function renderStrength(){const card=ensureStrength();if(!card)return;const rows=setRecords(),top=rows.slice(0,4);card.innerHTML=`<div class="p4-head"><div><span>Strength & PRs</span><h3>${rows.length?'Your strongest lifts':'Start building records'}</h3></div>${rows.length>4?'<button type="button" class="text-btn" data-p4="records">View all</button>':''}</div>${top.length?`<div class="p4-pr-list">${top.map((r,i)=>`<article><b>${i+1}</b><div><strong>${esc(r.name)}</strong><span>Best set ${r.bestWeight} kg × ${r.bestReps}</span></div><div><strong>${Math.round(r.best)} kg</strong><span>est. 1RM${r.change>0?` · +${Math.round(r.change)}%`:''}</span></div></article>`).join('')}</div>`:'<p class="p4-empty">Complete working sets with actual weight and reps. MYBODY will automatically detect personal records.</p>'}`;wireButtons(card)}
function openRecords(){const rows=setRecords();let m=$('#p4RecordsModal');if(!m){m=document.createElement('div');m.id='p4RecordsModal';m.className='p4-modal hidden';document.body.appendChild(m)}m.innerHTML=`<div class="p4-modal-panel p4-record-panel"><header><div><h2>Strength records</h2><p>Estimated 1RM uses logged working sets and is a training estimate, not a maximal-test prescription.</p></div><button class="p4-close" type="button">×</button></header><div class="p4-records">${rows.map(r=>`<article><div><strong>${esc(r.name)}</strong><span>${r.bestWeight} kg × ${r.bestReps}</span></div><div><strong>${Math.round(r.best)} kg</strong><span>est. 1RM</span></div></article>`).join('')}</div></div>`;m.classList.remove('hidden');document.body.classList.add('modal-open');$('.p4-close',m).onclick=()=>closeModal(m);m.onclick=e=>{if(e.target===m)closeModal(m)}}
function projection(){const w=weightTrend(),goal=n(state.config?.goalWeight),plan=state.profile?.coach?.plan,goalDate=plan?.profile?.goalDate;if(!w||!goal)return{status:'learning',title:'Need more weight data',body:'Log weight regularly to estimate your goal timeline.'};const weekly=w.change,remaining=goal-w.current,toward=(remaining<0&&weekly<0)||(remaining>0&&weekly>0);if(!toward||Math.abs(weekly)<.03)return{status:'flat',title:'No reliable projection yet',body:'Your recent weight trend is too flat or moving away from the target.'};const weeks=Math.abs(remaining/weekly);if(!Number.isFinite(weeks)||weeks>104)return{status:'flat',title:'Need a clearer trend',body:'Continue logging before using a long-range projection.'};const d=new Date();d.setDate(d.getDate()+Math.round(weeks*7));let badge='Current pace';if(goalDate){const target=new Date(goalDate+'T12:00:00');const diff=(d-target)/86400000;badge=diff<-7?'Ahead':diff>7?'Behind':'On track'}return{status:'ok',title:d.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}),body:`Current trend ${weekly>0?'+':''}${weekly.toFixed(2)} kg/week · ${Math.abs(remaining).toFixed(1)} kg remaining`,badge,date:d}}
function ensureProjection(){const progress=$('#progress');if(!progress)return null;let card=$('#p4Projection');if(!card){card=document.createElement('section');card.id='p4Projection';card.className='card p4-projection';const stats=$('#progress .stats-grid');(stats||progress.querySelector('.section-head'))?.insertAdjacentElement('afterend',card)}return card}
function renderProjection(){const card=ensureProjection();if(!card)return;const p=projection(),w=weightTrend(),goal=n(state.config?.goalWeight);card.innerHTML=`<div class="p4-proj-icon">↗</div><div><span>Goal projection</span><strong>${esc(p.title)}</strong><p>${esc(p.body)}</p></div><div class="p4-proj-side"><b>${esc(p.badge||'Learning')}</b><span>${w?`${w.current.toFixed(1)} → ${goal.toFixed(1)} kg`:'Add weights'}</span></div>`}
function reminderConfig(){return state.profile?.phase4?.notifications||{enabled:false,protein:true,steps:true,workout:true,weekly:true}}
function ensureReminderSettings(){const settings=$('#settings');if(!settings)return null;let card=$('#p4ReminderSettings');if(!card){card=document.createElement('section');card.id='p4ReminderSettings';card.className='card p4-reminders';const head=settings.querySelector('.section-head');head?.insertAdjacentElement('afterend',card)}return card}
function renderReminderSettings(){const card=ensureReminderSettings();if(!card)return;const c=reminderConfig(),supported='Notification'in window;const permission=supported?Notification.permission:'unsupported';card.innerHTML=`<div class="p4-head"><div><span>Smart reminders</span><h3>Only when useful</h3></div><b class="p4-permission">${permission==='granted'?'ON':permission==='denied'?'BLOCKED':'OFF'}</b></div><p>MYBODY can remind you about protein, steps, workouts and the weekly review. Browser notifications require permission and work best in the installed PWA.</p><div class="p4-toggle-grid">${[['protein','Protein'],['steps','Steps'],['workout','Workout'],['weekly','Weekly review']].map(([k,label])=>`<label><input type="checkbox" data-reminder="${k}" ${c[k]!==false?'checked':''}><span>${label}</span></label>`).join('')}</div><button type="button" class="secondary full" data-p4="notifications">${permission==='granted'?(c.enabled?'Pause notifications':'Enable reminders'):'Enable notifications'}</button>`;wireButtons(card);$$('[data-reminder]',card).forEach(x=>x.onchange=()=>saveReminderPrefs())}
function saveReminderPrefs(){const next=clone(Store.read());next.profile=next.profile||{};next.profile.phase4=next.profile.phase4||{};const old=next.profile.phase4.notifications||{};next.profile.phase4.notifications={...old,protein:$('[data-reminder="protein"]')?.checked!==false,steps:$('[data-reminder="steps"]')?.checked!==false,workout:$('[data-reminder="workout"]')?.checked!==false,weekly:$('[data-reminder="weekly"]')?.checked!==false};write(next)}
async function toggleNotifications(){if(!('Notification'in window)){toast('Notifications are not supported on this browser');return}let permission=Notification.permission;if(permission==='default')permission=await Notification.requestPermission();if(permission!=='granted'){toast('Notification permission was not enabled');renderReminderSettings();return}const next=clone(Store.read());next.profile=next.profile||{};next.profile.phase4=next.profile.phase4||{};next.profile.phase4.notifications={...reminderConfig(),enabled:!reminderConfig().enabled};write(next,next.profile.phase4.notifications.enabled?'Smart reminders enabled':'Smart reminders paused');if(next.profile.phase4.notifications.enabled)checkReminders(true)}
function loggedWorkoutToday(){return !!(state.workoutLog?.[today()]&&Object.keys(state.workoutLog[today()]).length)}
function dueReminder(){const c=reminderConfig();if(!c.enabled)return null;const hour=new Date().getHours(),nu=nutrition(today()),ac=activity(today()),proteinTarget=n(state.config?.protein),stepsTarget=n(state.config?.steps);if(c.weekly&&new Date().getDay()===0&&hour>=17&&!currentCheckin())return{type:'weekly',title:'Your weekly review is ready',body:'Take 30 seconds to check hunger, energy and training performance.'};if(c.workout&&hour>=17&&!loggedWorkoutToday())return{type:'workout',title:'Workout still open',body:`${state.workouts?.[(new Date().getDay()+6)%7]?.name||'Your workout'} is waiting when you are ready.`};if(c.protein&&hour>=19&&proteinTarget&&nu.protein<proteinTarget*.8)return{type:'protein',title:'Protein is behind target',body:`${Math.max(0,Math.round(proteinTarget-nu.protein))} g remaining today.`};if(c.steps&&hour>=18&&stepsTarget&&ac.steps<stepsTarget*.75)return{type:'steps',title:'Steps are behind target',body:`${Math.max(0,Math.round(stepsTarget-ac.steps)).toLocaleString()} steps remaining today.`};return null}
async function checkReminders(force=false){state=Store.read();const r=dueReminder();renderNextAction(r);if(!r||!('Notification'in window)||Notification.permission!=='granted')return;const key=`p4:${r.type}:${today()}`,last=localStorage.getItem(key);if(last&&!force)return;try{const reg=await navigator.serviceWorker?.ready;if(reg?.showNotification){await reg.showNotification(r.title,{body:r.body,icon:'icons/icon-192.png',badge:'icons/icon-192.png',tag:`mybody-${r.type}`,data:{url:'./'}});localStorage.setItem(key,String(Date.now()))}}catch(_){}}
function renderNextAction(reminder=dueReminder()){const todayPanel=$('#today');if(!todayPanel)return;let card=$('#p4NextAction');if(!reminder){card?.remove();return}if(!card){card=document.createElement('section');card.id='p4NextAction';card.className='p4-next';const workout=$('#today .today-workout-card');(workout||$('#phase3Adaptive')||$('#mybodyCoachCard'))?.insertAdjacentElement('afterend',card)}card.innerHTML=`<div><span>Next best action</span><strong>${esc(reminder.title)}</strong><small>${esc(reminder.body)}</small></div><button type="button" aria-label="Dismiss reminder">×</button>`;$('button',card).onclick=()=>card.remove()}
function wireButtons(root=document){$$('[data-p4]',root).forEach(btn=>{if(btn.dataset.p4Bound)return;btn.dataset.p4Bound='1';btn.addEventListener('click',()=>{const a=btn.dataset.p4;if(a==='checkin')openCheckin();if(a==='accept')acceptDecision(btn);if(a==='records')openRecords();if(a==='notifications')toggleNotifications()})})}
function renderAll(){state=Store.read();renderProjection();renderWeekly();renderStrength();renderReminderSettings();renderNextAction();wireButtons()}
function wire(){window.addEventListener('mybody:state',()=>setTimeout(renderAll,90));document.addEventListener('click',e=>{if(e.target.closest('[data-nav],.tab,#saveDaily,#saveWorkout,[data-action="save-food"],[data-action="save-exercise-detail"]'))setTimeout(renderAll,150)},true);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){state=Store.read();renderAll();checkReminders()}});setInterval(()=>checkReminders(),15*60*1000)}
document.addEventListener('DOMContentLoaded',()=>{renderAll();wire();setTimeout(()=>checkReminders(),600)});if(document.readyState!=='loading'){renderAll();wire();setTimeout(()=>checkReminders(),600)}
})();