(function(){
'use strict';
const Store=window.MyBodyStore,Library=window.MyBodyExerciseLibrary;
if(!Store||!Library)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=Store.clone;
let state=Store.read(),restEnd=0,restTimer=null;
const PHOTO_KEY=()=>`mybody.progressPhotos.v1.${localStorage.getItem(Store.SESSION_KEY)||'guest'}`;
const mealKeys=['breakfast','lunch','eveningSnacks','dinner'];
const mealLabel={breakfast:'Breakfast',lunch:'Lunch',eveningSnacks:'Snacks',dinner:'Dinner'};
function toast(m){const n=$('#appToast');if(!n)return;n.textContent=m;n.dataset.type='success';n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2200)}
function write(next,msg){const r=Store.write(next);state=r.state;if(msg)toast(msg);setTimeout(renderAll,40);return r.ok}
function dayIndex(){return Number($('.day-btn.active')?.dataset.day||0)}
function exerciseIndexFromTitle(){const name=$('#exerciseDetailTitle')?.textContent||'';return state.workouts?.[dayIndex()]?.exercises?.findIndex(x=>x[0]===name)??-1}
function currentMeal(){const h=new Date().getHours();return h<11?'breakfast':h<16?'lunch':h<19?'eveningSnacks':'dinner'}
function ensureMeals(next,date=Store.localDate()){next.nutrition[date]=next.nutrition[date]||{};next.nutrition[date].meals=next.nutrition[date].meals||{};mealKeys.forEach(k=>{if(!Array.isArray(next.nutrition[date].meals[k]))next.nutrition[date].meals[k]=[]});return next.nutrition[date].meals}
function isCompound(name){return /bench|press|squat|deadlift|row|pulldown|pull-up|dip|leg press|hack squat|ohp/i.test(name||'')}
function restSeconds(name){return isCompound(name)?150:/calf|lunge|split squat/i.test(name||'')?105:75}
function ensureRestTimer(){if($('#phase2RestTimer'))return;const el=document.createElement('div');el.id='phase2RestTimer';el.className='p2-rest hidden';el.innerHTML='<button class="p2-rest-main" type="button"><small>REST</small><strong>2:30</strong><span>Next set</span></button><button data-rest="plus" type="button">+30</button><button data-rest="skip" type="button">Skip</button>';document.body.appendChild(el);el.addEventListener('click',e=>{const a=e.target.closest('[data-rest]')?.dataset.rest;if(a==='plus'){restEnd+=30000;tickRest()}if(a==='skip')stopRest()})}
function startRest(seconds){ensureRestTimer();restEnd=Date.now()+seconds*1000;clearInterval(restTimer);restTimer=setInterval(tickRest,250);tickRest();if(navigator.vibrate)navigator.vibrate(40)}
function tickRest(){const el=$('#phase2RestTimer');if(!el)return;const left=Math.max(0,Math.ceil((restEnd-Date.now())/1000));el.classList.toggle('hidden',left<=0);const s=$('.p2-rest-main strong',el);if(s)s.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;if(left<=0){clearInterval(restTimer);if(navigator.vibrate)navigator.vibrate([120,80,120])}}
function stopRest(){restEnd=0;clearInterval(restTimer);$('#phase2RestTimer')?.classList.add('hidden')}
function roundLoad(v){return Math.max(0,Math.round(v/2.5)*2.5)}
function warmups(name,working){if(!working||!isCompound(name))return ['5 min easy movement','1–2 light practice sets'];return [`${roundLoad(working*.4)} kg × 8`,`${roundLoad(working*.6)} kg × 5`,`${roundLoad(working*.8)} kg × 2`].filter((x,i,a)=>a.indexOf(x)===i)}
function previousResult(day,index){const dates=Object.keys(state.workoutLog||{}).filter(d=>d<Store.localDate()).sort().reverse();for(const d of dates){const r=state.workoutLog?.[d]?.[day]?.exercises?.[index];if(r)return r}return null}
function progression(previous){if(!previous)return 'First logged session: focus on clean technique and leave a little in reserve.';const sets=previous.setsDetail||[];if(!sets.length)return 'Repeat the last load and aim to complete every target rep.';const hit=sets.every(s=>s.done&&Number(s.actualReps||0)>=Number(s.targetReps||0));const efforts=sets.map(s=>s.effort).filter(Boolean);const maxed=efforts.includes('max'),hard=efforts.includes('hard');if(hit&&!maxed&&!hard)return 'All targets looked controlled. A small load increase next time is reasonable.';if(hit&&(hard||maxed))return 'You hit the reps, but the set was hard. Keep the same load next time.';return 'Some target reps were missed. Keep the same load and try to beat this performance before increasing.'}
function enhanceExerciseDetail(){const sheet=$('#exerciseDetailSheet');if(!sheet||sheet.classList.contains('hidden'))return;const name=$('#exerciseDetailTitle')?.textContent||'';const day=dayIndex(),idx=exerciseIndexFromTitle();if(idx<0)return;const rows=$$('#exerciseSetRows .exercise-set-row');if(!rows.length)return;let guide=$('#phase2WorkoutGuide',sheet);if(!guide){guide=document.createElement('section');guide.id='phase2WorkoutGuide';guide.className='p2-workout-guide';const table=$('.exercise-set-table',sheet);table?.insertAdjacentElement('beforebegin',guide)}const target=Number($('span',rows[0])?.textContent)||0;const prev=previousResult(day,idx);guide.innerHTML=`<div><span>Warm-up</span><strong>${warmups(name,target).map(esc).join(' • ')}</strong></div><div><span>Next-time guidance</span><strong>${esc(progression(prev))}</strong></div><p>After each working set, choose how it felt. MYBODY uses this with your completed reps to guide progression.</p>`;rows.forEach((row,i)=>{let box=$('.p2-effort',row);if(!box){box=document.createElement('div');box.className='p2-effort';box.innerHTML='<span>How hard was this set?</span><div><button type="button" data-effort="easy">Easy</button><button type="button" data-effort="good">Good</button><button type="button" data-effort="hard">Hard</button><button type="button" data-effort="max">Max</button></div>';row.appendChild(box);box.addEventListener('click',e=>{const b=e.target.closest('[data-effort]');if(!b)return;$$('[data-effort]',box).forEach(x=>x.classList.toggle('active',x===b))})}const saved=state.workoutLog?.[Store.localDate()]?.[day]?.exercises?.[idx]?.setsDetail?.[i]?.effort;if(saved){const b=$(`[data-effort="${saved}"]`,box);if(b)b.classList.add('active')}})}
function persistEffortAfterNativeSave(){setTimeout(()=>{state=Store.read();const day=dayIndex(),idx=exerciseIndexFromTitle();if(idx<0)return;const rows=$$('#exerciseSetRows .exercise-set-row');const ex=state.workoutLog?.[Store.localDate()]?.[day]?.exercises?.[idx];if(!ex?.setsDetail)return;const next=clone(state);const target=next.workoutLog[Store.localDate()][day].exercises[idx];target.setsDetail=target.setsDetail.map((s,i)=>{const effort=$('.p2-effort [data-effort].active',rows[i])?.dataset.effort||s.effort||'';return {...s,effort,effortScale:({easy:4,good:2,hard:1,max:0})[effort]??null}});write(next,'Exercise saved with effort')},100)}
function enhanceExerciseCards(){const day=dayIndex();$$('#exerciseList .exercise').forEach((card,index)=>{if($('.p2-swap',card))return;const actions=$('.entry-confirm',card)||$('.exercise-main',card);const b=document.createElement('button');b.type='button';b.className='text-btn p2-swap';b.textContent='Swap exercise';b.dataset.swapIndex=index;b.addEventListener('click',()=>openSwap(day,index));actions?.appendChild(b)})}
function modal(id,title){let m=document.getElementById(id);if(!m){m=document.createElement('div');m.id=id;m.className='p2-modal hidden';document.body.appendChild(m)}m.innerHTML=`<div class="p2-modal-panel"><header><div><h2>${esc(title)}</h2></div><button type="button" class="p2-close">×</button></header><div class="p2-modal-body"></div></div>`;$('.p2-close',m).onclick=()=>closeModal(m);m.onclick=e=>{if(e.target===m)closeModal(m)};m.classList.remove('hidden');document.body.classList.add('modal-open');return m}
function closeModal(m){m.classList.add('hidden');if(!document.querySelector('.p2-modal:not(.hidden),.coach-modal:not(.hidden),.sheet-backdrop:not(.hidden)'))document.body.classList.remove('modal-open')}
function openSwap(day,index){state=Store.read();const current=state.workouts?.[day]?.exercises?.[index];if(!current)return;const base=Library.find(current[0]);const same=Library.exercises.filter(x=>x.id!==base.id&&(x.muscle===base.muscle||x.category===base.category)).slice(0,8);const m=modal('phase2SwapModal','Choose an alternative');$('.p2-modal-body',m).innerHTML=`<p class="p2-muted">MYBODY keeps the same sets and rep target while changing the exercise.</p><div class="p2-choice-list">${same.map(x=>`<button type="button" data-name="${esc(x.name)}"><b>${esc(x.name)}</b><span>${esc(x.equipment)} • ${esc(x.category)}</span></button>`).join('')}</div>`;$$('[data-name]',m).forEach(b=>b.onclick=()=>{const next=clone(Store.read());next.workouts[day].exercises[index][0]=b.dataset.name;write(next,'Exercise swapped');closeModal(m)})}
function recentFoods(){const dates=Object.keys(state.nutrition||{}).sort().reverse().slice(0,14),seen=new Map();for(const d of dates){const meals=state.nutrition[d]?.meals||{};for(const k of mealKeys){for(const f of meals[k]||[]){const key=String(f.name||'').toLowerCase();if(key&&!seen.has(key))seen.set(key,clone(f))}}}return Array.from(seen.values()).slice(0,16)}
function foodTools(){const host=$('#food');const anchor=$('#mealSections');if(!host||!anchor||$('#phase2FoodTools'))return;const bar=document.createElement('section');bar.id='phase2FoodTools';bar.className='p2-food-tools';bar.innerHTML='<button type="button" data-food-tool="recent">Recent foods</button><button type="button" data-food-tool="saved">Saved meals</button><button type="button" data-food-tool="copy">Copy yesterday</button><button type="button" data-food-tool="save">Save meal</button>';anchor.before(bar);bar.addEventListener('click',e=>{const a=e.target.closest('[data-food-tool]')?.dataset.foodTool;if(a==='recent')openRecent();if(a==='saved')openSavedMeals();if(a==='copy')copyYesterday();if(a==='save')saveMealTemplate()})}
function addFood(food,meal=currentMeal()){const next=clone(Store.read()),meals=ensureMeals(next);meals[meal].push({...clone(food),savedAt:new Date().toISOString()});write(next,`${food.name||'Food'} added to ${mealLabel[meal]}`)}
function openRecent(){state=Store.read();const items=recentFoods(),m=modal('phase2RecentModal','Recent foods');$('.p2-modal-body',m).innerHTML=`<div class="p2-choice-list">${items.length?items.map((f,i)=>`<button type="button" data-recent="${i}"><b>${esc(f.name||'Food')}</b><span>${Math.round(Number(f.calories)||0)} kcal • ${Math.round(Number(f.protein)||0)}g protein</span></button>`).join(''):'<p>No recent foods yet.</p>'}</div><p class="p2-muted">Added to ${mealLabel[currentMeal()]} based on the current time.</p>`;$$('[data-recent]',m).forEach(b=>b.onclick=()=>{addFood(items[Number(b.dataset.recent)]);closeModal(m)})}
function yesterdayKey(){const d=new Date();d.setDate(d.getDate()-1);return Store.localDate(d)}
function copyYesterday(){const y=Store.read().nutrition?.[yesterdayKey()]?.meals;if(!y){toast('No meals logged yesterday');return}const next=clone(Store.read()),today=ensureMeals(next);mealKeys.forEach(k=>{today[k]=(y[k]||[]).map(clone)});write(next,'Yesterday’s meals copied')}
function templates(){return state.profile?.phase2?.mealTemplates||[]}
function saveMealTemplate(){state=Store.read();const meal=prompt('Which meal? Type breakfast, lunch, snacks or dinner',mealLabel[currentMeal()]);if(!meal)return;const key=String(meal).toLowerCase().startsWith('break')?'breakfast':String(meal).toLowerCase().startsWith('lunch')?'lunch':String(meal).toLowerCase().startsWith('snack')?'eveningSnacks':'dinner';const foods=state.nutrition?.[Store.localDate()]?.meals?.[key]||[];if(!foods.length){toast(`No foods in ${mealLabel[key]} to save`);return}const name=prompt('Name this saved meal',`My ${mealLabel[key]}`);if(!name)return;const next=clone(state);next.profile=next.profile||{};next.profile.phase2=next.profile.phase2||{};const arr=next.profile.phase2.mealTemplates||[];arr.unshift({id:Date.now(),name,key,foods:clone(foods)});next.profile.phase2.mealTemplates=arr.slice(0,20);write(next,'Meal saved')}
function openSavedMeals(){state=Store.read();const arr=templates(),m=modal('phase2SavedMeals','Saved meals');$('.p2-modal-body',m).innerHTML=`<div class="p2-choice-list">${arr.length?arr.map((t,i)=>`<button type="button" data-template="${i}"><b>${esc(t.name)}</b><span>${esc(mealLabel[t.key]||t.key)} • ${t.foods.length} items</span></button>`).join(''):'<p>No saved meals yet. Log a meal and tap “Save meal”.</p>'}</div>`;$$('[data-template]',m).forEach(b=>b.onclick=()=>{const t=arr[Number(b.dataset.template)],next=clone(Store.read()),meals=ensureMeals(next);meals[t.key].push(...t.foods.map(clone));write(next,`${t.name} added`);closeModal(m)})}
function weightTrend(){const w=(state.weights||[]).filter(x=>Number(x.weight)>0).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)));if(!w.length)return null;const latest=w.slice(0,7),prev=w.slice(7,14),avg=a=>a.reduce((s,x)=>s+Number(x.weight),0)/a.length;const a=avg(latest),p=prev.length?avg(prev):null,change=p==null?null:a-p;const goal=Number(state.config.goalWeight)||0;let projection='Need more data';if(change!=null&&Math.abs(change)>.03&&goal){const toward=(goal<a&&change<0)||(goal>a&&change>0);if(toward){const weeks=Math.abs((goal-a)/change),d=new Date();d.setDate(d.getDate()+Math.round(weeks*7));projection=d.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}}return{avg:a,change,projection}}
function strengthRows(){const map=new Map();const dates=Object.keys(state.workoutLog||{}).sort();for(const date of dates){const dayLogs=state.workoutLog[date]||{};for(const [dayKey,log] of Object.entries(dayLogs)){const day=Number(dayKey),plan=state.workouts?.[day];(log.exercises||[]).forEach((r,i)=>{const name=plan?.exercises?.[i]?.[0]||`Exercise ${i+1}`;const weights=(r.setsDetail||[]).map(s=>Number(s.actualWeight)||0).concat(Number(r.weight)||0);const max=Math.max(...weights,0);if(!max)return;const x=map.get(name)||{name,first:max,last:max};x.last=max;map.set(name,x)})}}return Array.from(map.values()).map(x=>({...x,delta:x.last-x.first})).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,4)}
function progressEnhancements(){const panel=$('#progress');if(!panel)return;const chart=$('#weightChart')?.closest('.chart-card');if(chart&&!$('#phase2TrendCard')){const t=document.createElement('section');t.id='phase2TrendCard';t.className='p2-progress-grid';t.innerHTML='<article class="card p2-trend"></article><article class="card p2-strength"></article>';chart.after(t)}const trend=weightTrend(),tc=$('.p2-trend');if(tc)tc.innerHTML=trend?`<span>7-day trend</span><strong>${trend.avg.toFixed(1)} kg</strong><small>${trend.change==null?'Add more weigh-ins':`${trend.change>0?'+':''}${trend.change.toFixed(2)} kg vs previous 7`}</small><em>Estimated goal date: ${esc(trend.projection)}</em>`:'<span>7-day trend</span><strong>—</strong><small>Add weight entries to begin</small>';const rows=strengthRows(),sc=$('.p2-strength');if(sc)sc.innerHTML=`<span>Strength trend</span><strong>${rows.length?`${rows.length} tracked lifts`:'No history yet'}</strong><div>${rows.map(r=>`<p><b>${esc(r.name)}</b><span>${r.last} kg ${r.delta?`(${r.delta>0?'+':''}${r.delta.toFixed(1)})`:''}</span></p>`).join('')}</div>`;ensurePhotoCard(panel)}
function readPhotos(){try{return JSON.parse(localStorage.getItem(PHOTO_KEY())||'[]')}catch{return[]}}
function savePhotos(x){localStorage.setItem(PHOTO_KEY(),JSON.stringify(x.slice(0,8)))}
function ensurePhotoCard(panel){if($('#phase2Photos')){renderPhotos();return}const history=$('#progress .history-block');const c=document.createElement('section');c.id='phase2Photos';c.className='card p2-photos';c.innerHTML='<div class="p2-photo-head"><div><span>Progress photos</span><strong>Compare visually</strong></div><label class="primary">Add photo<input id="phase2PhotoInput" type="file" accept="image/*" capture="environment"></label></div><p>Use similar lighting, distance and pose each time. Photos stay on this device.</p><div class="p2-photo-grid"></div>';history?.before(c);$('#phase2PhotoInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const data=await compressPhoto(f);const arr=readPhotos();arr.unshift({id:Date.now(),date:new Date().toISOString(),data});savePhotos(arr);renderPhotos();e.target.value=''}) ;renderPhotos()}
function compressPhoto(file){return new Promise((resolve,reject)=>{const img=new Image(),r=new FileReader();r.onload=()=>{img.onload=()=>{const max=640,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function renderPhotos(){const grid=$('.p2-photo-grid');if(!grid)return;const arr=readPhotos();grid.innerHTML=arr.length?arr.map(p=>`<article><img src="${p.data}" alt="Progress photo"><span>${new Date(p.date).toLocaleDateString(undefined,{day:'numeric',month:'short'})}</span><button type="button" data-delete-photo="${p.id}" aria-label="Delete photo">×</button></article>`).join(''):'<div class="p2-photo-empty">Add front, side or back photos every 2–4 weeks.</div>';$$('[data-delete-photo]',grid).forEach(b=>b.onclick=()=>{savePhotos(arr.filter(p=>String(p.id)!==b.dataset.deletePhoto));renderPhotos()})}
function syncIndicator(){const host=$('.header-actions');if(!host)return;let b=$('#phase2SyncStatus');if(!b){b=document.createElement('button');b.id='phase2SyncStatus';b.className='p2-sync';b.type='button';b.title='Data status';b.innerHTML='<i></i><span></span>';host.prepend(b);b.onclick=()=>toast(b.dataset.detail||'')}const online=navigator.onLine,cloud=Boolean(window.MyBodyCloud?.accountMatches?.());b.classList.toggle('offline',!online);b.classList.toggle('cloud',online&&cloud);$('span',b).textContent=!online?'Offline':cloud?'Synced':'Saved';b.dataset.detail=!online?'Offline. Changes stay on this device until you reconnect.':cloud?'Cloud account connected. Your MYBODY data is saved and sync-enabled.':'Saved on this device.'}
function renderAll(){state=Store.read();foodTools();progressEnhancements();syncIndicator();enhanceExerciseCards();enhanceExerciseDetail()}
document.addEventListener('click',e=>{const done=e.target.closest('.set-done');if(done){setTimeout(()=>{if(done.classList.contains('saved'))startRest(restSeconds($('#exerciseDetailTitle')?.textContent||''))},30)}if(e.target.closest('[data-action="save-exercise-detail"]'))persistEffortAfterNativeSave();if(e.target.closest('[data-action="open-exercise-detail"],[data-action="select-day"],[data-tab="workout"],[data-tab="food"],[data-tab="progress"]'))setTimeout(renderAll,80)},true);
window.addEventListener('online',syncIndicator);window.addEventListener('offline',syncIndicator);window.addEventListener('mybody:state',e=>{state=e.detail||Store.read();setTimeout(renderAll,40)});
const observer=new MutationObserver(()=>{if(!document.body.dataset.p2render){document.body.dataset.p2render='1';requestAnimationFrame(()=>{delete document.body.dataset.p2render;renderAll()})}});
function init(){ensureRestTimer();renderAll();const targets=['exerciseList','exerciseSetRows','mealSections','progressList'].map(id=>document.getElementById(id)).filter(Boolean);targets.forEach(x=>observer.observe(x,{childList:true,subtree:true}))}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();