(function(){
'use strict';
const Store=window.MyBodyStore;
if(!Store)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const ADMIN_EMAIL='tausif.4946@gmail.com';
const ERROR_KEY='mybody.phase5.errors.v1';
const MAX_ERRORS=40;
let wired=false;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function build(){return document.querySelector('meta[name="app-build"]')?.content||document.getElementById('buildBadge')?.textContent?.replace(/\D+/g,'')||'—'}
function account(){try{return window.MyBodyCloud?.localAccount?.()||null}catch{return null}}
function isAdmin(){return String(account()?.email||'').toLowerCase()===ADMIN_EMAIL}
function errors(){try{return JSON.parse(localStorage.getItem(ERROR_KEY)||'[]')}catch{return[]}}
function saveErrors(list){try{localStorage.setItem(ERROR_KEY,JSON.stringify(list.slice(-MAX_ERRORS)))}catch{}}
function capture(type,message,source,line,col,stack){const list=errors();const sig=[type,message,source,line].join('|');const last=list[list.length-1];if(last?.sig===sig&&Date.now()-last.time<5000)return;list.push({sig,type,message:String(message||'Unknown error').slice(0,500),source:String(source||'').slice(0,220),line:line||0,col:col||0,stack:String(stack||'').slice(0,1600),time:Date.now(),build:build(),url:location.pathname,ua:navigator.userAgent.slice(0,260)});saveErrors(list)}
function setupErrorMonitoring(){window.addEventListener('error',e=>capture('error',e.message,e.filename,e.lineno,e.colno,e.error?.stack));window.addEventListener('unhandledrejection',e=>capture('promise',e.reason?.message||String(e.reason||'Unhandled promise rejection'),'','','',e.reason?.stack));}
function panel(){return $('#settings')||document.querySelector('[aria-labelledby="settings-tab"]')||$$('.panel').find(p=>/settings/i.test(p.id||'')||/settings/i.test(p.getAttribute('aria-labelledby')||''))}
function toast(m){const el=$('#appToast');if(!el)return;el.textContent=m;el.dataset.type='success';el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2300)}
function installed(){return window.matchMedia?.('(display-mode: standalone)').matches||navigator.standalone===true}
function onlineLabel(){return navigator.onLine?'Online':'Offline'}
function storageEstimate(){if(!navigator.storage?.estimate)return Promise.resolve(null);return navigator.storage.estimate().then(x=>({used:x.usage||0,quota:x.quota||0})).catch(()=>null)}
function fmtBytes(n){if(!n)return'0 MB';return `${(n/1048576).toFixed(n>10485760?0:1)} MB`}
function ensureLaunchCard(){const host=panel();if(!host||$('#p5LaunchCard'))return;const card=document.createElement('section');card.id='p5LaunchCard';card.className='card p5-launch';card.innerHTML=`<div class="p5-launch-head"><div><span>APP & PRIVACY</span><h3>MYBODY readiness</h3><p>Install, privacy, backup and diagnostics in one place.</p></div><b id="p5AppState">${installed()?'Installed':'Browser'}</b></div><div class="p5-status-grid"><div><small>Connection</small><strong id="p5Connection">${onlineLabel()}</strong></div><div><small>Build</small><strong>#${esc(build())}</strong></div><div><small>Storage</small><strong id="p5Storage">Checking…</strong></div></div><div class="p5-action-grid"><button type="button" class="secondary" data-p5="install">Install app</button><button type="button" class="secondary" data-p5="share">Share MYBODY</button><button type="button" class="secondary" data-p5="export">Export my data</button><button type="button" class="secondary" data-p5="privacy">Privacy</button><button type="button" class="secondary" data-p5="terms">Terms & safety</button>${isAdmin()?'<button type="button" class="secondary" data-p5="diagnostics">Diagnostics</button>':''}</div><p class="p5-footnote">Your fitness data remains available offline on this device. Cloud features depend on your signed-in account and connection.</p>`;
  const first=host.querySelector('.section-head');if(first)first.insertAdjacentElement('afterend',card);else host.prepend(card);
  storageEstimate().then(x=>{const el=$('#p5Storage');if(el)el.textContent=x?fmtBytes(x.used):'Local'});
  card.addEventListener('click',onAction);
}
function onAction(e){const a=e.target.closest('[data-p5]')?.dataset.p5;if(!a)return;if(a==='install')return installHelp();if(a==='share')return share();if(a==='export')return exportData();if(a==='privacy')return legal('privacy');if(a==='terms')return legal('terms');if(a==='diagnostics')return diagnostics()}
async function share(){const data={title:'MYBODY 2.0',text:'MYBODY 2.0 fitness and nutrition coach',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('App link copied')}}catch(e){if(e?.name!=='AbortError')toast('Unable to share right now')}}
function installHelp(){const existing=$('#webInstallPrompt:not(.hidden)');if(existing){existing.scrollIntoView({behavior:'smooth',block:'center'});return}const ios=/iPhone|iPad|iPod/i.test(navigator.userAgent);const android=/Android/i.test(navigator.userAgent);let body='Open this page in your browser and choose Add to Home Screen.';if(ios)body='In Safari, tap Share, then Add to Home Screen.';if(android)body='Open the browser menu and choose Install app or Add to Home screen.';simpleModal('Install MYBODY',installed()?'MYBODY is already installed on this device.':body)}
function exportData(){try{const data=Store.read();const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),build:build(),data},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mybody-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('MYBODY backup created')}catch{toast('Unable to export data')}}
function legal(kind){const privacy=`<h4>Privacy</h4><p>MYBODY stores fitness, nutrition, workout and progress data on your device and, when cloud sync is enabled, in the signed-in MYBODY account. The app does not need to sell personal data to provide its core tracking features.</p><p>Exercise, calorie-burn, body-composition and nutrition values are estimates. You control what you log and can export your local tracker data from Settings.</p><p>For account, privacy or deletion requests, contact the MYBODY app owner through the account channel used to access the app.</p>`;const terms=`<h4>Fitness & nutrition safety</h4><p>MYBODY provides general fitness and nutrition guidance. It is not a medical diagnosis, emergency service, or substitute for a physician, registered dietitian or other qualified clinician.</p><p>Stop exercise and seek appropriate medical care for chest pain, fainting, severe shortness of breath, acute injury or other concerning symptoms. Users with pregnancy, kidney disease, cardiovascular disease, uncontrolled hypertension, diabetes medication, recent surgery or an eating-disorder history should use clinician-guided targets where appropriate.</p><p>Training loads, calorie targets and projected goal dates are estimates and should be adjusted based on real-world progress, recovery and professional advice when needed.</p>`;legalModal(kind==='privacy'?'Privacy':'Terms & safety',kind==='privacy'?privacy:terms)}
function ensureModal(){let m=$('#p5Modal');if(!m){m=document.createElement('div');m.id='p5Modal';m.className='p5-modal hidden';m.innerHTML='<div class="p5-modal-panel" role="dialog" aria-modal="true"><header><h2 id="p5ModalTitle">MYBODY</h2><button type="button" class="p5-close" aria-label="Close">×</button></header><div id="p5ModalBody"></div></div>';document.body.appendChild(m);$('.p5-close',m).onclick=()=>closeModal();m.onclick=e=>{if(e.target===m)closeModal()}}return m}
function closeModal(){const m=$('#p5Modal');if(m)m.classList.add('hidden');if(!document.querySelector('.p5-modal:not(.hidden),.p3-modal:not(.hidden),.coach-modal:not(.hidden),.sheet-backdrop:not(.hidden)'))document.body.classList.remove('modal-open')}
function legalModal(title,html){const m=ensureModal();$('#p5ModalTitle',m).textContent=title;$('#p5ModalBody',m).innerHTML=`<div class="p5-legal">${html}</div>`;m.classList.remove('hidden');document.body.classList.add('modal-open')}
function simpleModal(title,body){legalModal(title,`<p>${esc(body)}</p>`)}
function diagnostics(){const list=errors().slice().reverse();const m=ensureModal();$('#p5ModalTitle',m).textContent='Diagnostics';$('#p5ModalBody',m).innerHTML=`<div class="p5-diag-head"><div><strong>${list.length}</strong><span>recent local errors</span></div><button type="button" class="secondary" id="p5ClearErrors">Clear</button></div><div class="p5-diag-list">${list.length?list.map(x=>`<article><div><b>${esc(x.type)}</b><span>${new Date(x.time).toLocaleString()}</span></div><strong>${esc(x.message)}</strong><small>Build #${esc(x.build)}${x.source?' • '+esc(x.source.split('/').pop()):''}${x.line?' :'+x.line:''}</small></article>`).join(''):'<p class="empty">No captured errors on this device.</p>'}</div>`;m.classList.remove('hidden');document.body.classList.add('modal-open');$('#p5ClearErrors',m).onclick=()=>{localStorage.removeItem(ERROR_KEY);diagnostics()}}
function profileCompleteness(){const host=$('#today');if(!host||$('#p5ProfileHint'))return;const s=Store.read(),cfg=s.config||{},missing=[];if(!cfg.age)missing.push('age');if(!cfg.height)missing.push('height');if(!cfg.goalWeight)missing.push('goal weight');if(!cfg.calories)missing.push('calorie target');if(!cfg.protein)missing.push('protein target');if(!missing.length)return;const card=document.createElement('section');card.id='p5ProfileHint';card.className='p5-profile-hint';card.innerHTML=`<div><strong>Finish your setup</strong><span>Add ${esc(missing.slice(0,3).join(', '))} for better coaching.</span></div><button type="button" class="secondary">Open settings</button>`;const anchor=$('#mybodyCoachCard',host)||host.querySelector('.section-head');anchor?.insertAdjacentElement('afterend',card);card.querySelector('button').onclick=()=>{const tab=$('[data-nav="settings"],#settings-tab');tab?.click()}}
function polishEmptyStates(){$$('.empty').forEach(el=>{const t=el.textContent.trim();if(!t||/nothing logged/i.test(t))el.textContent='Nothing here yet. Your first entry will appear here.';else if(/no .*yet/i.test(t)&&t.length<60)el.classList.add('p5-empty')})}
function optimizeMedia(root=document){$$('img',root).forEach(img=>{if(!img.hasAttribute('loading'))img.loading='lazy';if(!img.hasAttribute('decoding'))img.decoding='async'});$$('video',root).forEach(v=>{if(!v.hasAttribute('preload'))v.preload='metadata';v.setAttribute('playsinline','')})}
function enhanceAccessibility(){document.documentElement.classList.add('p5-ready');$$('button:not([type])').forEach(b=>b.type='button');$$('input[type="number"]').forEach(i=>{if(!i.inputMode)i.inputMode='decimal'});const main=document.querySelector('main');if(main&&!main.id)main.id='mainContent';if(!$('#p5Skip')){const a=document.createElement('a');a.id='p5Skip';a.className='p5-skip';a.href='#mainContent';a.textContent='Skip to content';document.body.prepend(a)}}
function statusUpdate(){const c=$('#p5Connection');if(c)c.textContent=onlineLabel();const s=$('#p5AppState');if(s)s.textContent=installed()?'Installed':'Browser'}
function initObserver(){const obs=new MutationObserver(ms=>{let needs=false;for(const m of ms){if(m.addedNodes.length){needs=true;for(const node of m.addedNodes){if(node.nodeType===1)optimizeMedia(node)}}}if(needs)requestAnimationFrame(()=>{polishEmptyStates();ensureLaunchCard();profileCompleteness()})});obs.observe(document.body,{childList:true,subtree:true})}
function init(){if(wired)return;wired=true;setupErrorMonitoring();enhanceAccessibility();optimizeMedia();ensureLaunchCard();profileCompleteness();polishEmptyStates();statusUpdate();initObserver();window.addEventListener('online',statusUpdate);window.addEventListener('offline',statusUpdate);window.MyBodyDiagnostics={errors,capture,clear:()=>localStorage.removeItem(ERROR_KEY),open:diagnostics}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();