document.addEventListener('DOMContentLoaded',function(){
'use strict';
var q=function(s){return document.querySelector(s)};
var touch=q('link[rel="apple-touch-icon"]');if(touch)touch.href='apple-touch-icon.png?v=141';else{touch=document.createElement('link');touch.rel='apple-touch-icon';touch.href='apple-touch-icon.png?v=141';document.head.appendChild(touch)}
var top=q('.topbar');if(top&&!q('#forceRefreshBtn')){var rb=document.createElement('button');rb.id='forceRefreshBtn';rb.type='button';rb.title='Refresh latest version';rb.setAttribute('aria-label','Refresh latest version');rb.textContent='↻';rb.style.cssText='position:absolute;right:52px;top:18px;width:38px;height:38px;border:1px solid var(--line);border-radius:50%;background:var(--card);color:var(--text);font-size:23px;font-weight:800;display:grid;place-items:center;z-index:25';rb.onclick=function(){rb.textContent='…';try{var u=new URL(location.href);u.searchParams.set('refresh',Date.now());if('serviceWorker'in navigator){navigator.serviceWorker.getRegistrations().then(function(rs){return Promise.all(rs.map(function(r){return r.update()}))}).finally(function(){location.replace(u.toString())})}else location.replace(u.toString())}catch(e){location.reload()}};top.appendChild(rb)}
var today=q('#today');
if(today){var energy=q('.app-shell>.energy-strip')||q('.energy-strip');var balance=today.querySelector('.balance-card');var combined=q('#combinedEnergyDashboard');if(!combined&&energy&&balance){combined=document.createElement('section');combined.id='combinedEnergyDashboard';combined.className='combined-energy-dashboard';today.insertBefore(combined,today.firstChild);combined.appendChild(energy);combined.appendChild(balance)}else if(combined&&combined.parentNode!==today){today.insertBefore(combined,today.firstChild)}if(!q('#quickActions')){var qa=document.createElement('section');qa.id='quickActions';qa.className='quick-actions';qa.innerHTML='<button data-tab-go="food"><b>＋</b><span>Log Food</span></button><button data-tab-go="workout"><b>✓</b><span>Workout</span></button><button data-focus="weightInput"><b>⚖</b><span>Weight</span></button><button data-focus="waterInput"><b>◉</b><span>Water</span></button>';if(combined)combined.insertAdjacentElement('afterend',qa);qa.addEventListener('click',function(e){var b=e.target.closest('button');if(!b)return;var tab=b.getAttribute('data-tab-go');if(tab){var t=q('.tab[data-tab="'+tab+'"]');if(t)t.click()}var id=b.getAttribute('data-focus');if(id){var el=q('#'+id);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(function(){el.focus()},300)}}});var scores=today.querySelector('.score-grid');var macro=document.createElement('section');macro.className='card macro-summary';macro.id='macroSummary';macro.innerHTML='<div class="macro-head"><div><p class="eyebrow">TODAY\'S MACROS</p><h3>Nutrition balance</h3></div><span id="macroKcal" class="pill">0 kcal</span></div><div class="macro-line"><span>Protein</span><div><i id="macroProteinBar"></i></div><b id="macroProteinText">0g</b></div><div class="macro-line"><span>Carbs</span><div><i id="macroCarbBar"></i></div><b id="macroCarbText">0g</b></div><div class="macro-line"><span>Fat</span><div><i id="macroFatBar"></i></div><b id="macroFatText">0g</b></div>';if(scores)scores.insertAdjacentElement('beforebegin',macro)}}
var old=q('#waistInput');if(old){var label=old.closest('label');if(label&&!q('#abdomenInput')){label.innerHTML='Belly / abdomen (in)<input id="abdomenInput" type="number" step="0.1" inputmode="decimal">';var x=document.createElement('label');x.innerHTML='Waist / pant line (in)<input id="pantWaistInput" type="number" step="0.1" inputmode="decimal">';label.insertAdjacentElement('afterend',x)}}
function updateMacros(){try{if(typeof state==='undefined'||typeof totals!=='function')return;var z=totals(),c=state.config||{},pt=Number(c.protein)||1,cal=Number(c.calories)||2000,ft=65,ct=Math.max(1,Math.round((cal-pt*4-ft*9)/4));var set=function(id,val){var e=q(id);if(e)e.textContent=val};var bar=function(id,v,t){var e=q(id);if(e)e.style.width=Math.min(100,Math.round((Number(v)||0)/Math.max(1,t)*100))+'%'};set('#macroKcal',Math.round(z.calories)+' / '+cal+' kcal');set('#macroProteinText',Math.round(z.protein)+' / '+pt+'g');set('#macroCarbText',Math.round(z.carbs)+' / '+ct+'g');set('#macroFatText',Math.round(z.fat)+' / '+ft+'g');bar('#macroProteinBar',z.protein,pt);bar('#macroCarbBar',z.carbs,ct);bar('#macroFatBar',z.fat,ft)}catch(e){console.error(e)}}
updateMacros();document.addEventListener('click',function(){setTimeout(updateMacros,80)});document.addEventListener('change',function(){setTimeout(updateMacros,80)});if(!document.querySelector('script[data-editors-fix]')){var s=document.createElement('script');s.src='editors-fix.js?v=141';s.setAttribute('data-editors-fix','1');document.body.appendChild(s)}
});