/* MYBODY 2.0 premium mobile UI enhancement */
(function(){
 const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
 function css(){if(q('#premiumUiCss'))return;const s=document.createElement('style');s.id='premiumUiCss';s.textContent=`
 :root{--accent:#8b7cff;--accent2:#52d6b0;--radius:24px}body{padding-bottom:96px}.topbar{position:sticky;top:0;z-index:20;padding:14px 4px 10px;background:color-mix(in srgb,var(--bg) 88%,transparent);backdrop-filter:blur(18px)}.topbar:after{content:'Your transformation, one day at a time';display:block;position:absolute;left:4px;bottom:-5px;font-size:10px;color:var(--muted)}
 .energy-strip{grid-template-columns:repeat(4,minmax(0,1fr));}.metric-card{min-height:104px;display:flex;flex-direction:column;justify-content:center}.metric-card strong{font-size:25px}.card,.metric-card{box-shadow:0 12px 32px #00000016}
 .tabs{position:fixed;z-index:30;left:0;right:0;bottom:0;margin:0;padding:8px max(12px,env(safe-area-inset-right)) calc(8px + env(safe-area-inset-bottom)) max(12px,env(safe-area-inset-left));background:color-mix(in srgb,var(--bg) 94%,transparent);backdrop-filter:blur(22px);border-top:1px solid var(--line);justify-content:center}.tab{flex:1;max-width:150px;border:0;background:transparent;padding:10px 5px;border-radius:15px;font-size:11px}.tab:before{display:block;font-size:18px;margin-bottom:3px}.tab[data-tab=today]:before{content:'⌂'}.tab[data-tab=workout]:before{content:'◉'}.tab[data-tab=food]:before{content:'◒'}.tab[data-tab=progress]:before{content:'▥'}.tab[data-tab=settings]:before{content:'⚙'}.tab.active{background:#8b7cff18;color:var(--accent)}
 .quick-actions{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:12px 0}.quick-action{border:1px solid var(--line);background:linear-gradient(145deg,var(--card),var(--card2));color:var(--text);border-radius:18px;padding:14px 6px;text-align:center;font-weight:750;font-size:11px}.quick-action b{display:grid;place-items:center;margin:0 auto 7px;width:36px;height:36px;border-radius:12px;background:#8b7cff18;color:var(--accent);font-size:18px}
 .macro-panel{padding:17px;margin:12px 0}.macro-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.macro-title h3{margin:0;font-size:18px}.macro-row{display:grid;grid-template-columns:70px 1fr auto;gap:10px;align-items:center;margin:12px 0;font-size:12px}.macro-track{height:9px;background:var(--bg);border-radius:20px;overflow:hidden}.macro-track i{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--accent),var(--accent2));border-radius:20px;transition:.3s}.macro-row strong{font-size:11px}
 .exercise{padding:17px}.exercise h4{font-size:17px}.exercise-num{width:34px;height:34px;border-radius:11px}.exercise-inputs label{font-size:10px}.exercise-inputs input{text-align:center;font-size:16px;font-weight:700}.exercise-actions{display:flex;gap:8px;margin-top:11px}.exercise-actions button,.exercise-actions a{flex:1;text-align:center;text-decoration:none;border:1px solid var(--line);background:var(--bg);color:var(--text);border-radius:11px;padding:9px;font-size:11px;font-weight:700}
 .meal-card{border-radius:24px}.meal-head>div>span{width:38px;height:38px;display:grid;place-items:center;background:#8b7cff15;border-radius:12px}.add-food{color:var(--accent)}
 @media(max-width:600px){body{padding-left:12px;padding-right:12px}.topbar h1{font-size:22px}.energy-strip{grid-template-columns:repeat(2,1fr);gap:9px}.metric-card{min-height:96px}.quick-actions{grid-template-columns:repeat(4,1fr)}.quick-action{padding:12px 3px}.balance-card{border-radius:26px}.balance-ring{width:86px;height:86px}.score-grid{grid-template-columns:repeat(2,1fr)}.insight-grid{grid-template-columns:repeat(3,1fr)}.insight{padding:12px}.insight strong{font-size:17px}.section-head h3{font-size:21px}.exercise-inputs{grid-template-columns:repeat(3,1fr)}}`;
 document.head.appendChild(s)}
 function go(tab){q(`.tab[data-tab="${tab}"]`)?.click();setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),30)}
 function dashboard(){const panel=q('#today');if(!panel||q('#quickActions'))return;const firstCard=panel.querySelector('.balance-card');const a=document.createElement('section');a.id='quickActions';a.className='quick-actions';a.innerHTML=`<button class="quick-action" data-go="food"><b>＋</b>Log food</button><button class="quick-action" data-go="workout"><b>✓</b>Workout</button><button class="quick-action" data-focus="weightInput"><b>⚖</b>Weight</button><button class="quick-action" data-focus="waterInput"><b>◉</b>Water</button>`;firstCard?.insertAdjacentElement('afterend',a);a.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go)go(b.dataset.go);if(b.dataset.focus){q('#'+b.dataset.focus)?.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>q('#'+b.dataset.focus)?.focus(),350)}});
 const scores=q('.score-grid');if(scores&&!q('#macroPanel')){const m=document.createElement('section');m.id='macroPanel';m.className='card macro-panel';m.innerHTML=`<div class="macro-title"><h3>Today's macros</h3><span class="pill" id="macroCalories">0 kcal</span></div><div class="macro-row"><span>Protein</span><div class="macro-track"><i id="pmProtein"></i></div><strong id="pmProteinTxt">0g</strong></div><div class="macro-row"><span>Carbs</span><div class="macro-track"><i id="pmCarbs"></i></div><strong id="pmCarbsTxt">0g</strong></div><div class="macro-row"><span>Fat</span><div class="macro-track"><i id="pmFat"></i></div><strong id="pmFatTxt">0g</strong></div>`;scores.insertAdjacentElement('beforebegin',m)}}
 function updateMacros(){if(typeof nutritionTotals!=='function'||typeof state==='undefined')return;const n=nutritionTotals(),c=state.config||{};const cal=q('#macroCalories');if(cal)cal.textContent=`${Math.round(n.calories)} / ${c.calories||0} kcal`;const targets={Protein:Number(c.protein)||1,Carbs:Math.max(1,Math.round(((Number(c.calories)||2000)-Number(c.protein||0)*4-(Number(c.fat)||65)*9)/4)),Fat:Number(c.fat)||65};for(const k of ['Protein','Carbs','Fat']){const v=Number(n[k.toLowerCase()])||0,t=targets[k];const bar=q('#pm'+k),txt=q('#pm'+k+'Txt');if(bar)bar.style.width=Math.min(100,v/t*100)+'%';if(txt)txt.textContent=`${Math.round(v)} / ${Math.round(t)}g`}}
 function exercises(){qa('#exerciseList .exercise').forEach((card,i)=>{if(card.querySelector('.exercise-actions'))return;const row=document.createElement('div');row.className='exercise-actions';row.innerHTML=`<button type="button" data-copy="${i}">Use last</button><button type="button" data-done="${i}">Mark done ✓</button>`;card.appendChild(row);row.querySelector('[data-done]')?.addEventListener('click',e=>{e.currentTarget.textContent='Completed ✓';e.currentTarget.style.color='var(--accent2)'});row.querySelector('[data-copy]')?.addEventListener('click',e=>{const k=Object.keys(state.workoutLog||{}).sort().reverse().find(d=>state.workoutLog[d]?.[selectedDay]?.exercises?.[i]);const x=k&&state.workoutLog[k][selectedDay].exercises[i];if(!x)return;e.currentTarget.closest('.exercise').querySelector('.ex-set').value=x.sets||'';e.currentTarget.closest('.exercise').querySelector('.ex-reps').value=x.reps||'';e.currentTarget.closest('.exercise').querySelector('.ex-weight').value=x.weight||'';e.currentTarget.textContent='Loaded ✓';e.currentTarget.closest('.exercise').querySelector('.ex-weight').dispatchEvent(new Event('input',{bubbles:true}))})})}
 function init(){css();dashboard();updateMacros();exercises();const obs=new MutationObserver(()=>{dashboard();updateMacros();exercises()});obs.observe(document.body,{childList:true,subtree:true});document.addEventListener('click',()=>setTimeout(updateMacros,50));document.addEventListener('input',()=>setTimeout(updateMacros,100))}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();