/* MYBODY 2.0 cloud authentication + sync */
(function(){
'use strict';
const URL='https://vucmcxkgpghnahnocirk.supabase.co';
const KEY='sb_publishable____2MhGKdMY2FWa_lgOT_w_454NS9Qg';
const LOCAL='decemberTracker.v1';
const ACCOUNTS_KEY='tausifTracker.accounts.v1';
const LOCAL_SESSION_KEY='tausifTracker.session.v1';
const ADMIN_EMAIL='tausif.4946@gmail.com';
const redirect=location.origin+location.pathname;
let session=null,syncTimer=null,activityTimer=null;
const headers=(token)=>({'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+(token||KEY)});
async function req(path,opts={}){const r=await fetch(URL+path,{...opts,headers:{...headers(opts.token),...(opts.headers||{})}});let x={};try{x=await r.json()}catch{}if(!r.ok)throw new Error(x.msg||x.message||x.error_description||x.error||'Request failed');return x}
function saveSession(s){session=s||null;if(s)localStorage.setItem('mybody.supabase.session',JSON.stringify(s));else localStorage.removeItem('mybody.supabase.session')}
function storedSession(){try{return JSON.parse(localStorage.getItem('mybody.supabase.session')||'null')}catch{return null}}
function localAccount(){try{const id=localStorage.getItem(LOCAL_SESSION_KEY)||'';const list=JSON.parse(localStorage.getItem(ACCOUNTS_KEY)||'[]');return list.find(a=>a.id===id)||null}catch{return null}}
function accountMatches(){const local=localAccount(),cloud=String(session?.user?.email||'').trim().toLowerCase();return Boolean(local?.email&&cloud&&String(local.email).trim().toLowerCase()===cloud)}
async function refresh(){const s=storedSession();if(!s?.refresh_token)return null;try{const n=await req('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:s.refresh_token})});saveSession(n);return n}catch{saveSession(null);return null}}
async function signup(email,password){const s=await req('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password,options:{emailRedirectTo:redirect}})});if(s?.access_token)saveSession(s);return s}
async function login(email,password){const local=localAccount();if(local?.email&&String(local.email).toLowerCase()!==String(email).trim().toLowerCase())throw new Error('Use the same email as the currently logged-in MYBODY profile.');const s=await req('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});saveSession(s);await pullOrMigrate();await recordActivity(true).catch(()=>false);return s}
async function forgot(email){await req('/auth/v1/recover',{method:'POST',body:JSON.stringify({email,redirect_to:redirect})});}
async function updatePassword(password){if(!session?.access_token)throw new Error('Open the reset link from your email first.');await req('/auth/v1/user',{method:'PUT',token:session.access_token,body:JSON.stringify({password})})}
async function logoutCloud(){if(session?.access_token)try{await req('/auth/v1/logout',{method:'POST',token:session.access_token})}catch{}saveSession(null)}
async function logoutApp(){try{const id=localStorage.getItem(LOCAL_SESSION_KEY),current=localStorage.getItem(LOCAL);if(id&&current)localStorage.setItem(`${LOCAL}.user.${id}`,current)}catch{}await logoutCloud();localStorage.removeItem(LOCAL_SESSION_KEY);location.reload()}
async function cloudGet(){if(!session?.user?.id||!accountMatches())return null;const r=await fetch(URL+'/rest/v1/user_tracker_data?user_id=eq.'+encodeURIComponent(session.user.id)+'&select=data,updated_at',{headers:headers(session.access_token)});if(!r.ok)return null;const a=await r.json();return a[0]||null}
async function cloudPut(data){if(!session?.user?.id||!accountMatches())return;await fetch(URL+'/rest/v1/user_tracker_data?on_conflict=user_id',{method:'POST',headers:{...headers(session.access_token),'Prefer':'resolution=merge-duplicates'},body:JSON.stringify({user_id:session.user.id,data,updated_at:new Date().toISOString()})})}
async function pullOrMigrate(){if(!accountMatches())return;const cloud=await cloudGet();let local=null;try{local=JSON.parse(localStorage.getItem(LOCAL)||'null')}catch{}if(cloud?.data&&Object.keys(cloud.data).length){localStorage.setItem(LOCAL,JSON.stringify(cloud.data));location.reload();return}if(local)await cloudPut(local)}
function queueSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>{try{const d=JSON.parse(localStorage.getItem(LOCAL)||'null');if(d&&accountMatches())cloudPut(d)}catch{}},800)}
const oldSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){oldSet.call(this,k,v);if(k===LOCAL&&session?.access_token&&accountMatches())queueSync()};
function appType(){const u=navigator.userAgent||'',standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(window.MyBodyAndroidHealth)return'Android App';if(/Android/i.test(u))return standalone?'Android PWA':'Android Web';if(/iPhone|iPad|iPod/i.test(u))return standalone?'iOS PWA':'iOS Web';return standalone?'PWA':'Web'}
function browserName(){const u=navigator.userAgent||'';if(/Edg\//.test(u))return'Edge';if(/CriOS|Chrome\//.test(u))return'Chrome';if(/FxiOS|Firefox\//.test(u))return'Firefox';if(/Safari\//.test(u))return'Safari';return'Other'}
function localName(){try{return JSON.parse(localStorage.getItem(LOCAL)||'{}')?.profile?.name||localAccount()?.name||''}catch{return localAccount()?.name||''}}
function appVersion(){return document.querySelector('meta[name="app-build"]')?.content||document.documentElement.dataset.build||''}
async function recordActivity(isLogin=false){if(!session?.access_token||!session?.user||!accountMatches())return false;const r=await fetch(URL+'/rest/v1/rpc/record_mybody_activity',{method:'POST',headers:headers(session.access_token),body:JSON.stringify({p_name:localName(),p_app_type:appType(),p_device:(navigator.userAgent||'').slice(0,160),p_browser:browserName(),p_app_version:String(appVersion()),p_is_login:Boolean(isLogin)})});return r.ok}
function isAdmin(){const local=String(localAccount()?.email||'').toLowerCase(),cloud=String(session?.user?.email||'').toLowerCase();return accountMatches()&&local===ADMIN_EMAIL&&cloud===ADMIN_EMAIL}
async function adminUsers(){if(!session?.access_token||!accountMatches())throw new Error('Sign in to the matching MYBODY Cloud account first.');if(!isAdmin())throw new Error('Admin access is limited to the MYBODY owner account.');const r=await fetch(URL+'/rest/v1/app_users?select=user_id,email,name,created_at,last_opened_at,last_login_at,app_type,browser,app_version,session_count&order=last_opened_at.desc.nullslast',{headers:headers(session.access_token)});let x=[];try{x=await r.json()}catch{}if(!r.ok)throw new Error(x.message||x.error||'Unable to load users.');return x}
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function closeProfile(){document.querySelectorAll('.cloud-auth-overlay').forEach(x=>x.remove())}
function modal(title,fields,action,goLabel='Continue',closeLabel='Close'){closeProfile();const o=document.createElement('div');o.className='cloud-auth-overlay';o.innerHTML=`<div class="card cloud-auth-card"><h2>${esc(title)}</h2>${fields}<p class="cloud-auth-msg"></p><button class="primary full cloud-go">${esc(goLabel)}</button><button class="text-btn full cloud-close">${esc(closeLabel)}</button></div>`;document.body.appendChild(o);o.querySelector('.cloud-close').onclick=()=>o.remove();o.querySelector('.cloud-go').onclick=async()=>{const b=o.querySelector('.cloud-go'),m=o.querySelector('.cloud-auth-msg');b.disabled=true;m.textContent='Please wait…';try{await action(o);if(!m.textContent||m.textContent==='Please wait…')m.textContent='Done.'}catch(e){m.textContent=e.message}finally{b.disabled=false}};return o}
function openProfile(){const local=localAccount(),name=localName()||local?.name||'User',email=local?.email||'';if(session?.user&&accountMatches()){const o=modal('Profile',`<p><strong>${esc(name)}</strong></p><p>${esc(email)}</p><p>Your tracker is synced to MYBODY 2.0 cloud.</p><button class="secondary full cloud-app-logout" type="button" style="margin-top:12px">Log out</button>`,async(x)=>{await cloudPut(JSON.parse(localStorage.getItem(LOCAL)||'{}'));await recordActivity(false);x.querySelector('.cloud-auth-msg').textContent='Synced now.'},'Sync now','Close');o.querySelector('.cloud-app-logout').onclick=logoutApp;return}
const o=modal('Profile',`<p><strong>${esc(name)}</strong></p><p>${esc(email)}</p><p>Cloud sync is not connected for this profile.</p><label>Password<input class="cloud-pass" type="password" autocomplete="current-password"></label><div style="display:flex;gap:8px;margin:10px 0"><button class="secondary cloud-create" type="button">Create cloud account</button><button class="text-btn cloud-forgot" type="button">Forgot password?</button></div><button class="secondary full cloud-app-logout" type="button" style="margin-top:12px">Log out</button>`,async(x)=>{await login(email,x.querySelector('.cloud-pass').value);location.reload()},'Connect cloud','Close');o.querySelector('.cloud-app-logout').onclick=logoutApp;o.querySelector('.cloud-create').onclick=async()=>{const m=o.querySelector('.cloud-auth-msg');try{await signup(email,o.querySelector('.cloud-pass').value);m.textContent='Cloud account created. Check your email if confirmation is required, then connect cloud.'}catch(e){m.textContent=e.message}};o.querySelector('.cloud-forgot').onclick=async()=>{const m=o.querySelector('.cloud-auth-msg');try{await forgot(email);m.textContent='Password reset email sent.'}catch(e){m.textContent=e.message}}}
function applyRequestedUI(){document.getElementById('shareAppBtn')?.remove();document.getElementById('userMenu')?.remove();const head=document.querySelector('#today > .section-head');const name=localName();if(head&&name){const eyebrow=head.querySelector('.eyebrow');const title=document.getElementById('todayLabel')||head.querySelector('h3');if(eyebrow)eyebrow.textContent='WELCOME';if(title)title.textContent=name}}
function addUI(){const host=document.querySelector('.header-actions')||document.querySelector('.topbar');if(!host)return;let b=document.querySelector('#cloudAccountBtn');if(!b){b=document.createElement('button');b.id='cloudAccountBtn';b.className='icon-btn';b.type='button';b.setAttribute('aria-label','Profile');b.textContent='👤';b.title='Profile';host.appendChild(b)}b.onclick=openProfile;applyRequestedUI()}
function recoveryUI(){const h=location.hash;if(!h.includes('access_token='))return;const p=new URLSearchParams(h.slice(1));const access_token=p.get('access_token'),refresh_token=p.get('refresh_token'),type=p.get('type');if(!access_token)return;session={access_token,refresh_token,user:null};req('/auth/v1/user',{token:access_token}).then(u=>{session.user=u;saveSession(session);if(type==='recovery'){const o=modal('Set new password',`<label>New password<input class="cloud-newpass" type="password" minlength="8"></label>`,async(x)=>{await updatePassword(x.querySelector('.cloud-newpass').value);history.replaceState(null,'',redirect);setTimeout(()=>location.reload(),600)},'Save password','Cancel')}})}
async function init(){recoveryUI();session=storedSession();if(session&&!session.user&&session.access_token)try{session.user=await req('/auth/v1/user',{token:session.access_token});saveSession(session)}catch{session=await refresh()}else if(session?.expires_at&&session.expires_at*1000<Date.now()+60000)session=await refresh();if(session?.user&&!accountMatches()){saveSession(null);session=null}addUI();setTimeout(applyRequestedUI,250);if(session?.user&&accountMatches()){await recordActivity(false).catch(()=>false);clearInterval(activityTimer);activityTimer=setInterval(()=>recordActivity(false).catch(()=>false),15*60*1000);window.addEventListener('focus',()=>recordActivity(false).catch(()=>false))}window.MyBodyAdminUI?.init?.()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
window.MyBodyCloud={signup,login,forgot,logout:logoutApp,logoutCloud,updatePassword,sync:async()=>{if(accountMatches())return cloudPut(JSON.parse(localStorage.getItem(LOCAL)||'{}'))},recordActivity,adminUsers,isAdmin,accountMatches,localAccount,openProfile};
})();