/* MYBODY 2.0 cloud authentication + sync */
(function(){
const URL='https://vucmcxkgpghnahnocirk.supabase.co';
const KEY='sb_publishable____2MhGKdMY2FWa_lgOT_w_454NS9Qg';
const LOCAL='decemberTracker.v1';
const ADMIN_EMAIL='tausif.4946@gmail.com';
const redirect=location.origin+location.pathname;
let session=null,syncTimer=null,activityTimer=null;
const headers=(token)=>({'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+(token||KEY)});
async function req(path,opts={}){const r=await fetch(URL+path,{...opts,headers:{...headers(opts.token),...(opts.headers||{})}});let x={};try{x=await r.json()}catch{}if(!r.ok)throw new Error(x.msg||x.message||x.error_description||x.error||'Request failed');return x}
function saveSession(s){session=s||null;if(s)localStorage.setItem('mybody.supabase.session',JSON.stringify(s));else localStorage.removeItem('mybody.supabase.session')}
function storedSession(){try{return JSON.parse(localStorage.getItem('mybody.supabase.session')||'null')}catch{return null}}
async function refresh(){const s=storedSession();if(!s?.refresh_token)return null;try{const n=await req('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:s.refresh_token})});saveSession(n);return n}catch{saveSession(null);return null}}
async function signup(email,password){const s=await req('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password,options:{emailRedirectTo:redirect}})});if(s?.access_token)saveSession(s);return s}
async function login(email,password){const s=await req('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});saveSession(s);await pullOrMigrate();await recordActivity(true).catch(()=>false);return s}
async function forgot(email){await req('/auth/v1/recover',{method:'POST',body:JSON.stringify({email,redirect_to:redirect})});}
async function updatePassword(password){if(!session?.access_token)throw new Error('Open the reset link from your email first.');await req('/auth/v1/user',{method:'PUT',token:session.access_token,body:JSON.stringify({password})})}
async function logout(){if(session?.access_token)try{await req('/auth/v1/logout',{method:'POST',token:session.access_token})}catch{}saveSession(null)}
async function cloudGet(){if(!session?.user?.id)return null;const r=await fetch(URL+'/rest/v1/user_tracker_data?user_id=eq.'+encodeURIComponent(session.user.id)+'&select=data,updated_at',{headers:headers(session.access_token)});if(!r.ok)return null;const a=await r.json();return a[0]||null}
async function cloudPut(data){if(!session?.user?.id)return;await fetch(URL+'/rest/v1/user_tracker_data?on_conflict=user_id',{method:'POST',headers:{...headers(session.access_token),'Prefer':'resolution=merge-duplicates'},body:JSON.stringify({user_id:session.user.id,data,updated_at:new Date().toISOString()})})}
async function pullOrMigrate(){const cloud=await cloudGet();let local=null;try{local=JSON.parse(localStorage.getItem(LOCAL)||'null')}catch{}if(cloud?.data&&Object.keys(cloud.data).length){localStorage.setItem(LOCAL,JSON.stringify(cloud.data));location.reload();return}if(local)await cloudPut(local)}
function queueSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>{try{const d=JSON.parse(localStorage.getItem(LOCAL)||'null');if(d)cloudPut(d)}catch{}},800)}
const oldSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){oldSet.call(this,k,v);if(k===LOCAL&&session?.access_token)queueSync()};
function appType(){const u=navigator.userAgent||'',standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(window.MyBodyAndroidHealth)return'Android App';if(/Android/i.test(u))return standalone?'Android PWA':'Android Web';if(/iPhone|iPad|iPod/i.test(u))return standalone?'iOS PWA':'iOS Web';return standalone?'PWA':'Web'}
function browserName(){const u=navigator.userAgent||'';if(/Edg\//.test(u))return'Edge';if(/CriOS|Chrome\//.test(u))return'Chrome';if(/FxiOS|Firefox\//.test(u))return'Firefox';if(/Safari\//.test(u))return'Safari';return'Other'}
function localName(){try{return JSON.parse(localStorage.getItem(LOCAL)||'{}')?.profile?.name||''}catch{return''}}
function appVersion(){return document.querySelector('meta[name="app-build"]')?.content||document.documentElement.dataset.build||''}
async function recordActivity(isLogin=false){if(!session?.access_token||!session?.user)return false;const r=await fetch(URL+'/rest/v1/rpc/record_mybody_activity',{method:'POST',headers:headers(session.access_token),body:JSON.stringify({p_name:localName(),p_app_type:appType(),p_device:(navigator.userAgent||'').slice(0,160),p_browser:browserName(),p_app_version:String(appVersion()),p_is_login:Boolean(isLogin)})});return r.ok}
function isAdmin(){return String(session?.user?.email||'').toLowerCase()===ADMIN_EMAIL}
async function adminUsers(){if(!session?.access_token)throw new Error('Sign in to MYBODY Cloud first.');if(!isAdmin())throw new Error('Admin access is limited to the MYBODY owner account.');const r=await fetch(URL+'/rest/v1/app_users?select=user_id,email,name,created_at,last_opened_at,last_login_at,app_type,browser,app_version,session_count&order=last_opened_at.desc.nullslast',{headers:headers(session.access_token)});let x=[];try{x=await r.json()}catch{}if(!r.ok)throw new Error(x.message||x.error||'Unable to load users.');return x}
function modal(title,fields,action){const o=document.createElement('div');o.className='cloud-auth-overlay';o.innerHTML=`<div class="card cloud-auth-card"><h2>${title}</h2>${fields}<p class="cloud-auth-msg"></p><button class="primary full cloud-go">Continue</button><button class="text-btn full cloud-close">Cancel</button></div>`;document.body.appendChild(o);o.querySelector('.cloud-close').onclick=()=>o.remove();o.querySelector('.cloud-go').onclick=async()=>{const b=o.querySelector('.cloud-go'),m=o.querySelector('.cloud-auth-msg');b.disabled=true;m.textContent='Please wait…';try{await action(o);m.textContent='Done.'}catch(e){m.textContent=e.message}finally{b.disabled=false}};return o}
function addUI(){const host=document.querySelector('.topbar');if(!host||document.querySelector('#cloudAccountBtn'))return;const b=document.createElement('button');b.id='cloudAccountBtn';b.className='icon-btn';b.textContent=session?.user?.email?'☁︎':'👤';b.title='Cloud account';host.appendChild(b);b.onclick=()=>{if(session?.user){modal('Cloud account',`<p>${session.user.email}</p><p>Your tracker is synced to MYBODY 2.0 cloud.</p>`,async(o)=>{await cloudPut(JSON.parse(localStorage.getItem(LOCAL)||'{}'));await recordActivity(false);o.querySelector('.cloud-auth-msg').textContent='Synced now.'});return}const o=modal('MYBODY 2.0 Account',`<label>Email<input class="cloud-email" type="email" autocomplete="email"></label><label>Password<input class="cloud-pass" type="password" autocomplete="current-password"></label><div style="display:flex;gap:8px;margin:10px 0"><button class="secondary cloud-create" type="button">Create account</button><button class="text-btn cloud-forgot" type="button">Forgot password?</button></div>`,async(x)=>{await login(x.querySelector('.cloud-email').value,x.querySelector('.cloud-pass').value);location.reload()});o.querySelector('.cloud-create').onclick=async()=>{const m=o.querySelector('.cloud-auth-msg');try{await signup(o.querySelector('.cloud-email').value,o.querySelector('.cloud-pass').value);m.textContent='Account created. Check your email if confirmation is required, then log in.'}catch(e){m.textContent=e.message}};o.querySelector('.cloud-forgot').onclick=async()=>{const m=o.querySelector('.cloud-auth-msg');try{await forgot(o.querySelector('.cloud-email').value);m.textContent='Password reset email sent.'}catch(e){m.textContent=e.message}}}}
function recoveryUI(){const h=location.hash;if(!h.includes('access_token='))return;const p=new URLSearchParams(h.slice(1));const access_token=p.get('access_token'),refresh_token=p.get('refresh_token'),type=p.get('type');if(!access_token)return;session={access_token,refresh_token,user:null};req('/auth/v1/user',{token:access_token}).then(u=>{session.user=u;saveSession(session);if(type==='recovery'){const o=modal('Set new password',`<label>New password<input class="cloud-newpass" type="password" minlength="8"></label>`,async(x)=>{await updatePassword(x.querySelector('.cloud-newpass').value);history.replaceState(null,'',redirect);setTimeout(()=>location.reload(),600)})}})}
async function init(){recoveryUI();session=storedSession();if(session&&!session.user&&session.access_token)try{session.user=await req('/auth/v1/user',{token:session.access_token});saveSession(session)}catch{session=await refresh()}else if(session?.expires_at&&session.expires_at*1000<Date.now()+60000)session=await refresh();addUI();if(session?.user){await recordActivity(false).catch(()=>false);clearInterval(activityTimer);activityTimer=setInterval(()=>recordActivity(false).catch(()=>false),15*60*1000);window.addEventListener('focus',()=>recordActivity(false).catch(()=>false))}window.MyBodyAdminUI?.init?.()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
window.MyBodyCloud={signup,login,forgot,logout,updatePassword,sync:async()=>cloudPut(JSON.parse(localStorage.getItem(LOCAL)||'{}')),recordActivity,adminUsers,isAdmin};
})();