create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null check (char_length(event_name) between 1 and 80),
  event_props jsonb not null default '{}'::jsonb,
  app_version text,
  app_type text,
  created_at timestamptz not null default now()
);

create index if not exists app_events_user_created_idx on public.app_events(user_id, created_at desc);
create index if not exists app_events_name_created_idx on public.app_events(event_name, created_at desc);

alter table public.app_events enable row level security;
drop policy if exists "users insert own app events" on public.app_events;
create policy "users insert own app events" on public.app_events for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "users read own app events" on public.app_events;
create policy "users read own app events" on public.app_events for select to authenticated using ((select auth.uid()) = user_id);

create table if not exists public.app_errors (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  error_type text not null default 'error',
  message text not null,
  source text,
  line_no integer,
  stack text,
  app_version text,
  app_type text,
  created_at timestamptz not null default now()
);

create index if not exists app_errors_user_created_idx on public.app_errors(user_id, created_at desc);
create index if not exists app_errors_created_idx on public.app_errors(created_at desc);

alter table public.app_errors enable row level security;
drop policy if exists "users insert own app errors" on public.app_errors;
create policy "users insert own app errors" on public.app_errors for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "users read own app errors" on public.app_errors;
create policy "users read own app errors" on public.app_errors for select to authenticated using ((select auth.uid()) = user_id);

create or replace function public.get_mybody_product_analytics()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce((select auth.jwt()->>'email'),'') <> 'tausif.4946@gmail.com' then
    raise exception 'Admin access required';
  end if;
  return jsonb_build_object(
    'events_7d', (select count(*) from public.app_events where created_at >= now() - interval '7 days'),
    'active_users_7d', (select count(distinct user_id) from public.app_events where created_at >= now() - interval '7 days'),
    'top_events_7d', coalesce((select jsonb_agg(x) from (select event_name, count(*) as count from public.app_events where created_at >= now() - interval '7 days' group by event_name order by count(*) desc limit 12) x),'[]'::jsonb),
    'builds_7d', coalesce((select jsonb_agg(x) from (select coalesce(app_version,'unknown') as build, count(*) as count from public.app_events where created_at >= now() - interval '7 days' group by app_version order by count(*) desc limit 8) x),'[]'::jsonb)
  );
end;
$$;

create or replace function public.get_mybody_error_summary()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce((select auth.jwt()->>'email'),'') <> 'tausif.4946@gmail.com' then
    raise exception 'Admin access required';
  end if;
  return jsonb_build_object(
    'errors_7d', (select count(*) from public.app_errors where created_at >= now() - interval '7 days'),
    'affected_users_7d', (select count(distinct user_id) from public.app_errors where created_at >= now() - interval '7 days'),
    'recent', coalesce((select jsonb_agg(x) from (select message, source, line_no, app_version, app_type, created_at from public.app_errors order by created_at desc limit 20) x),'[]'::jsonb)
  );
end;
$$;

revoke all on function public.get_mybody_product_analytics() from public;
revoke all on function public.get_mybody_error_summary() from public;
grant execute on function public.get_mybody_product_analytics() to authenticated;
grant execute on function public.get_mybody_error_summary() to authenticated;